/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import action.BeanTbl;
import action.Invoice;
import action.Sale;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.ClassCodRandon;
import model.ClassProductInvoice;
import model.ClassSale;
import util.DateActual;
import util.JTextFieldTools;
import util.Mascaras;
import xml.NewXML;

/**
 *
 * @author Rafael Recalcatti
 */
public class Frame_In_Budget extends javax.swing.JFrame {

    private final Color whiteColor = Color.white;                 // new Color(254, 254, 254);
    private final Color alternateColor = new Color(204, 204, 255);    // Color.lightGray;//new Color(204, 204, 204);
    private final Color selectedColor = Color.yellow;
    private Invoice invoice = new Invoice();
    private static boolean insertingInvoice = false;
    private static boolean controlEditHeaderInvoice = false;
    private MyModel tabela;
    private final List<String> lista = new ArrayList<>();
    private String par = null;
    private static final NewXML newXML = new NewXML();

    public Frame_In_Budget() {
        initComponents();
        bindingGroup.addBindingListener(new LoggingBindingListener(validationMsgLabel));
    }

    /**
     * Creates new form Frame_1
     *
     * @return
     */
    public action.Invoice getInvoice() {
        return invoice;
    }

    /**
     * Sets client to edit.
     *
     * @param invoice
     */
    public void setInvoice(action.Invoice invoice) {
        action.Invoice oldNotaFiscal = this.invoice;
        this.invoice = invoice;
        firePropertyChange("notaFiscal", oldNotaFiscal, invoice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductInvoice = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelPriceSaleActual = new javax.swing.JLabel();
        jPanelActionProductInvoice = new javax.swing.JPanel();
        jButtonNewProductInvoice = new javax.swing.JButton();
        jButtonSaveProductInvoice = new javax.swing.JButton();
        jButtonDeleteProductInvoice = new javax.swing.JButton();
        jPanelProductInvoice = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDescriptionProductInvoice = new javax.swing.JTextField();
        jTextFieldQuantityProductInvoice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldValueProductInvoice = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldBarCodeProductInvoice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldObservationProductInvoice = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanelHeaderInvoice = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        nfe_filial = new javax.swing.JTextField();
        nfe_fornecedores = new javax.swing.JComboBox(ClassProductInvoice.allVendor().toArray());
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nfe_num_nota = new javax.swing.JTextField();
        nfe_data_entrada = new JFormattedTextField(Mascaras.maskDate());
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nfe_serie = new javax.swing.JTextField();
        nfe_data_emissao = new JFormattedTextField(Mascaras.maskDate());
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nfe_total_nota = new javax.swing.JTextField();
        nfe_cfop = new javax.swing.JComboBox();
        jButtonLaunchInvoice = new javax.swing.JButton();
        nfe_valor_subst = new javax.swing.JTextField();
        nfe_valor_outros = new javax.swing.JTextField();
        nfe_valor_isento = new javax.swing.JTextField();
        nfe_base_icms = new javax.swing.JTextField();
        nfe_total_icms = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldCodControl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextValueAllProductsInvoice = new javax.swing.JTextField();
        validationMsgLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTableProductInvoice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableProductInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProductInvoice.setDefaultRenderer(Object.class, new MyCellRenderer());
        jTableProductInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductInvoiceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProductInvoice);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setText("Ultima Compra");

        jLabel12.setText("Média Compra");

        jLabel13.setText("Preço de Venda Atual");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("0.0");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("0.0");

        jLabelPriceSaleActual.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelPriceSaleActual.setForeground(new java.awt.Color(204, 0, 0));
        jLabelPriceSaleActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPriceSaleActual.setText("0.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel13)
                        .addGap(85, 85, 85)))
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabelPriceSaleActual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPriceSaleActual)
                .addContainerGap())
        );

        jPanelActionProductInvoice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButtonNewProductInvoice.setText("Novo Produto Nota");
        jButtonNewProductInvoice.setEnabled(false);
        jButtonNewProductInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewProductInvoiceActionPerformed(evt);
            }
        });

        jButtonSaveProductInvoice.setText("Gravar Produto Nota");
        jButtonSaveProductInvoice.setEnabled(false);
        jButtonSaveProductInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveProductInvoiceActionPerformed(evt);
            }
        });

        jButtonDeleteProductInvoice.setText("Excluir Selecionado");
        jButtonDeleteProductInvoice.setEnabled(false);
        jButtonDeleteProductInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteProductInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelActionProductInvoiceLayout = new javax.swing.GroupLayout(jPanelActionProductInvoice);
        jPanelActionProductInvoice.setLayout(jPanelActionProductInvoiceLayout);
        jPanelActionProductInvoiceLayout.setHorizontalGroup(
            jPanelActionProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionProductInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelActionProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNewProductInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSaveProductInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteProductInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelActionProductInvoiceLayout.setVerticalGroup(
            jPanelActionProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActionProductInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNewProductInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSaveProductInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteProductInvoice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProductInvoice.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos Nota"));

        jLabel7.setText("Descrição do Produto:");
        jLabel7.setEnabled(false);

        jTextFieldDescriptionProductInvoice.setColumns(40);
        jTextFieldDescriptionProductInvoice.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.descriptionProductInvoice}"), jTextFieldDescriptionProductInvoice, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldQuantityProductInvoice.setColumns(12);
        jTextFieldQuantityProductInvoice.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.quantityProductInvoice}"), jTextFieldQuantityProductInvoice, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(null);
        bindingGroup.addBinding(binding);

        jTextFieldQuantityProductInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityProductInvoiceActionPerformed(evt);
            }
        });
        jTextFieldQuantityProductInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQuantityProductInvoiceKeyReleased(evt);
            }
        });

        jLabel8.setText("Quantidade:");
        jLabel8.setEnabled(false);

        jLabel9.setText("R$ Unitário:");
        jLabel9.setEnabled(false);

        jTextFieldValueProductInvoice.setColumns(12);
        jTextFieldValueProductInvoice.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueProductInvoice}"), jTextFieldValueProductInvoice, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(null);
        bindingGroup.addBinding(binding);

        jTextFieldValueProductInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValueProductInvoiceActionPerformed(evt);
            }
        });
        jTextFieldValueProductInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldValueProductInvoiceKeyReleased(evt);
            }
        });

        jLabel17.setText("Código Barra:");
        jLabel17.setEnabled(false);

        jTextFieldBarCodeProductInvoice.setColumns(12);
        jTextFieldBarCodeProductInvoice.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.codBarProductInvoice}"), jTextFieldBarCodeProductInvoice, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldBarCodeProductInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBarCodeProductInvoiceActionPerformed(evt);
            }
        });
        jTextFieldBarCodeProductInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBarCodeProductInvoiceKeyReleased(evt);
            }
        });

        jLabel10.setText("Observações:");
        jLabel10.setEnabled(false);

        jTextFieldObservationProductInvoice.setColumns(20);
        jTextFieldObservationProductInvoice.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.observationProductInvoice}"), jTextFieldObservationProductInvoice, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldObservationProductInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldObservationProductInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProductInvoiceLayout = new javax.swing.GroupLayout(jPanelProductInvoice);
        jPanelProductInvoice.setLayout(jPanelProductInvoiceLayout);
        jPanelProductInvoiceLayout.setHorizontalGroup(
            jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductInvoiceLayout.createSequentialGroup()
                        .addGroup(jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jTextFieldBarCodeProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldObservationProductInvoice)))
                    .addGroup(jPanelProductInvoiceLayout.createSequentialGroup()
                        .addGroup(jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldDescriptionProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldQuantityProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldValueProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11))
        );
        jPanelProductInvoiceLayout.setVerticalGroup(
            jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductInvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDescriptionProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelProductInvoiceLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldValueProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelProductInvoiceLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldQuantityProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductInvoiceLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelProductInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductInvoiceLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBarCodeProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductInvoiceLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26))))
                    .addGroup(jPanelProductInvoiceLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldObservationProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanelProductInvoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelActionProductInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelActionProductInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton4.setText("jButton4");

        jButton5.setText("Deletar");

        jButton6.setText("Sair");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Finalizar Nota");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Imprimir Documento de Entrada");

        jButton9.setText("Editar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jPanelHeaderInvoice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel18.setText("Filial:");

        nfe_filial.setColumns(2);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.filialInvoice}"), nfe_filial, org.jdesktop.beansbinding.BeanProperty.create("text"), "Filial");
        binding.setValidator(null);
        bindingGroup.addBinding(binding);

        nfe_filial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_filialActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.vendorInvoice}"), nfe_fornecedores, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        nfe_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_fornecedoresActionPerformed(evt);
            }
        });
        nfe_fornecedores.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nfe_fornecedoresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nfe_fornecedoresFocusLost(evt);
            }
        });
        nfe_fornecedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nfe_fornecedoresKeyPressed(evt);
            }
        });

        jLabel20.setText("Fornecedores:");

        jLabel19.setText("Número:");

        nfe_num_nota.setColumns(10);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.numberInvoice}"), nfe_num_nota, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nfe_num_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_num_notaActionPerformed(evt);
            }
        });
        nfe_num_nota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nfe_num_notaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nfe_num_notaFocusLost(evt);
            }
        });

        nfe_data_entrada.setColumns(9);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.dateEntryInvoice}"), nfe_data_entrada, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel21.setText("Data Entrada:");

        jLabel22.setText("Serie:");

        nfe_serie.setColumns(3);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.seriesInvoive}"), nfe_serie, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nfe_serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_serieActionPerformed(evt);
            }
        });

        nfe_data_emissao.setColumns(9);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.dateEmissionInvoice}"), nfe_data_emissao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nfe_data_emissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_data_emissaoActionPerformed(evt);
            }
        });

        jLabel23.setText("Data Emissão:");

        jLabel24.setText("Total Nota:");

        nfe_total_nota.setColumns(7);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueTotalInvoice}"), nfe_total_nota, org.jdesktop.beansbinding.BeanProperty.create("text"), "Total Nota");
        binding.setValidator(null);
        bindingGroup.addBinding(binding);

        nfe_total_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_total_notaActionPerformed(evt);
            }
        });

        nfe_cfop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_cfopActionPerformed(evt);
            }
        });

        jButtonLaunchInvoice.setText("Lançar Nota");
        jButtonLaunchInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaunchInvoiceActionPerformed(evt);
            }
        });

        nfe_valor_subst.setColumns(7);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueSubstInvoice}"), nfe_valor_subst, org.jdesktop.beansbinding.BeanProperty.create("text"), "Valor Subst.");
        binding.setValidator(null);
        bindingGroup.addBinding(binding);

        nfe_valor_subst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_valor_substActionPerformed(evt);
            }
        });

        nfe_valor_outros.setColumns(7);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueOthersInvoice}"), nfe_valor_outros, org.jdesktop.beansbinding.BeanProperty.create("text"), "Valor Outros");
        binding.setValidator(null);
        bindingGroup.addBinding(binding);

        nfe_valor_outros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_valor_outrosActionPerformed(evt);
            }
        });

        nfe_valor_isento.setColumns(7);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueDutyInvoice}"), nfe_valor_isento, org.jdesktop.beansbinding.BeanProperty.create("text"), "Valor Isento");
        binding.setValidator(null);
        bindingGroup.addBinding(binding);

        nfe_valor_isento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_valor_isentoActionPerformed(evt);
            }
        });

        nfe_base_icms.setColumns(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.baseIcmsInvoice}"), nfe_base_icms, org.jdesktop.beansbinding.BeanProperty.create("text"), "Base ICMS");
        binding.setValidator(null);
        bindingGroup.addBinding(binding);

        nfe_base_icms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_base_icmsActionPerformed(evt);
            }
        });

        nfe_total_icms.setColumns(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.totalIcmsInvoice}"), nfe_total_icms, org.jdesktop.beansbinding.BeanProperty.create("text"), "Total ICMS");
        binding.setValidator(null);
        bindingGroup.addBinding(binding);

        nfe_total_icms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfe_total_icmsActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.observationInvoice}"), jTextArea1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jTextArea1);

        jTextField2.setColumns(20);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.transporter}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel4.setText("Transportador:");

        jLabel5.setText("Observações:");

        jLabel25.setText("Total ICMS:");

        jLabel26.setText("Base ICMS:");

        jLabel27.setText("Valor Isento:");

        jLabel28.setText("Valor Outros:");

        jLabel29.setText("Valor Subst:");

        jLabel30.setText("Valor Produtos:");

        jLabel31.setText("CFOP:");

        jTextFieldCodControl.setEditable(false);
        jTextFieldCodControl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldCodControl.setForeground(new java.awt.Color(204, 51, 0));
        jTextFieldCodControl.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.idInvoice}"), jTextFieldCodControl, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel6.setText("Cód. Controle:");

        jTextValueAllProductsInvoice.setColumns(7);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueAllProductsInvoice}"), jTextValueAllProductsInvoice, org.jdesktop.beansbinding.BeanProperty.create("text"), "Valor Produtos");
        bindingGroup.addBinding(binding);

        jTextValueAllProductsInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValueAllProductsInvoiceActionPerformed(evt);
            }
        });

        validationMsgLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        validationMsgLabel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 102, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.totalIcmsInvoice}"), jLabel1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel2.setForeground(new java.awt.Color(0, 102, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.baseIcmsInvoice}"), jLabel2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel3.setForeground(new java.awt.Color(0, 102, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueOthersInvoice}"), jLabel3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel32.setForeground(new java.awt.Color(0, 102, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueSubstInvoice}"), jLabel32, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel33.setForeground(new java.awt.Color(0, 102, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueDutyInvoice}"), jLabel33, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel34.setForeground(new java.awt.Color(0, 102, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueAllProductsInvoice}"), jLabel34, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel35.setForeground(new java.awt.Color(0, 102, 0));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${invoice.valueTotalInvoice}"), jLabel35, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanelHeaderInvoiceLayout = new javax.swing.GroupLayout(jPanelHeaderInvoice);
        jPanelHeaderInvoice.setLayout(jPanelHeaderInvoiceLayout);
        jPanelHeaderInvoiceLayout.setHorizontalGroup(
            jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderInvoiceLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validationMsgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nfe_filial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nfe_data_emissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nfe_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nfe_data_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                                .addComponent(nfe_total_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24))
                                    .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nfe_fornecedores, 0, 124, Short.MAX_VALUE)
                                            .addComponent(nfe_num_nota))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)))
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nfe_base_icms, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(nfe_total_icms))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextFieldCodControl)))
                            .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nfe_cfop, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextValueAllProductsInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonLaunchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nfe_valor_subst, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nfe_valor_outros, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nfe_valor_isento, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(4, 4, 4)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(20, 20, 20))
        );
        jPanelHeaderInvoiceLayout.setVerticalGroup(
            jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                            .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nfe_filial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nfe_total_icms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nfe_fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nfe_base_icms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jTextFieldCodControl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nfe_valor_isento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(nfe_num_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nfe_valor_outros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel28))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nfe_valor_subst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29)))
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel30)
                                .addComponent(jTextValueAllProductsInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nfe_cfop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)))
                    .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLaunchInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nfe_data_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelHeaderInvoiceLayout.createSequentialGroup()
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nfe_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nfe_data_emissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelHeaderInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nfe_total_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)))
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(validationMsgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelHeaderInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeaderInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewProductInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewProductInvoiceActionPerformed
        jTextFieldBarCodeProductInvoice.requestFocus(true);
        activeItens(jPanelProductInvoice, true);
        activeButton(jButtonSaveProductInvoice, true);
        activeButton(jButtonNewProductInvoice, false);

    }//GEN-LAST:event_jButtonNewProductInvoiceActionPerformed

    private void jButtonSaveProductInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveProductInvoiceActionPerformed
        jTextFieldBarCodeProductInvoice.requestFocus(true);
        System.err.println("Produto Codigo:" + invoice.getCodBarProductInvoice());
        System.err.println("Produto QTD:" + invoice.getQuantityProductInvoice());
        if (ClassProductInvoice.newProductInvoice(invoice)) {

            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso.");

            try {
                BeanTbl.setPar(jTextFieldCodControl.getText());
                tabela = new MyModel();
                jTableProductInvoice.setModel(tabela);
            } catch (Exception ex) {

                System.err.println("ERROR::" + ex);
                ////newXML.generateLog(ex.toString());
            }

            clearJText(jPanelProductInvoice);
            activeButton(jButtonSaveProductInvoice, false);
            activeButton(jButtonNewProductInvoice, true);
            jTextFieldBarCodeProductInvoice.requestFocus(true);

        } else {

            JOptionPane.showMessageDialog(null, "Erro ao gravar o produto. Tente novamente.");

        }
    }//GEN-LAST:event_jButtonSaveProductInvoiceActionPerformed

    private void nfe_filialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_filialActionPerformed
        nfe_fornecedores.requestFocus();
    }//GEN-LAST:event_nfe_filialActionPerformed

    private void nfe_num_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_num_notaActionPerformed
        nfe_serie.requestFocus();
    }//GEN-LAST:event_nfe_num_notaActionPerformed

    private void nfe_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_fornecedoresActionPerformed
        nfe_num_nota.requestFocus(true);
    }//GEN-LAST:event_nfe_fornecedoresActionPerformed

    private void nfe_data_emissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_data_emissaoActionPerformed
        nfe_total_nota.requestFocus(true);
    }//GEN-LAST:event_nfe_data_emissaoActionPerformed

    private void nfe_total_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_total_notaActionPerformed
        nfe_total_icms.requestFocus(true);
    }//GEN-LAST:event_nfe_total_notaActionPerformed

    private void jButtonDeleteProductInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteProductInvoiceActionPerformed
        for (int i = 0; i < jTableProductInvoice.getRowCount(); i++) {

            if (jTableProductInvoice.getValueAt(i, 0).equals(true)) {
                lista.add((String) jTableProductInvoice.getValueAt(i, 5));
            }

        }
        if (lista.size() > 0) {

            par = lista.toString().replace("[", "(").replace("]", ")");

            ClassProductInvoice.deleteProductInvoice(par, jTextFieldCodControl.getText());
            try {
                BeanTbl.setPar(jTextFieldCodControl.getText());
                tabela = new MyModel();
                jTableProductInvoice.setModel(tabela);
            } catch (Exception ex) {

                System.err.println("ERROR::" + ex);
                ////newXML.generateLog(ex.toString());
            }

        } else {

            JOptionPane.showMessageDialog(null, "Selecione pelo menos um item na tabela.", "Impressão", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteProductInvoiceActionPerformed

    private void jButtonLaunchInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaunchInvoiceActionPerformed

        if (validationMsgLabel.getText().equals("")) {
            if (!controlEditHeaderInvoice) {
                if (!ClassProductInvoice.validNumberInvoice(nfe_num_nota.getText(), nfe_fornecedores.getSelectedItem().toString())) {

                    do {

                        jTextFieldCodControl.setText(ClassCodRandon.codeGeneratorInvoice());
                        insertingInvoice = ClassProductInvoice.newHeaderInvoice(invoice);

                    } while (!insertingInvoice);

                    if (insertingInvoice) {

                        JOptionPane.showMessageDialog(null, "Nota cadastrada com sucesso.\n Você já pode cadastrar os produtos da nota.");
                        activeItens(jPanelHeaderInvoice, false);
                        activeItens(jPanelActionProductInvoice, true);
                        jButtonSaveProductInvoice.setEnabled(false);
                        jButtonNewProductInvoice.requestFocus(true);

                    } else {

                        JOptionPane.showMessageDialog(null, "Erro ao lançar a nota.");

                    }
                } else {

                    nfe_num_nota.setBackground(Color.red);
                    nfe_num_nota.setForeground(Color.yellow);
                    JOptionPane.showMessageDialog(null, "Este fornecedor já possui uma nota com este número cadastrada. Verifique.");
                    nfe_num_nota.requestFocus(true);
                }
            } else {

                JOptionPane.showMessageDialog(null, "Cabeçario da nota atualizdo com sucesso.");
                controlEditHeaderInvoice = false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Existem campos com valores inválidos.");
        }
    }//GEN-LAST:event_jButtonLaunchInvoiceActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //nfe_data_emissao.setValue(DataAtual.setData(new Date(), "dd/MM/yyyy"));
        nfe_data_entrada.setValue(DateActual.setDate(new Date(), "dd/MM/yyyy"));
        nfe_filial.setText("1");
        nfe_serie.setText("1");
        nfe_fornecedores.setSelectedIndex(0);

    }//GEN-LAST:event_formWindowOpened

    private void nfe_num_notaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nfe_num_notaFocusGained
        nfe_num_nota.setBackground(Color.white);
        nfe_num_nota.setForeground(Color.black);

        if (nfe_num_nota.getText().length() > 0) {
            nfe_num_nota.setSelectionStart(0);
            nfe_num_nota.setSelectionEnd(nfe_num_nota.getText().length());
        }
    }//GEN-LAST:event_nfe_num_notaFocusGained

    private void nfe_num_notaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nfe_num_notaFocusLost
        if (ClassProductInvoice.validNumberInvoice(nfe_num_nota.getText(), nfe_fornecedores.getSelectedItem().toString())) {
            nfe_num_nota.setBackground(Color.red);
            nfe_num_nota.setForeground(Color.yellow);
        }
    }//GEN-LAST:event_nfe_num_notaFocusLost

    private void nfe_fornecedoresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nfe_fornecedoresFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nfe_fornecedoresFocusGained

    private void nfe_fornecedoresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nfe_fornecedoresFocusLost
        if (!nfe_num_nota.getText().isEmpty()) {
            if (ClassProductInvoice.validNumberInvoice(nfe_num_nota.getText(), nfe_fornecedores.getSelectedItem().toString())) {
                nfe_num_nota.setBackground(Color.red);
                nfe_num_nota.setForeground(Color.yellow);
            } else {
                nfe_num_nota.setBackground(Color.white);
                nfe_num_nota.setForeground(Color.black);
            }
        }
    }//GEN-LAST:event_nfe_fornecedoresFocusLost

    private void nfe_fornecedoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nfe_fornecedoresKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            nfe_num_nota.requestFocus();
        }
    }//GEN-LAST:event_nfe_fornecedoresKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTableProductInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductInvoiceMouseClicked
        /*
         for (int i = 0; i < jTableProductInvoice.getRowCount(); i++) {

         if (jTableProductInvoice.getValueAt(i, 0).equals(true)) {
         lista.add((String) jTableProductInvoice.getValueAt(i, 5));
         }
         //lista.add((String) jTableProductInvoice.getValueAt(jTableProductInvoice.getSelectedRow(), 5));
         }
         if (lista.size() > 0) {
         par = lista.toString().replace("[", "(").replace("]", ")");
         ClassProductInvoice.setSelected(par);
         }
         */

        //if (evt.getClickCount() == 1) {
        refreshBean(jTextFieldCodControl.getText(), (String) jTableProductInvoice.getValueAt(jTableProductInvoice.getSelectedRow(), 5));//

        //}
    }//GEN-LAST:event_jTableProductInvoiceMouseClicked

    private void jTextFieldBarCodeProductInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBarCodeProductInvoiceActionPerformed
        //jButtonSaveProductInvoice.requestFocus(true);
        JTextFieldTools.validarValor(jTextFieldBarCodeProductInvoice);

        if (jTextFieldBarCodeProductInvoice.getText().length() >= 7) {

            int consultProd = ClassSale.searchProduct(jTextFieldBarCodeProductInvoice.getText(), false, 0, false, false);

            if (consultProd == 0) {
                jTextFieldDescriptionProductInvoice.setText(String.valueOf(Sale.getProductName()));
                jLabelPriceSaleActual.setText(String.valueOf(Sale.getProductPrice()));

                jTextFieldQuantityProductInvoice.requestFocus(true);
            } else if (consultProd == 1) {

                JOptionPane.showMessageDialog(null, "Produto nao cadastrado");
                jTextFieldBarCodeProductInvoice.setText("");
            }
        }
    }//GEN-LAST:event_jTextFieldBarCodeProductInvoiceActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        activeItens(jPanelHeaderInvoice, true);
        controlEditHeaderInvoice = true;
        nfe_filial.requestFocus(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void nfe_total_icmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_total_icmsActionPerformed
        nfe_base_icms.requestFocus(true);
    }//GEN-LAST:event_nfe_total_icmsActionPerformed

    private void nfe_base_icmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_base_icmsActionPerformed
        nfe_valor_isento.requestFocus(true);
    }//GEN-LAST:event_nfe_base_icmsActionPerformed

    private void nfe_valor_isentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_valor_isentoActionPerformed
        nfe_valor_outros.requestFocus(true);
    }//GEN-LAST:event_nfe_valor_isentoActionPerformed

    private void nfe_valor_outrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_valor_outrosActionPerformed
        nfe_valor_subst.requestFocus(true);
    }//GEN-LAST:event_nfe_valor_outrosActionPerformed

    private void nfe_valor_substActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_valor_substActionPerformed
        jTextValueAllProductsInvoice.requestFocus(true);
    }//GEN-LAST:event_nfe_valor_substActionPerformed

    private void jTextValueAllProductsInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValueAllProductsInvoiceActionPerformed
        nfe_cfop.requestFocus(true);
    }//GEN-LAST:event_jTextValueAllProductsInvoiceActionPerformed

    private void nfe_cfopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_cfopActionPerformed
        jButtonLaunchInvoice.requestFocus();
    }//GEN-LAST:event_nfe_cfopActionPerformed

    private void nfe_serieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfe_serieActionPerformed
        nfe_data_emissao.requestFocus();
    }//GEN-LAST:event_nfe_serieActionPerformed

    private void jTextFieldBarCodeProductInvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBarCodeProductInvoiceKeyReleased


    }//GEN-LAST:event_jTextFieldBarCodeProductInvoiceKeyReleased

    private void jTextFieldQuantityProductInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityProductInvoiceActionPerformed
        jTextFieldValueProductInvoice.requestFocus(true);
    }//GEN-LAST:event_jTextFieldQuantityProductInvoiceActionPerformed

    private void jTextFieldValueProductInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValueProductInvoiceActionPerformed
        jButtonSaveProductInvoice.requestFocus(true);
    }//GEN-LAST:event_jTextFieldValueProductInvoiceActionPerformed

    private void jTextFieldObservationProductInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldObservationProductInvoiceActionPerformed
        jButtonSaveProductInvoice.requestFocus(true);
    }//GEN-LAST:event_jTextFieldObservationProductInvoiceActionPerformed

    private void jTextFieldQuantityProductInvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantityProductInvoiceKeyReleased
        JTextFieldTools.formatJTextNumber(jTextFieldQuantityProductInvoice);
    }//GEN-LAST:event_jTextFieldQuantityProductInvoiceKeyReleased

    private void jTextFieldValueProductInvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValueProductInvoiceKeyReleased
        JTextFieldTools.formatJTextNumber(jTextFieldValueProductInvoice);
    }//GEN-LAST:event_jTextFieldValueProductInvoiceKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.err.println("value::" + invoice.getValueProductInvoice());
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println("ERROR::" + ex);
            //newXML.generateLog(ex.toString());
            java.util.logging.Logger.getLogger(Frame_In_Budget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame_In_Budget().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDeleteProductInvoice;
    private javax.swing.JButton jButtonLaunchInvoice;
    private javax.swing.JButton jButtonNewProductInvoice;
    private javax.swing.JButton jButtonSaveProductInvoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPriceSaleActual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelActionProductInvoice;
    private javax.swing.JPanel jPanelHeaderInvoice;
    private javax.swing.JPanel jPanelProductInvoice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTableProductInvoice;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldBarCodeProductInvoice;
    private javax.swing.JTextField jTextFieldCodControl;
    private javax.swing.JTextField jTextFieldDescriptionProductInvoice;
    private javax.swing.JTextField jTextFieldObservationProductInvoice;
    private javax.swing.JTextField jTextFieldQuantityProductInvoice;
    private javax.swing.JTextField jTextFieldValueProductInvoice;
    private static javax.swing.JTextField jTextValueAllProductsInvoice;
    private static javax.swing.JTextField nfe_base_icms;
    private static javax.swing.JComboBox nfe_cfop;
    private static javax.swing.JFormattedTextField nfe_data_emissao;
    private static javax.swing.JFormattedTextField nfe_data_entrada;
    private static javax.swing.JTextField nfe_filial;
    private static javax.swing.JComboBox nfe_fornecedores;
    private static javax.swing.JTextField nfe_num_nota;
    private static javax.swing.JTextField nfe_serie;
    private static javax.swing.JTextField nfe_total_icms;
    private static javax.swing.JTextField nfe_total_nota;
    private static javax.swing.JTextField nfe_valor_isento;
    private static javax.swing.JTextField nfe_valor_outros;
    private static javax.swing.JTextField nfe_valor_subst;
    private javax.swing.JLabel validationMsgLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    class MyCellRenderer extends DefaultTableCellRenderer {

        public MyCellRenderer() {
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused,
                int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);

            Color bg;

            if (!selected) {
                bg = ((row % 2 == 0)
                        ? alternateColor
                        : whiteColor);
            } else {
                bg = selectedColor;
            }

            if (jTableProductInvoice.getRowCount() > 0) {

                jTableProductInvoice.getColumnModel().getColumn(0).setPreferredWidth(40);
                jTableProductInvoice.getColumnModel().getColumn(1).setPreferredWidth(200);// define a largura da coluna
                jTableProductInvoice.getColumnModel().getColumn(2).setPreferredWidth(400);
                jTableProductInvoice.getColumnModel().getColumn(3).setPreferredWidth(100);
                jTableProductInvoice.getColumnModel().getColumn(4).setPreferredWidth(100);// define a largura da coluna
                jTableProductInvoice.getColumnModel().getColumn(5).setPreferredWidth(0);

            }

            //jTable1.setShowHorizontalLines(true);
            jTableProductInvoice.setShowVerticalLines(true);
            setBackground(bg);
            setForeground(selected
                    ? Color.black
                    : new java.awt.Color(102, 102, 102));
            setHorizontalAlignment(SwingConstants.CENTER);

            /*
             *  if (value instanceof ImageIcon) {
             * setIcon((ImageIcon) value);
             * setText("");
             * } else
             * setIcon(null);
             */
            return this;
        }
    }

    private void clearJText(JPanel panel) {

        java.awt.Component[] components = panel.getComponents();

        javax.swing.JTextField jTextField = null;

        for (Component component : components) {
            if (component instanceof javax.swing.JTextField) {
                jTextField = (javax.swing.JTextField) component;
                jTextField.setText("");
            }
        }
        String str = jTextFieldCodControl.getText();

    }

    private void activeItens(JPanel panel, boolean isEnable) {

        java.awt.Component[] components = panel.getComponents();

        javax.swing.JTextField jTextField = null;
        javax.swing.JLabel jLabel = null;
        javax.swing.JComboBox jComboBox = null;
        javax.swing.JButton jButton = null;
        javax.swing.JTextArea jTextArea = null;

        for (Component component : components) {
            if (component instanceof javax.swing.JTextField) {
                jTextField = (javax.swing.JTextField) component;
                jTextField.setEnabled(isEnable);
            }
            if (component instanceof javax.swing.JLabel) {
                jLabel = (javax.swing.JLabel) component;
                jLabel.setEnabled(isEnable);
            }
            if (component instanceof javax.swing.JComboBox) {
                jComboBox = (javax.swing.JComboBox) component;
                jComboBox.setEnabled(isEnable);
            }
            if (component instanceof javax.swing.JButton) {
                jButton = (javax.swing.JButton) component;
                jButton.setEnabled(isEnable);
            }
            if (component instanceof javax.swing.JTextArea) {
                jTextArea = (javax.swing.JTextArea) component;
                jTextArea.setEnabled(isEnable);
            }
        }
    }

    private void activeButton(javax.swing.JButton jButton, boolean isEnable) {

        jButton.setEnabled(isEnable);

    }

    private Object todosFornecedores() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private Object todosCfop() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void refreshBean(String arg, String arg2) {

        Invoice invoiceNew = (ClassProductInvoice.consultProductInvoice(arg, arg2));
        Invoice oldInvoice = invoice;
        invoice = invoiceNew;
        firePropertyChange("invoice", oldInvoice, invoiceNew);
        //jFormattedTextDataVenda.setText(DataAtual.setData(new Date()));

    }
}
