/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import action.Bean;
import action.BeanProductTransition;
import java.awt.Color;
import java.awt.Component;
import java.lang.reflect.Method;
import java.sql.Time;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import reports.ImprimirRelatorio_2;
import util.DateActual;
import util.Mascaras;
import static util.Moeda.DINHEIRO_REAL;
import static util.Moeda.mascaraDinheiro;
import xml.NewXML;

/**
 *
 * @author User
 */
public class JDialogGroupedProductSales extends javax.swing.JDialog {

    private final Color whiteColor = Color.white;                 // new Color(254, 254, 254);
    private final Color alternateColor = new Color(227, 227, 227);    // Color.lightGray;//new Color(204, 204, 204);
    private final Color selectedColor = Color.yellow;
    private static final NewXML newXML = new NewXML();
    private static final List<String> str_status = new ArrayList<>();
    private static MyModelJTableChekedSales myModelJTableChekedSales;
    private static String sql = "";
    private static boolean selected = false;
    private static final List<String> allCodCoupons = new ArrayList<>();
    private static String codeSale;
    private static final DecimalFormat v = new DecimalFormat("0.00");
    private static MyModelJtableDetaialSale myModelJtableDetaialSale;
    private static final DateFormat dateFormat_sql = new SimpleDateFormat("YYYY/MM/dd");
    private static final DateFormat dateFormat = new SimpleDateFormat("dd/MM/YYYY");
    private static String startDate;
    private static String endDate;
    private Object startHour;
    private Object endHour;
    private static boolean isCanceled = false;
    private static int algin = 0;

    /**
     * Creates new form JDialogAllSales
     *
     * @param parent
     * @param modal
     */
    public JDialogGroupedProductSales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAlgin = new javax.swing.ButtonGroup();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableGroupedProductSale = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jButtonBuscarVendas = new javax.swing.JButton();
        jDateChooserStart = new com.toedter.calendar.JDateChooser();
        jDateChooserEnd = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jFormattedTexfieldHourEnd = new javax.swing.JFormattedTextField(Mascaras.maskHour());
        jButtonUpTime = new javax.swing.JButton();
        jButtonDownTime = new javax.swing.JButton();
        jCheckBoxCanceledProduct = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jFormattedTexfieldHourStart = new javax.swing.JFormattedTextField(Mascaras.maskHour());
        jButtonUpTime1 = new javax.swing.JButton();
        jButtonDownTime1 = new javax.swing.JButton();
        jTextFieldbarCode = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jRadioButtonMenuItemAlignLeft = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemAlignCenter = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemAlignRight = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busca de Vendas por Produtos Agrupados");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos Vendidos: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        jTableGroupedProductSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableGroupedProductSale.setRowHeight(20);
        jTableGroupedProductSale.setDefaultRenderer(Object.class, new MyCellRenderer());
        jTableGroupedProductSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGroupedProductSaleMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableGroupedProductSale);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        jButtonBuscarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/11379_32x32.png"))); // NOI18N
        jButtonBuscarVendas.setText("Buscar  ");
        jButtonBuscarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarVendasActionPerformed(evt);
            }
        });

        jDateChooserStart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Inicio:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        jDateChooserStart.setDate(new Date());

        jDateChooserEnd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Fim:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        jDateChooserEnd.setDate(new Date());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora Fim:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jFormattedTexfieldHourEnd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTexfieldHourEnd.setText("00:00");
        jFormattedTexfieldHourEnd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTexfieldHourEndFocusLost(evt);
            }
        });
        jFormattedTexfieldHourEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTexfieldHourEndActionPerformed(evt);
            }
        });

        jButtonUpTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[000686].png"))); // NOI18N
        jButtonUpTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpTimeActionPerformed(evt);
            }
        });

        jButtonDownTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[000676].png"))); // NOI18N
        jButtonDownTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jFormattedTexfieldHourEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUpTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDownTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTexfieldHourEnd)
                    .addComponent(jButtonUpTime, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonDownTime, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jCheckBoxCanceledProduct.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jCheckBoxCanceledProduct.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBoxCanceledProduct.setText("Cancelado");
        jCheckBoxCanceledProduct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxCanceledProductItemStateChanged(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora Inicio:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jFormattedTexfieldHourStart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTexfieldHourStart.setText("00:00");
        jFormattedTexfieldHourStart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTexfieldHourStartFocusLost(evt);
            }
        });
        jFormattedTexfieldHourStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTexfieldHourStartActionPerformed(evt);
            }
        });

        jButtonUpTime1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[000686].png"))); // NOI18N
        jButtonUpTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpTime1ActionPerformed(evt);
            }
        });

        jButtonDownTime1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[000676].png"))); // NOI18N
        jButtonDownTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownTime1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jFormattedTexfieldHourStart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUpTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDownTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTexfieldHourStart)
                    .addComponent(jButtonUpTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonDownTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jTextFieldbarCode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldbarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbarCodeActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010681].png"))); // NOI18N
        jButton2.setText("Imprimir (Ctrl+P)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDateChooserEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserStart, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jButtonBuscarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldbarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxCanceledProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jTextFieldbarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxCanceledProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooserStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButtonBuscarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))))
        );

        jMenu3.setText("Arquivo");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Imprimir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        jMenuEdit.setText("Editar");

        buttonGroupAlgin.add(jRadioButtonMenuItemAlignLeft);
        jRadioButtonMenuItemAlignLeft.setText("Alinhar à Esquerda");
        jRadioButtonMenuItemAlignLeft.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonMenuItemAlignLeftItemStateChanged(evt);
            }
        });
        jMenuEdit.add(jRadioButtonMenuItemAlignLeft);

        buttonGroupAlgin.add(jRadioButtonMenuItemAlignCenter);
        jRadioButtonMenuItemAlignCenter.setSelected(true);
        jRadioButtonMenuItemAlignCenter.setText("Alinhar  Justificado");
        jRadioButtonMenuItemAlignCenter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonMenuItemAlignCenterItemStateChanged(evt);
            }
        });
        jMenuEdit.add(jRadioButtonMenuItemAlignCenter);

        buttonGroupAlgin.add(jRadioButtonMenuItemAlignRight);
        jRadioButtonMenuItemAlignRight.setText("Alinhar à Direita");
        jRadioButtonMenuItemAlignRight.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonMenuItemAlignRightItemStateChanged(evt);
            }
        });
        jMenuEdit.add(jRadioButtonMenuItemAlignRight);

        jMenuBar2.add(jMenuEdit);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed


    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTableGroupedProductSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGroupedProductSaleMouseClicked

        if (evt.getClickCount() == 2) {

            BeanProductTransition.setControl(true);
            BeanProductTransition.setCode(jTableGroupedProductSale.getValueAt(jTableGroupedProductSale.getSelectedRow(), 1).toString());
            new JDialogProduct_2_0(null, true).setVisible(true);
        }


    }//GEN-LAST:event_jTableGroupedProductSaleMouseClicked

    private void jButtonBuscarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarVendasActionPerformed

        try {
            Method something = this.getClass().getDeclaredMethod("fnSearchGroupedProducts", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR::" + ex);

        }

    }//GEN-LAST:event_jButtonBuscarVendasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            Method something = this.getClass().getDeclaredMethod("fnPrint", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR::" + ex);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jCheckBoxCanceledProductItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxCanceledProductItemStateChanged

        isCanceled = jCheckBoxCanceledProduct.isSelected();

    }//GEN-LAST:event_jCheckBoxCanceledProductItemStateChanged

    private void jRadioButtonMenuItemAlignLeftItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemAlignLeftItemStateChanged

        algin = -1;
        try {
            Method something
                    = this.getClass().getDeclaredMethod("fnSearchGroupedProducts", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR COMPLETE TABLE LINE 1136::" + ex);

        }
    }//GEN-LAST:event_jRadioButtonMenuItemAlignLeftItemStateChanged

    private void jRadioButtonMenuItemAlignCenterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemAlignCenterItemStateChanged

        algin = 0;
        try {
            Method something
                    = this.getClass().getDeclaredMethod("fnSearchGroupedProducts", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR COMPLETE TABLE LINE 1136::" + ex);

        }
    }//GEN-LAST:event_jRadioButtonMenuItemAlignCenterItemStateChanged

    private void jRadioButtonMenuItemAlignRightItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemAlignRightItemStateChanged

        algin = 1;
        try {
            Method something
                    = this.getClass().getDeclaredMethod("fnSearchGroupedProducts", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR COMPLETE TABLE LINE 1136::" + ex);

        }
    }//GEN-LAST:event_jRadioButtonMenuItemAlignRightItemStateChanged

    private void jFormattedTexfieldHourEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTexfieldHourEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTexfieldHourEndActionPerformed

    private void jButtonUpTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpTimeActionPerformed
          try {
            
            SimpleDateFormat formatador = new SimpleDateFormat("HH:mm");
            Date data;
            data = formatador.parse(jFormattedTexfieldHourEnd.getText().replaceAll("_", "0"));
            Time time = new Time(data.getTime());
            jFormattedTexfieldHourEnd.setText(DateActual.incrementTime(time, 1));
            
        } catch (ParseException ex) {
            Logger.getLogger(JDialogGroupedProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUpTimeActionPerformed

    private void jButtonDownTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownTimeActionPerformed
        try {
            
            SimpleDateFormat formatador = new SimpleDateFormat("HH:mm");
            Date data;
            data = formatador.parse(jFormattedTexfieldHourEnd.getText().replaceAll("_", "0"));
            Time time = new Time(data.getTime());
            jFormattedTexfieldHourEnd.setText(DateActual.incrementTime(time, -1));
            
        } catch (ParseException ex) {
            Logger.getLogger(JDialogGroupedProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDownTimeActionPerformed

    private void jFormattedTexfieldHourEndFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTexfieldHourEndFocusLost
       DateActual.validImputTime(jFormattedTexfieldHourEnd);
    }//GEN-LAST:event_jFormattedTexfieldHourEndFocusLost

    private void jFormattedTexfieldHourStartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTexfieldHourStartFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTexfieldHourStartFocusLost

    private void jFormattedTexfieldHourStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTexfieldHourStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTexfieldHourStartActionPerformed

    private void jButtonUpTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpTime1ActionPerformed
       try {
            
            SimpleDateFormat formatador = new SimpleDateFormat("HH:mm");
            Date data;
            data = formatador.parse(jFormattedTexfieldHourStart.getText().replaceAll("_", "0"));
            Time time = new Time(data.getTime());
            jFormattedTexfieldHourStart.setText(DateActual.incrementTime(time, 1));
            
        } catch (ParseException ex) {
            Logger.getLogger(JDialogGroupedProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUpTime1ActionPerformed

    private void jButtonDownTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownTime1ActionPerformed
        try {
            
            SimpleDateFormat formatador = new SimpleDateFormat("HH:mm");
            Date data;
            data = formatador.parse(jFormattedTexfieldHourStart.getText().replaceAll("_", "0"));
            Time time = new Time(data.getTime());
            jFormattedTexfieldHourStart.setText(DateActual.incrementTime(time, -1));
            
        } catch (ParseException ex) {
            Logger.getLogger(JDialogGroupedProductSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDownTime1ActionPerformed

    private void jTextFieldbarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbarCodeActionPerformed
        
        try {
            Method something = this.getClass().getDeclaredMethod("fnSearchGroupedProductsFilter", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR::" + ex);

        }
    }//GEN-LAST:event_jTextFieldbarCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGroupedProductSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogGroupedProductSales dialog = new JDialogGroupedProductSales(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAlgin;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscarVendas;
    private javax.swing.JButton jButtonDownTime;
    private javax.swing.JButton jButtonDownTime1;
    private javax.swing.JButton jButtonUpTime;
    private javax.swing.JButton jButtonUpTime1;
    private javax.swing.JCheckBox jCheckBoxCanceledProduct;
    private com.toedter.calendar.JDateChooser jDateChooserEnd;
    private com.toedter.calendar.JDateChooser jDateChooserStart;
    private javax.swing.JFormattedTextField jFormattedTexfieldHourEnd;
    private javax.swing.JFormattedTextField jFormattedTexfieldHourStart;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAlignCenter;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAlignLeft;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAlignRight;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableGroupedProductSale;
    private javax.swing.JTextField jTextFieldbarCode;
    // End of variables declaration//GEN-END:variables

    public void fnPrint() {

        ImprimirRelatorio_2 imprimirRelatorio_2 = new ImprimirRelatorio_2();
        Object[] par = {"PAR_INI_DATE", "PAR_END_DATE", "PAR_IS_CANC", "PAR_FILTER"};
        String str_sta = dateFormat.format(jDateChooserStart.getCalendar().getTime());
        String str_end = dateFormat.format(jDateChooserEnd.getCalendar().getTime());
        String filter = "Das "+startHour+" horas do dia " +str_sta+" até as "+endHour+" horas do dia "+str_end; 
        Object[] valuePar = {startDate + " " + startHour, endDate + " " + endHour, isCanceled, filter};
        imprimirRelatorio_2.visualizarRelatorio(valuePar, par, "reportGroupedProductSales.jasper", true);

    }


    public void fnSearchGroupedProducts() {

        startDate = dateFormat_sql.format(jDateChooserStart.getCalendar().getTime());
        endDate = dateFormat_sql.format(jDateChooserEnd.getCalendar().getTime());

        startHour = (jFormattedTexfieldHourStart.getText());
        endHour = (jFormattedTexfieldHourEnd.getText());

        String[] header = {"Descrição", "Código", "Quantidade", "ValorTotal"};
        ArrayList<Object> arg = new ArrayList<>();
        arg.add(startDate + " " + startHour);
        arg.add(endDate + " " + endHour);
        arg.add(isCanceled);

        ClassMyModelTable.popTable(jTableGroupedProductSale,
                "SELECT "
                + " p.`prod_description_product` AS Descrição,"
                + " pc.`prod_bar_code_product` AS Código,"
                + " SUM(pc.`product_quantity`) AS Quantidade,"
                + " SUM(pc.`product_quantity` * pc.`product_price`) AS ValorTotal"
                + " FROM tbl_coupon t INNER JOIN tbl_product_coupon pc ON t.`idtbl_coupon` = pc.`idtbl_coupon` "
                + " INNER JOIN tbl_product p ON pc.`prod_bar_code_product` = p.`prod_bar_code_product` "
                + " WHERE DATE_FORMAT(t.`date_hour_coupon`,'%Y/%m/%d %H:%i') BETWEEN ? AND ?  AND pc.`isToCancel` = ?"
                + " GROUP BY pc.`prod_bar_code_product` ORDER BY p.`prod_description_product`", header, arg, false);
        
        String valueTotal = String.valueOf(fnCalculateTotalValue());
        String str = String.valueOf(jTableGroupedProductSale.getModel().getRowCount());
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos Vendidos: "+str+"  -  Total:"+valueTotal+" ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N
    }
    
    public void fnSearchGroupedProductsFilter() {

        startDate = dateFormat_sql.format(jDateChooserStart.getCalendar().getTime());
        endDate = dateFormat_sql.format(jDateChooserEnd.getCalendar().getTime());

        startHour = (jFormattedTexfieldHourStart.getText());
        endHour = (jFormattedTexfieldHourEnd.getText());

        String[] header = {"Descrição", "Código", "Quantidade", "ValorTotal"};
        ArrayList<Object> arg = new ArrayList<>();
        arg.add(startDate + " " + startHour);
        arg.add(endDate + " " + endHour);
        arg.add(isCanceled);
        arg.add(jTextFieldbarCode.getText());

        ClassMyModelTable.popTable(jTableGroupedProductSale,
                "SELECT "
                + " p.`prod_description_product` AS Descrição,"
                + " pc.`prod_bar_code_product` AS Código,"
                + " SUM(pc.`product_quantity`) AS Quantidade,"
                + " SUM(pc.`product_quantity` * pc.`product_price`) AS ValorTotal"
                + " FROM tbl_coupon t INNER JOIN tbl_product_coupon pc ON t.`idtbl_coupon` = pc.`idtbl_coupon` "
                + " INNER JOIN tbl_product p ON pc.`prod_bar_code_product` = p.`prod_bar_code_product` "
                + " WHERE DATE_FORMAT(t.`date_hour_coupon`,'%Y/%m/%d %H:%i') BETWEEN ? AND ?  AND pc.`isToCancel` = ? AND pc.`prod_bar_code_product` = ? "
                + " GROUP BY pc.`prod_bar_code_product` ORDER BY p.`prod_description_product`", header, arg, false);
        
        String valueTotal = String.valueOf(fnCalculateTotalValue());
        String str = String.valueOf(jTableGroupedProductSale.getModel().getRowCount());
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos Vendidos: "+str+"  -  Total:"+valueTotal+" ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N
    }

    private String fnCalculateTotalValue() {
      
        double total = 0;
        
        for(int i = 0; i<jTableGroupedProductSale.getModel().getRowCount(); i++){
            
            total += Double.parseDouble(jTableGroupedProductSale.getModel().getValueAt(i, 3).toString().replace(",", "."));
            
        }
        return mascaraDinheiro(total, DINHEIRO_REAL);
    }

    class MyCellRenderer extends DefaultTableCellRenderer {

        public MyCellRenderer() {
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused,
                int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);

            Color bg;

            if (!selected) {
                bg = ((row % 2 == 0)
                        ? alternateColor
                        : whiteColor);
            } else {
                bg = selectedColor;
            }

            if (jTableGroupedProductSale.getRowCount() > 0) {

                jTableGroupedProductSale.getColumnModel().getColumn(0).setPreferredWidth(300);
                jTableGroupedProductSale.getColumnModel().getColumn(1).setPreferredWidth(180);// define a largura da coluna
                jTableGroupedProductSale.getColumnModel().getColumn(2).setPreferredWidth(30);
                jTableGroupedProductSale.getColumnModel().getColumn(3).setPreferredWidth(30);

            

            switch (algin) {

                case -1:
                    setHorizontalAlignment(SwingConstants.LEFT);
                    break;
                case 0:
                    setHorizontalAlignment(SwingConstants.CENTER);
                    break;
                case 1:
                    setHorizontalAlignment(SwingConstants.RIGHT);
                    break;

            }
           }
            //jTableItens.setShowHorizontalLines(false);
            //jTableItens.setShowVerticalLines(false);

            setBackground(bg);
            setForeground(selected
                    ? Color.black
                    : new java.awt.Color(102, 102, 102));

            setVerticalAlignment(SwingConstants.CENTER);

            ((DefaultTableCellRenderer) jTableGroupedProductSale.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

            /*
             *  if (value instanceof ImageIcon) {
             * setIcon((ImageIcon) value);
             * setText(""); 
             * } else
             * setIcon(null);
             */
            return this;
        }
    }
}
