/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import action.BeanLogin;
import action.Cashier;
import java.awt.AWTEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.AWTEventListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.ClassCashier;
import model.ClassUser;
import testes.PrintCoupon;
import util.CriaArquivoResumoCaixa;
import util.DateActual;
import util.ImpressaoJPS;
import util.JTextFieldTools;
import util.Sons;
import static view.JFrameSale_1.*;
import xml.NewXML;

/**
 *
 * @author Rafael Recalcatti
 */
public class JDialogCloseCashier_4_2 extends javax.swing.JDialog {

    public static MyModelJtableDetailedReport detailedReport;
    private final Color whiteColor = Color.white;                 // new Color(254, 254, 254);
    private final Color alternateColor = new Color(204, 204, 255);    // Color.lightGray;//new Color(204, 204, 204);
    private final Color selectedColor = Color.yellow;
    private static boolean controle;
    private static final String[] head_tbl = {"Data/Hora", "Usuário", "Valor", "Turno", "Terminal", "Descrição"};
    private static final DecimalFormat v = new DecimalFormat("0.00");
    private Cashier cashier = new Cashier();
    private static final NewXML newXML = new NewXML();
    private MyModelJtableMovementCashier jtableMovementCashier;
    private static URI uri;

    /**  //AWTUtilities.setWindo
     * Creates new form JDialogOpenCaixa
     *
     * @param parent
     * @param modal
     */
    public JDialogCloseCashier_4_2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //AWTUtilities.setWindowOpacity(this, 0.3f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jDialogMovement = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMovementCashier = new javax.swing.JTable();
        jDialogPassword = new javax.swing.JDialog();
        jPasswordField1 = new javax.swing.JPasswordField();
        jDialogDetailedReportCashier = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDetailedReportCashier = new javax.swing.JTable();
        jPopupMenuDetailedReportCashier = new javax.swing.JPopupMenu();
        jMenuItemPrintSelected = new javax.swing.JMenuItem();
        jMenuItemPrintReportDetailedCashier = new javax.swing.JMenuItem();
        jMenuItemPrintAllCouponValuesThisCashierSelected = new javax.swing.JMenuItem();
        jMenuItemExitDetailedReportCashier = new javax.swing.JMenuItem();
        decimalConverter1 = new action.DecimalConverter();
        dateConverter1 = new action.DateConverter();
        decimalConverterReal1 = new action.DecimalConverterReal();
        panelOpenCaixa = new javax.swing.JPanel();
        text_data_abertura_caixa = new javax.swing.JTextField();
        text_hora_abertura_caixa = new javax.swing.JTextField();
        text_valor_inic_abert_caixa = new javax.swing.JTextField();
        text_terminal_abertura_caixa = new javax.swing.JTextField();
        text_data_fechamento_caixa = new javax.swing.JTextField();
        text_usuario_fechamento_caixa = new javax.swing.JTextField();
        text_turno_abertura_caixa = new javax.swing.JTextField();
        text_usuario_abertura_caixa = new javax.swing.JTextField();
        panelCloseCaixa = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        text_valor_suprimento_caixa = new javax.swing.JTextField();
        text_valor_sangria_caixa = new javax.swing.JTextField();
        text_saldo_caixa = new javax.swing.JTextField();
        jLabel_view_insercao = new javax.swing.JLabel();
        jLabel_view_sangria = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        text_valor_final_dinheiro = new javax.swing.JTextField();
        text_valor_final_cartao = new javax.swing.JTextField();
        jLabelQuantityCash = new javax.swing.JLabel();
        jLabelQuantityCard = new javax.swing.JLabel();
        text_valor_final_discount_card = new javax.swing.JTextField();
        jLabelQuantityCardDiscount = new javax.swing.JLabel();
        text_valor_final_discount_cash = new javax.swing.JTextField();
        jLabelQuantityCashDiscount = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCloseCashier = new javax.swing.JMenuItem();
        jMenuItemDetailedReportCashier = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();

        jDialogMovement.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogMovement.setTitle("Detalhes Movimentos");
        jDialogMovement.setModal(true);
        jDialogMovement.setType(java.awt.Window.Type.UTILITY);
        jDialogMovement.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialogMovementWindowActivated(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTableMovementCashier.setAutoCreateRowSorter(true);
        jTableMovementCashier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMovementCashier.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableMovementCashier.setDoubleBuffered(true);
        jTableMovementCashier.setDragEnabled(true);
        jTableMovementCashier.setRowHeight(18);
        jTableMovementCashier.setSurrendersFocusOnKeystroke(true);
        jTableMovementCashier.setUpdateSelectionOnSort(false);
        jTableMovementCashier.setDefaultRenderer(Object.class, new MyCellRenderer());
        jScrollPane1.setViewportView(jTableMovementCashier);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogMovement.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jDialogPassword.setTitle("Entre com o código validador :");
        jDialogPassword.setAlwaysOnTop(true);
        jDialogPassword.setModal(true);
        jDialogPassword.setType(java.awt.Window.Type.UTILITY);

        jPasswordField1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 16), new java.awt.Color(153, 153, 153))); // NOI18N
        jPasswordField1.setPreferredSize(new java.awt.Dimension(8, 50));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jDialogPasswordLayout = new javax.swing.GroupLayout(jDialogPassword.getContentPane());
        jDialogPassword.getContentPane().setLayout(jDialogPasswordLayout);
        jDialogPasswordLayout.setHorizontalGroup(
            jDialogPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jDialogPasswordLayout.setVerticalGroup(
            jDialogPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPasswordLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jDialogDetailedReportCashier.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        jDialogDetailedReportCashier.setResizable(false);
        jDialogDetailedReportCashier.setType(java.awt.Window.Type.POPUP);
        jDialogDetailedReportCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDialogDetailedReportCashierMouseReleased(evt);
            }
        });
        jDialogDetailedReportCashier.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialogDetailedReportCashierWindowActivated(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseReleased(evt);
            }
        });

        jTableDetailedReportCashier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDetailedReportCashier.setRowHeight(23);
        jTableDetailedReportCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableDetailedReportCashierMouseReleased(evt);
            }
        });
        jTableDetailedReportCashier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableDetailedReportCashierKeyPressed(evt);
            }
        });
        jTableDetailedReportCashier.setDefaultRenderer(Object.class, new MyCellRenderer());
        jScrollPane2.setViewportView(jTableDetailedReportCashier);

        javax.swing.GroupLayout jDialogDetailedReportCashierLayout = new javax.swing.GroupLayout(jDialogDetailedReportCashier.getContentPane());
        jDialogDetailedReportCashier.getContentPane().setLayout(jDialogDetailedReportCashierLayout);
        jDialogDetailedReportCashierLayout.setHorizontalGroup(
            jDialogDetailedReportCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDetailedReportCashierLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogDetailedReportCashierLayout.setVerticalGroup(
            jDialogDetailedReportCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jMenuItemPrintSelected.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPrintSelected.setText("Imprimir Selecionado");
        jMenuItemPrintSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintSelectedActionPerformed(evt);
            }
        });
        jPopupMenuDetailedReportCashier.add(jMenuItemPrintSelected);

        jMenuItemPrintReportDetailedCashier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPrintReportDetailedCashier.setText("Imprimir Delátorio Detalhado ");
        jMenuItemPrintReportDetailedCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintReportDetailedCashierActionPerformed(evt);
            }
        });
        jPopupMenuDetailedReportCashier.add(jMenuItemPrintReportDetailedCashier);

        jMenuItemPrintAllCouponValuesThisCashierSelected.setText("Imprimir Valores dos Cupons do(s) Caixa(s) Selecionado(s)");
        jMenuItemPrintAllCouponValuesThisCashierSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintAllCouponValuesThisCashierSelectedActionPerformed(evt);
            }
        });
        jPopupMenuDetailedReportCashier.add(jMenuItemPrintAllCouponValuesThisCashierSelected);

        jMenuItemExitDetailedReportCashier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemExitDetailedReportCashier.setText("Sair");
        jMenuItemExitDetailedReportCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitDetailedReportCashierActionPerformed(evt);
            }
        });
        jPopupMenuDetailedReportCashier.add(jMenuItemExitDetailedReportCashier);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fechamento de Caixa");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelOpenCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abertura de Caixa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        panelOpenCaixa.setForeground(new java.awt.Color(153, 153, 153));

        text_data_abertura_caixa.setEditable(false);
        text_data_abertura_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_data_abertura_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_data_abertura_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Abertura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_data_abertura_caixa.setVerifyInputWhenFocusTarget(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.date_open_cashier}"), text_data_abertura_caixa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        text_hora_abertura_caixa.setEditable(false);
        text_hora_abertura_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_hora_abertura_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_hora_abertura_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora Abertura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_hora_abertura_caixa.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.hour_open_cashier}"), text_hora_abertura_caixa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        text_valor_inic_abert_caixa.setEditable(false);
        text_valor_inic_abert_caixa.setFont(new java.awt.Font("Arial", 3, 17)); // NOI18N
        text_valor_inic_abert_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_valor_inic_abert_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turno Aberto Com:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_valor_inic_abert_caixa.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.value_started_cashier}"), text_valor_inic_abert_caixa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(decimalConverterReal1);
        bindingGroup.addBinding(binding);

        text_terminal_abertura_caixa.setEditable(false);
        text_terminal_abertura_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_terminal_abertura_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_terminal_abertura_caixa.setText("1");
        text_terminal_abertura_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Terminal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_terminal_abertura_caixa.setVerifyInputWhenFocusTarget(false);

        text_data_fechamento_caixa.setEditable(false);
        text_data_fechamento_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_data_fechamento_caixa.setForeground(new java.awt.Color(204, 0, 0));
        text_data_fechamento_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_data_fechamento_caixa.setText("29/12/2014");
        text_data_fechamento_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Fechamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_data_fechamento_caixa.setVerifyInputWhenFocusTarget(false);

        text_usuario_fechamento_caixa.setEditable(false);
        text_usuario_fechamento_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_usuario_fechamento_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_usuario_fechamento_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fechamento Efetuado Por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_usuario_fechamento_caixa.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.name_user_end_cashier}"), text_usuario_fechamento_caixa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        text_turno_abertura_caixa.setEditable(false);
        text_turno_abertura_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_turno_abertura_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_turno_abertura_caixa.setText("1");
        text_turno_abertura_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_turno_abertura_caixa.setVerifyInputWhenFocusTarget(false);

        text_usuario_abertura_caixa.setEditable(false);
        text_usuario_abertura_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_usuario_abertura_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_usuario_abertura_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abertura Efetuada Por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_usuario_abertura_caixa.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.name_user_start_cashier}"), text_usuario_abertura_caixa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout panelOpenCaixaLayout = new javax.swing.GroupLayout(panelOpenCaixa);
        panelOpenCaixa.setLayout(panelOpenCaixaLayout);
        panelOpenCaixaLayout.setHorizontalGroup(
            panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpenCaixaLayout.createSequentialGroup()
                        .addComponent(text_usuario_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_usuario_fechamento_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_valor_inic_abert_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_turno_abertura_caixa, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                    .addGroup(panelOpenCaixaLayout.createSequentialGroup()
                        .addComponent(text_data_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_hora_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_data_fechamento_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_terminal_abertura_caixa)))
                .addContainerGap())
        );
        panelOpenCaixaLayout.setVerticalGroup(
            panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_hora_abertura_caixa)
                        .addComponent(text_data_fechamento_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(text_terminal_abertura_caixa))
                    .addComponent(text_data_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_usuario_fechamento_caixa)
                    .addComponent(text_turno_abertura_caixa)
                    .addGroup(panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_valor_inic_abert_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(text_usuario_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelCloseCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fechamento de Caixa [ Tecle (F2) para fechar o caixa ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        panelCloseCaixa.setForeground(new java.awt.Color(153, 153, 153));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Outros Valores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        text_valor_suprimento_caixa.setEditable(false);
        text_valor_suprimento_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_valor_suprimento_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suprimento de Caixa [ + ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_valor_suprimento_caixa.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.value_add_cashier}"), text_valor_suprimento_caixa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(decimalConverterReal1);
        bindingGroup.addBinding(binding);

        text_valor_sangria_caixa.setEditable(false);
        text_valor_sangria_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_valor_sangria_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retirada Caixa [ - ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_valor_sangria_caixa.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.value_removed_cashier}"), text_valor_sangria_caixa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(decimalConverterReal1);
        bindingGroup.addBinding(binding);

        text_saldo_caixa.setEditable(false);
        text_saldo_caixa.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_saldo_caixa.setForeground(new java.awt.Color(0, 153, 51));
        text_saldo_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saldo em Dinheiro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_saldo_caixa.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.value_remainder_cashier}"), text_saldo_caixa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(decimalConverterReal1);
        bindingGroup.addBinding(binding);

        jLabel_view_insercao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_view_insercao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/11379_32x32.png"))); // NOI18N
        jLabel_view_insercao.setToolTipText("Clique para detalhar");
        jLabel_view_insercao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_view_insercao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel_view_insercao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_view_insercaoMouseClicked(evt);
            }
        });

        jLabel_view_sangria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_view_sangria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/11379_32x32.png"))); // NOI18N
        jLabel_view_sangria.setToolTipText("Clique para detalhar");
        jLabel_view_sangria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_view_sangria.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel_view_sangria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_view_sangriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_saldo_caixa, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(text_valor_sangria_caixa)
                    .addComponent(text_valor_suprimento_caixa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_view_insercao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_view_sangria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_valor_suprimento_caixa)
                    .addComponent(jLabel_view_insercao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_view_sangria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text_valor_sangria_caixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(text_saldo_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        text_valor_suprimento_caixa.getAccessibleContext().setAccessibleName("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valores Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        text_valor_final_dinheiro.setEditable(false);
        text_valor_final_dinheiro.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_valor_final_dinheiro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venda Dinheiro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_valor_final_dinheiro.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.value_sales_cash}"), text_valor_final_dinheiro, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(decimalConverterReal1);
        bindingGroup.addBinding(binding);

        text_valor_final_cartao.setEditable(false);
        text_valor_final_cartao.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_valor_final_cartao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendas Cartão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_valor_final_cartao.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.value_sales_card}"), text_valor_final_cartao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(decimalConverterReal1);
        bindingGroup.addBinding(binding);

        jLabelQuantityCash.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabelQuantityCash.setForeground(new java.awt.Color(102, 102, 102));
        jLabelQuantityCash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.quantyti_sales_cash}"), jLabelQuantityCash, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabelQuantityCard.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabelQuantityCard.setForeground(new java.awt.Color(102, 102, 102));
        jLabelQuantityCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.quantyti_sales_card}"), jLabelQuantityCard, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        text_valor_final_discount_card.setEditable(false);
        text_valor_final_discount_card.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_valor_final_discount_card.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descontos Cartão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_valor_final_discount_card.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.value_discount_card}"), text_valor_final_discount_card, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(decimalConverterReal1);
        bindingGroup.addBinding(binding);

        jLabelQuantityCardDiscount.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabelQuantityCardDiscount.setForeground(new java.awt.Color(102, 102, 102));
        jLabelQuantityCardDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.quantyti_discount_card}"), jLabelQuantityCardDiscount, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        text_valor_final_discount_cash.setEditable(false);
        text_valor_final_discount_cash.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        text_valor_final_discount_cash.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descontos Dinheiro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_valor_final_discount_cash.setVerifyInputWhenFocusTarget(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.value_discount_cash}"), text_valor_final_discount_cash, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(decimalConverterReal1);
        bindingGroup.addBinding(binding);

        jLabelQuantityCashDiscount.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabelQuantityCashDiscount.setForeground(new java.awt.Color(102, 102, 102));
        jLabelQuantityCashDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cashier.quantyti_discount_cash}"), jLabelQuantityCashDiscount, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_valor_final_discount_card)
                    .addComponent(text_valor_final_dinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(text_valor_final_cartao)
                    .addComponent(text_valor_final_discount_cash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQuantityCashDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelQuantityCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelQuantityCash, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jLabelQuantityCardDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_valor_final_dinheiro)
                    .addComponent(jLabelQuantityCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_valor_final_discount_cash)
                    .addComponent(jLabelQuantityCashDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_valor_final_cartao)
                    .addComponent(jLabelQuantityCard, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_valor_final_discount_card)
                    .addComponent(jLabelQuantityCardDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCloseCaixaLayout = new javax.swing.GroupLayout(panelCloseCaixa);
        panelCloseCaixa.setLayout(panelCloseCaixaLayout);
        panelCloseCaixaLayout.setHorizontalGroup(
            panelCloseCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCloseCaixaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        panelCloseCaixaLayout.setVerticalGroup(
            panelCloseCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCloseCaixaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCloseCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[009443].png"))); // NOI18N
        jButton1.setText("Fechar Caixa");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jMenu1.setText("Arquivo");

        jMenuItemCloseCashier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemCloseCashier.setText("Fechar Caixa");
        jMenuItemCloseCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseCashierActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCloseCashier);

        jMenuItemDetailedReportCashier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDetailedReportCashier.setText("Histórico Fechamentos");
        jMenuItemDetailedReportCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDetailedReportCashierActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDetailedReportCashier);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemExit.setText("Sair");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCloseCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOpenCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOpenCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCloseCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Cashier oldCashier = cashier;
        this.cashier = ClassCashier.valuesCashier(jLabelTerminalNumber.getText());
        firePropertyChange("cashier", oldCashier, cashier);
        text_data_fechamento_caixa.setText(DateActual.setDate(new Date(), "dd/MM/yyyy"));
        text_usuario_fechamento_caixa.setText(BeanLogin.getUser());
        text_terminal_abertura_caixa.setText(jLabelTerminalNumber.getText());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        ClassCashier.clearBean();

    }//GEN-LAST:event_formWindowClosed

    private void jLabel_view_insercaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_view_insercaoMouseClicked
       
        if (!text_valor_suprimento_caixa.getText().equals("R$ 0,00")) {           
            fnFillTableMovementCashier("1", "0");
            fnShowDialogMovementCashier();
        } else {
            JOptionPane.showMessageDialog(null, "Não há inserções de suprimentos para visualizar.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jLabel_view_insercaoMouseClicked

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {

            jDialogPassword.dispose();

        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jLabel_view_sangriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_view_sangriaMouseClicked
        if (!text_valor_sangria_caixa.getText().equals("R$ 0,00")) {
            fnFillTableMovementCashier("1","1");
            fnShowDialogMovementCashier();
        } else {
            JOptionPane.showMessageDialog(null, "Não há retiradas para visualizar.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jLabel_view_sangriaMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

        if (evt.getClickCount() == 2) {

            this.jDialogMovement.dispose();

        }

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked

        if (evt.getClickCount() == 2) {

            this.jDialogPassword.dispose();

        }

    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        

    }//GEN-LAST:event_formWindowActivated

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

       

    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jMenuItemCloseCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseCashierActionPerformed
       functionCloseCashier();
    }//GEN-LAST:event_jMenuItemCloseCashierActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemDetailedReportCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDetailedReportCashierActionPerformed
        Dimension tamanhoDialogMain = getSize();
        Dimension tamanhoDialog1 = jDialogDetailedReportCashier.getPreferredSize();
        Point loc = getLocation();
        jDialogDetailedReportCashier.setLocation(
                (tamanhoDialogMain.width - tamanhoDialog1.width) / 2 + loc.x,
                (tamanhoDialogMain.height - tamanhoDialog1.height) / 2 + loc.y);
        jDialogDetailedReportCashier.setModal(true);
        jDialogDetailedReportCashier.pack();
        jDialogDetailedReportCashier.setVisible(true);
    }//GEN-LAST:event_jMenuItemDetailedReportCashierActionPerformed

    private void jTableDetailedReportCashierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableDetailedReportCashierKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {

            this.jDialogDetailedReportCashier.dispose();

        }
    }//GEN-LAST:event_jTableDetailedReportCashierKeyPressed

    private void jDialogDetailedReportCashierWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogDetailedReportCashierWindowActivated

        try {

            detailedReport = new MyModelJtableDetailedReport(false);
            jTableDetailedReportCashier.setModel(detailedReport);
            jTableDetailedReportCashier.requestFocus(true);

        } catch (Exception ex) {
            System.err.println("ERRO MODEL TABLE AVANCED SEARCH::" + ex);
            System.err.println("ERROR::" + ex);
            ////newXML.generateLog(ex.toString());
        }
    }//GEN-LAST:event_jDialogDetailedReportCashierWindowActivated

    private void jMenuItemPrintAllCouponValuesThisCashierSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrintAllCouponValuesThisCashierSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPrintAllCouponValuesThisCashierSelectedActionPerformed

    private void jDialogDetailedReportCashierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDialogDetailedReportCashierMouseReleased

    }//GEN-LAST:event_jDialogDetailedReportCashierMouseReleased

    private void jTableDetailedReportCashierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDetailedReportCashierMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenuDetailedReportCashier.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTableDetailedReportCashierMouseReleased

    private void jMenuItemExitDetailedReportCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitDetailedReportCashierActionPerformed
        this.jDialogDetailedReportCashier.dispose();
    }//GEN-LAST:event_jMenuItemExitDetailedReportCashierActionPerformed

    private void jMenuItemPrintSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrintSelectedActionPerformed
        List<String> list = new ArrayList<>();
        for (int i = 0; i < jTableDetailedReportCashier.getRowCount(); i++) {
            if (jTableDetailedReportCashier.getValueAt(i, 0).equals(true)) {
                list.add((String) jTableDetailedReportCashier.getValueAt(i, 1));
            }
        }
        if (!list.isEmpty()) {
            for (String list1 : list) {

                ClassCashier.clearBean();
                ClassCashier.valuesOldCashier(list1);
                System.err.println("Id Cashier::" + list1);
                System.err.println("Value Sales Cash::" + cashier.getValue_sales_cash());
                CriaArquivoResumoCaixa.criaArquivo(cashier, true);
                ClassCashier.clearBean();
                ClassCashier.valuesCashier(jLabelTerminalNumber.getText());
                ImpressaoJPS impressaoJPS = new ImpressaoJPS(true);

                try {

                    detailedReport = new MyModelJtableDetailedReport(false);
                    jTableDetailedReportCashier.setModel(detailedReport);
                    jTableDetailedReportCashier.requestFocus(true);

                } catch (Exception ex) {
                    System.err.println("ERROR::" + ex);
                    ////newXML.generateLog(ex.toString());
                }
            }
        } else {

            JOptionPane.showMessageDialog(null, "Selecione pelo menos um item na tabela.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemPrintSelectedActionPerformed

    private void jScrollPane2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenuDetailedReportCashier.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jScrollPane2MouseReleased

    private void jMenuItemPrintReportDetailedCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrintReportDetailedCashierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPrintReportDetailedCashierActionPerformed

    private void jDialogMovementWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogMovementWindowActivated
         //código para sair da JDialog com ESC
        Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {

            @Override
         public void eventDispatched(final AWTEvent event){
            if(event.getID() == KeyEvent.KEY_PRESSED){
                final KeyEvent evt = (KeyEvent)event;
               
                if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
                    
                    jDialogMovement.dispose();
                    
                }
            }
            
        }
        },AWTEvent.KEY_EVENT_MASK);
    }//GEN-LAST:event_jDialogMovementWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        functionCloseCashier();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println("ERROR::" + ex);
            //newXML.generateLog(ex.toString());
            java.util.logging.Logger.getLogger(JDialogCloseCashier_4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogCloseCashier_4_2 dialog = new JDialogCloseCashier_4_2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private action.DateConverter dateConverter1;
    private action.DecimalConverter decimalConverter1;
    private action.DecimalConverterReal decimalConverterReal1;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialogDetailedReportCashier;
    private javax.swing.JDialog jDialogMovement;
    private javax.swing.JDialog jDialogPassword;
    private javax.swing.JLabel jLabelQuantityCard;
    private javax.swing.JLabel jLabelQuantityCardDiscount;
    private javax.swing.JLabel jLabelQuantityCash;
    private javax.swing.JLabel jLabelQuantityCashDiscount;
    private javax.swing.JLabel jLabel_view_insercao;
    private javax.swing.JLabel jLabel_view_sangria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCloseCashier;
    private javax.swing.JMenuItem jMenuItemDetailedReportCashier;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemExitDetailedReportCashier;
    private javax.swing.JMenuItem jMenuItemPrintAllCouponValuesThisCashierSelected;
    private javax.swing.JMenuItem jMenuItemPrintReportDetailedCashier;
    private javax.swing.JMenuItem jMenuItemPrintSelected;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPopupMenu jPopupMenuDetailedReportCashier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDetailedReportCashier;
    private javax.swing.JTable jTableMovementCashier;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JPanel panelCloseCaixa;
    public static javax.swing.JPanel panelOpenCaixa;
    private javax.swing.JTextField text_data_abertura_caixa;
    private javax.swing.JTextField text_data_fechamento_caixa;
    private javax.swing.JTextField text_hora_abertura_caixa;
    private static javax.swing.JTextField text_saldo_caixa;
    private javax.swing.JTextField text_terminal_abertura_caixa;
    private javax.swing.JTextField text_turno_abertura_caixa;
    private javax.swing.JTextField text_usuario_abertura_caixa;
    private javax.swing.JTextField text_usuario_fechamento_caixa;
    private static javax.swing.JTextField text_valor_final_cartao;
    private static javax.swing.JTextField text_valor_final_dinheiro;
    private static javax.swing.JTextField text_valor_final_discount_card;
    private static javax.swing.JTextField text_valor_final_discount_cash;
    private javax.swing.JTextField text_valor_inic_abert_caixa;
    private static javax.swing.JTextField text_valor_sangria_caixa;
    private static javax.swing.JTextField text_valor_suprimento_caixa;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


    public static void activItem(javax.swing.JPanel panel, boolean isActive) {

        Component[] components = panel.getComponents();

        javax.swing.JButton jButton;
        javax.swing.JTextField jTextField;
        javax.swing.JLabel jLabel;

        for (Component component : components) {
            if (component instanceof javax.swing.JLabel) {
                jLabel = (javax.swing.JLabel) component;
                jLabel.setEnabled(isActive);
            }
            if (component instanceof javax.swing.JButton) {
                jButton = (javax.swing.JButton) component;
                jButton.setEnabled(isActive);
            }
            if (component instanceof javax.swing.JTextField) {
                jTextField = (javax.swing.JTextField) component;
                jTextField.setEnabled(isActive);
            }
        }
    }

    public static JTextField[] campos() {

        JTextField[] campo = {text_valor_sangria_caixa, text_saldo_caixa, text_valor_suprimento_caixa};

        return campo;
    }

    /**
     * @return the cashier
     */
    public Cashier getCashier() {
        return cashier;
    }

    /**
     * @param cashier the cashier to set
     */
    public void setCashier(Cashier cashier) {
        Cashier oldCashier = this.cashier;
        this.cashier = cashier;
        firePropertyChange("cashier", oldCashier, cashier);
    }

    private void functionCloseCashier() {
        
        String code_main = JTextFieldTools.enterCodeAcsses(this);
        if (ClassUser.validatorCode(code_main)) {

            new Sons().tocarFim();
            jDialogPassword.dispose();
            System.err.println("Validou!!");

            if (ClassCashier.closeCashier(BeanLogin.getUser(), jLabelTerminalNumber.getText())) {

                CriaArquivoResumoCaixa.criaArquivo(cashier, false);
               
                ImpressaoJPS impressaoJPS = new ImpressaoJPS(true);
                

                PrintCoupon op = new PrintCoupon();
                op.openDrawer();

                JOptionPane.showMessageDialog(null, "Caixa fechado com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                System.exit(0);
                jTextProductCode.setEnabled(false);
                jLabelFooterMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/footer_indisponivel.png"))); // NOI18N  
                jLabelUserNameFooter.setText("Dont Loged");
                //jLabelTurnNumber.setText("1");
                idCashier = null;
                idCashier = null;
                JDialogCloseCashier_4_2.this.dispose();

            }

            new Sons().tocarFim();
       
            System.err.println("Fechou!!");

        } else {

            JOptionPane.showMessageDialog(this, "Codigo inválido!", "UPMarket diz:", JOptionPane.ERROR_MESSAGE);
            new Sons().tocarErro();
           

        }
    }

    private void fnFillTableMovementCashier(String terminal, String type) {
        
        jtableMovementCashier = new MyModelJtableMovementCashier(terminal, type);
        jTableMovementCashier.setModel(jtableMovementCashier);
    }

    private void fnShowDialogMovementCashier() {
        
         Dimension tamanhoDialogMain = getSize();
        Dimension tamanhoDialog1 = jDialogMovement.getPreferredSize();
        Point loc = getLocation();
        jDialogMovement.setLocation(
                (tamanhoDialogMain.width - tamanhoDialog1.width) / 2 + loc.x,
                (tamanhoDialogMain.height - tamanhoDialog1.height) / 2 + loc.y);
        jDialogMovement.setModal(true);
        jDialogMovement.pack();
        jDialogMovement.setVisible(true);
    }

    private String validaURL(String string) {
        return string.replaceAll(" ", "_");
    }

    class MyCellRenderer extends DefaultTableCellRenderer {

        public MyCellRenderer() {
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused,
                int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);

            Color bg;

            if (!selected) {
                bg = ((row % 2 == 0)
                        ? alternateColor
                        : whiteColor);
            } else {
                bg = selectedColor;
            }

            if (jTableMovementCashier.getRowCount() > 0) {

                jTableMovementCashier.getColumnModel().getColumn(0).setPreferredWidth(80);
                jTableMovementCashier.getColumnModel().getColumn(1).setPreferredWidth(20);// define a largura da coluna
                jTableMovementCashier.getColumnModel().getColumn(2).setPreferredWidth(10);
                jTableMovementCashier.getColumnModel().getColumn(3).setPreferredWidth(10);
                jTableMovementCashier.getColumnModel().getColumn(4).setPreferredWidth(25);// define a largura da coluna
                jTableMovementCashier.getColumnModel().getColumn(5).setPreferredWidth(80);
            }
            if (jTableDetailedReportCashier.getRowCount() > 0) {

                jTableDetailedReportCashier.getColumnModel().getColumn(0).setPreferredWidth(5);
                jTableDetailedReportCashier.getColumnModel().getColumn(1).setPreferredWidth(70);// define a largura da coluna
                jTableDetailedReportCashier.getColumnModel().getColumn(2).setPreferredWidth(120);
                jTableDetailedReportCashier.getColumnModel().getColumn(3).setPreferredWidth(120);
                jTableDetailedReportCashier.getColumnModel().getColumn(4).setPreferredWidth(80);// define a largura da coluna
                jTableDetailedReportCashier.getColumnModel().getColumn(5).setPreferredWidth(80);
                jTableDetailedReportCashier.getColumnModel().getColumn(6).setPreferredWidth(85);
                jTableDetailedReportCashier.getColumnModel().getColumn(7).setPreferredWidth(85);// define a largura da coluna
                jTableDetailedReportCashier.getColumnModel().getColumn(8).setPreferredWidth(80);
                jTableDetailedReportCashier.getColumnModel().getColumn(9).setPreferredWidth(60);
                jTableDetailedReportCashier.getColumnModel().getColumn(10).setPreferredWidth(40);// define a largura da coluna
                jTableDetailedReportCashier.getColumnModel().getColumn(11).setPreferredWidth(40);
            }

            //jTable1.setShowHorizontalLines(true);
            jTableMovementCashier.setShowVerticalLines(true);
            setBackground(bg);
            setForeground(selected
                    ? Color.black
                    : new java.awt.Color(102, 102, 102));
            setHorizontalAlignment(SwingConstants.CENTER);

            /*
             *  if (value instanceof ImageIcon) {
             * setIcon((ImageIcon) value);
             * setText("");
             * } else
             * setIcon(null);
             */
            return this;
        }
    }
    
     private void fnOpenURL(URI uri) {
         
        if (Desktop.isDesktopSupported()) {

            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(uri);

            } catch (IOException ex) {
                System.err.println("ERROR::" + ex);
                //newXML.generateLog(ex.toString());
            }
        } else {
            System.err.println("Erro de compatibilidade.");
        }

    }
}
