/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.lang.reflect.Method;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import reports.ImprimirRelatorio_2;
import static util.ClassValidTerminal.valid_terminal;
import xml.NewXML;

/**
 *
 * @author Rafael Recalcatti
 */
public class JDialogCashierHistory_4_6 extends javax.swing.JDialog {

    private MyModelJtableClosuresCashier jtableClosuresCashier;
    private final Color whiteColor = Color.white;                 // new Color(254, 254, 254);
    private final Color alternateColor = new Color(227, 227, 227);    // Color.lightGray;//new Color(204, 204, 204);
    private final Color selectedColor = Color.yellow;
    private static final NewXML newXML = new NewXML();

    /**
     * Creates new form JDialogCashierHistory_4_5
     *
     * @param parent
     * @param modal
     */
    public JDialogCashierHistory_4_6(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTableHistoryClosuresCashier = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico de Fechamentos de Caixa");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTableHistoryClosuresCashier.setDefaultRenderer(Object.class, new MyCellRenderer());
        jTableHistoryClosuresCashier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableHistoryClosuresCashier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableHistoryClosuresCashier.setRowHeight(25);
        jTableHistoryClosuresCashier.setDefaultRenderer(Object.class, new MyCellRenderer());
        jTableHistoryClosuresCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHistoryClosuresCashierMouseClicked(evt);
            }
        });
        jTableHistoryClosuresCashier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableHistoryClosuresCashierKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(jTableHistoryClosuresCashier);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1165, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableHistoryClosuresCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHistoryClosuresCashierMouseClicked
        if (evt.getClickCount() == 2) {

            if (jTableHistoryClosuresCashier.getRowCount() > 0) {

                try {
                    Method something
                            = this.getClass().getDeclaredMethod("fnPrintReportClosureCashier", new Class[0]);

                    ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
                } catch (NoSuchMethodException | SecurityException ex) {
                    System.err.println("ERROR::" + ex);
                    //newXML.generateLog(ex.toString());
                }
            }
        }
    }//GEN-LAST:event_jTableHistoryClosuresCashierMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            jtableClosuresCashier = new MyModelJtableClosuresCashier('1');
            jTableHistoryClosuresCashier.setModel(jtableClosuresCashier);
        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
            System.err.println("ERROR::" + ex);
            ////newXML.generateLog(ex.toString());
        }
    }//GEN-LAST:event_formWindowActivated

    private void jTableHistoryClosuresCashierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableHistoryClosuresCashierKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {

            this.dispose();
        }
    }//GEN-LAST:event_jTableHistoryClosuresCashierKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println("ERROR::" + ex);
            //newXML.generateLog(ex.toString());
            java.util.logging.Logger.getLogger(JDialogCashierHistory_4_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogCashierHistory_4_6 dialog = new JDialogCashierHistory_4_6(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableHistoryClosuresCashier;
    // End of variables declaration//GEN-END:variables

    public void fnPrintReportClosureCashier() {
        String arg = (jTableHistoryClosuresCashier.getModel().getValueAt(jTableHistoryClosuresCashier.getSelectedRow(), 0)).toString();
        try {
            String arg_terminal = (valid_terminal());

            Object[] arg1 = {arg, arg_terminal};
            Object[] arg2 = {"PAR_ID", "PAR_TERMINAL"};
            new ImprimirRelatorio_2().visualizarRelatorio(arg1, arg2, "reportCashier.jasper", true);
        } catch (IOException ex) {
            System.err.println("ERROR::" + ex);
            //newXML.generateLog(ex.toString());
            Logger.getLogger(JFrameSale_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    class MyCellRenderer extends DefaultTableCellRenderer {

        public MyCellRenderer() {
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused,
                int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);

            Color bg;

            if (!selected) {
                bg = ((row % 2 == 0)
                        ? alternateColor
                        : whiteColor);
            } else {
                bg = selectedColor;
            }

            if (jTableHistoryClosuresCashier.getRowCount() > 0) {

                jTableHistoryClosuresCashier.getColumnModel().getColumn(0).setPreferredWidth(65);
                jTableHistoryClosuresCashier.getColumnModel().getColumn(1).setPreferredWidth(85);// define a largura da coluna
                jTableHistoryClosuresCashier.getColumnModel().getColumn(2).setPreferredWidth(85);
                jTableHistoryClosuresCashier.getColumnModel().getColumn(3).setPreferredWidth(100);
                jTableHistoryClosuresCashier.getColumnModel().getColumn(4).setPreferredWidth(100);// define a largura da coluna
                jTableHistoryClosuresCashier.getColumnModel().getColumn(5).setPreferredWidth(45);// define a largura da coluna
                jTableHistoryClosuresCashier.getColumnModel().getColumn(6).setPreferredWidth(40);
                jTableHistoryClosuresCashier.getColumnModel().getColumn(7).setPreferredWidth(25);
                jTableHistoryClosuresCashier.getColumnModel().getColumn(8).setPreferredWidth(80);// define a largura da coluna
                jTableHistoryClosuresCashier.getColumnModel().getColumn(9).setPreferredWidth(70);// define a largura da coluna

            }

            //jTableItens.setShowHorizontalLines(false);
            //jTableItens.setShowVerticalLines(false);
            setBackground(bg);
            setForeground(selected
                    ? Color.black
                    : new java.awt.Color(102, 102, 102));
            setHorizontalAlignment(SwingConstants.CENTER);

            /*
             *  if (value instanceof ImageIcon) {
             * setIcon((ImageIcon) value);
             * setText(""); 
             * } else
             * setIcon(null);
             */
            return this;
        }
    }
}
