/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import action.BeanLogin;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.ClassCashier;
import model.ClassCodRandon;
import model.ClassUser;
import testes.PrintCoupon;
import util.DateActual;
import util.JTextFieldTools;
import util.Sons;
import static view.JFrameSale_1.*;
import xml.NewXML;

/**
 *
 * @author Rafael Recalcatti
 */
public class JDialogOpenCashier_4_1 extends javax.swing.JDialog {

    private static final Locale BRAZIL = new Locale("pt", "BR");
    private static final DecimalFormatSymbols REAL = new DecimalFormatSymbols(BRAZIL);
    public static final DecimalFormat DINHEIRO_REAL = new DecimalFormat("¤ ###,###,##0.00", REAL);
    private static final BeanLogin beanLogin = new BeanLogin();
    private boolean isOpen = false;
    private static final PrintCoupon pc = new PrintCoupon();
    private static final NewXML newXML = new NewXML();
    private static ClassPrintCoupon cpc;

    /**
     * Mascara de dinheiro para Real Brasileiro
     */
    /**
     * Creates new form JDialogOpenCaixa
     *
     * @param parent
     * @param modal
     */
    public JDialogOpenCashier_4_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpenCaixa = new javax.swing.JPanel();
        text_turno_abertura_caixa = new javax.swing.JTextField();
        text_terminal_abertura_caixa = new javax.swing.JTextField();
        text_data_abertura_caixa = new javax.swing.JTextField();
        text_hora_abertura_caixa = new javax.swing.JTextField();
        text_valor_inic_abert_caixa = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abertura de Caixa");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelOpenCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abertura de Caixa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15), new java.awt.Color(153, 153, 153))); // NOI18N
        panelOpenCaixa.setForeground(new java.awt.Color(153, 153, 153));
        panelOpenCaixa.setToolTipText("Abertura de Caixa");

        text_turno_abertura_caixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_turno_abertura_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_turno_abertura_caixa.setText("1");
        text_turno_abertura_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turno:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_turno_abertura_caixa.setVerifyInputWhenFocusTarget(false);

        text_terminal_abertura_caixa.setEditable(false);
        text_terminal_abertura_caixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_terminal_abertura_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_terminal_abertura_caixa.setText("1");
        text_terminal_abertura_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Terminal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_terminal_abertura_caixa.setVerifyInputWhenFocusTarget(false);

        text_data_abertura_caixa.setEditable(false);
        text_data_abertura_caixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_data_abertura_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_data_abertura_caixa.setText("29/12/2014");
        text_data_abertura_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Abertura:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_data_abertura_caixa.setVerifyInputWhenFocusTarget(false);

        text_hora_abertura_caixa.setEditable(false);
        text_hora_abertura_caixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_hora_abertura_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_hora_abertura_caixa.setText("23:59");
        text_hora_abertura_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora Abertura:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_hora_abertura_caixa.setVerifyInputWhenFocusTarget(false);

        text_valor_inic_abert_caixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_valor_inic_abert_caixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_valor_inic_abert_caixa.setText("0,00");
        text_valor_inic_abert_caixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor em Caixa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        text_valor_inic_abert_caixa.setVerifyInputWhenFocusTarget(false);
        text_valor_inic_abert_caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_valor_inic_abert_caixaActionPerformed(evt);
            }
        });
        text_valor_inic_abert_caixa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_valor_inic_abert_caixaFocusGained(evt);
            }
        });
        text_valor_inic_abert_caixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_valor_inic_abert_caixaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelOpenCaixaLayout = new javax.swing.GroupLayout(panelOpenCaixa);
        panelOpenCaixa.setLayout(panelOpenCaixaLayout);
        panelOpenCaixaLayout.setHorizontalGroup(
            panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenCaixaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(text_turno_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_terminal_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_data_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_hora_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_valor_inic_abert_caixa, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        panelOpenCaixaLayout.setVerticalGroup(
            panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenCaixaLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(panelOpenCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_turno_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_data_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_hora_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_valor_inic_abert_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_terminal_abertura_caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setText("Abrir Caixa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelOpenCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(panelOpenCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(593, 158));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        panelOpenCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abertura de Caixa [ Usuario: " + BeanLogin.getUser() + " ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(153, 153, 153)));
        text_data_abertura_caixa.setText(DateActual.setDate(new Date(), "dd/MM/yyyy"));
        text_hora_abertura_caixa.setText(DateActual.setDate(new Date(), "HH:mm"));
        text_terminal_abertura_caixa.setText(jLabelTerminalNumber.getText());
        text_valor_inic_abert_caixa.requestFocus(true);

    }//GEN-LAST:event_formWindowOpened

    private void text_valor_inic_abert_caixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_valor_inic_abert_caixaKeyReleased

        JTextFieldTools.formatJTextNumber(text_valor_inic_abert_caixa);

    }//GEN-LAST:event_text_valor_inic_abert_caixaKeyReleased

    private void text_valor_inic_abert_caixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_valor_inic_abert_caixaActionPerformed
       functionOpenCashier();
    }//GEN-LAST:event_text_valor_inic_abert_caixaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.err.println("closing dialg open cashier");

        if (isOpen) {

            jTextProductCode.setEnabled(true);
            jTextProductCode.requestFocus(true);
        }


    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void text_valor_inic_abert_caixaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_valor_inic_abert_caixaFocusGained
        text_valor_inic_abert_caixa.setSelectionStart(0);
        text_valor_inic_abert_caixa.setSelectionEnd(text_valor_inic_abert_caixa.getText().length());
    }//GEN-LAST:event_text_valor_inic_abert_caixaFocusGained

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        functionOpenCashier();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        cpc = new ClassPrintCoupon();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println("ERROR::" + ex);
            //newXML.generateLog(ex.toString());
            java.util.logging.Logger.getLogger(JDialogOpenCashier_4_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogOpenCashier_4_1 dialog = new JDialogOpenCashier_4_1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JPanel panelOpenCaixa;
    private javax.swing.JTextField text_data_abertura_caixa;
    private javax.swing.JTextField text_hora_abertura_caixa;
    private javax.swing.JTextField text_terminal_abertura_caixa;
    private javax.swing.JTextField text_turno_abertura_caixa;
    private javax.swing.JTextField text_valor_inic_abert_caixa;
    // End of variables declaration//GEN-END:variables

    private void functionOpenCashier() {

        String code_main = JTextFieldTools.enterCodeAcsses(this);
        if (ClassUser.validatorCode(code_main)) {
                String codeCashier = ClassCodRandon.codeGeneratorCashier();

              
                //setando user
                if (ClassCashier.newTurn(codeCashier, BeanLogin.getUser(), Double.parseDouble(text_valor_inic_abert_caixa.getText().replace(",", ".")), Integer.parseInt(text_turno_abertura_caixa.getText()), Integer.parseInt(text_terminal_abertura_caixa.getText()))) {

                    isOpen = true;
                    //jLabelTurnNumber.setText("1");

                    jLabelFooterMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/footer_disponivel.png"))); // NOI18N  
                    jLabelUserNameFooter.setText(BeanLogin.getUser());

                    cpc.printUserCashier(3, BeanLogin.getUser(), "Abertura de Caixa", text_valor_inic_abert_caixa.getText(), codeCashier, ClassCodRandon.codeGeneratorOpenCashier(), headerCoupon);
                    pc.openDrawer();
                    pc.actionGuillotine();

                    JOptionPane.showMessageDialog(null, "Turno iniciado com sucesso \n Usúario [" + BeanLogin.getUser() + "]", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    idCashier = ClassCashier.isOpened(jLabelTerminalNumber.getText());
                    this.dispose();

                }

            } else {

                JOptionPane.showMessageDialog(this, "Codigo inválido!","UPMarket diz:",JOptionPane.ERROR_MESSAGE);
                new Sons().tocarErro();
              
            }

        
    }
}
