/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import action.AccountClient;
import action.Bean;
import action.BeanLogin;
import java.awt.Color;
import java.awt.Component;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.ClassClient;
import model.ClassSale;
import reports.ImprimirRelatorio_cupom;
import util.DateActual;
import util.Mascaras;
//import xml.NewXML;

/**
 *
 * @author Rafael Recalcatti
 */
public class JDialogAccountClient extends javax.swing.JDialog {

    private static final String currentYear = DateActual.setDate(new Date(), "YYYY");
    private AccountClient aClient = new AccountClient();

    
    
    private final Color whiteColor = Color.white;                 // new Color(254, 254, 254);
    private final Color alternateColor = new Color(227, 227, 227);    // Color.lightGray;//new Color(204, 204, 204);
    private final Color selectedColor = Color.yellow;
    //private static final NewXML newXML = new NewXML();
    private MyModelJtableAccountClient myModelJtableAccountClient;   
    private boolean isFromDialogClient;

    /**
     * Creates new form JDialogAccountClient
     *
     * @param parent
     * @param modal
     */
    public JDialogAccountClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel3 = new javax.swing.JLabel();
        buttonGroupStatusAccount = new javax.swing.ButtonGroup();
        jButtonSaveClient = new javax.swing.JButton();
        jButtonExitClient = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextNameClientAccount = new javax.swing.JTextField();
        jFormattedTextFieldClientCPFAccount = new javax.swing.JFormattedTextField(Mascaras.maskCPF());
        jFormattedTextFieldClientPhoneAccount = new javax.swing.JFormattedTextField(Mascaras.maskCel());
        jTextFieldStatusAccount = new javax.swing.JTextField();
        jTextIdAccount = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAccountClient = new javax.swing.JTable();
        jLabelReportWeek = new javax.swing.JLabel();
        jLabelReportMonth = new javax.swing.JLabel();
        jLabelReportYear = new javax.swing.JLabel();
        jComboReportYear = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboReportWeek = new javax.swing.JComboBox();
        jTextFieldAccountType = new javax.swing.JTextField();
        jFormattedTextFieldDateAccount = new javax.swing.JFormattedTextField(Mascaras.maskDate());
        jTextFieldValueAccount = new javax.swing.JTextField();
        jTextFieldIdClient = new javax.swing.JTextField();
        jRadioButtonOpened = new javax.swing.JRadioButton();
        jRadioButtonClosed = new javax.swing.JRadioButton();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010984].png"))); // NOI18N
        jLabel3.setText("Relátorio Mensal");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Contas");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonSaveClient.setText("Registrar Pagamento");
        jButtonSaveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveClientActionPerformed(evt);
            }
        });

        jButtonExitClient.setText("Sair");
        jButtonExitClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitClientActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextNameClientAccount.setEditable(false);
        jTextNameClientAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextNameClientAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome Cliente:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aClient.name_client}"), jTextNameClientAccount, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextNameClientAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameClientAccountActionPerformed(evt);
            }
        });

        jFormattedTextFieldClientCPFAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPF:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        jFormattedTextFieldClientCPFAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aClient.cpf_client}"), jFormattedTextFieldClientCPFAccount, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jFormattedTextFieldClientCPFAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldClientCPFAccountActionPerformed(evt);
            }
        });

        jFormattedTextFieldClientPhoneAccount.setEditable(false);
        jFormattedTextFieldClientPhoneAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fone:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        jFormattedTextFieldClientPhoneAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aClient.phone_client}"), jFormattedTextFieldClientPhoneAccount, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jTextFieldStatusAccount.setEditable(false);
        jTextFieldStatusAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldStatusAccount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldStatusAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Situação Conta:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aClient.status_acount}"), jTextFieldStatusAccount, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextIdAccount.setEditable(false);
        jTextIdAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextIdAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Conta:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aClient.id_account}"), jTextIdAccount, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jTableAccountClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableAccountClient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableAccountClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableAccountClient.setRowHeight(25);
        jTableAccountClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAccountClientMouseClicked(evt);
            }
        });
        jTableAccountClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableAccountClientKeyPressed(evt);
            }
        });
        jTableAccountClient.setDefaultRenderer(Object.class, new MyCellRenderer());
        jScrollPane1.setViewportView(jTableAccountClient);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        jLabelReportWeek.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelReportWeek.setForeground(new java.awt.Color(102, 102, 102));
        jLabelReportWeek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010984].png"))); // NOI18N
        jLabelReportWeek.setText("Relátorio Semanal de Contas de Clientes");
        jLabelReportWeek.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelReportWeek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelReportWeek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReportWeekMouseClicked(evt);
            }
        });

        jLabelReportMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelReportMonth.setForeground(new java.awt.Color(102, 102, 102));
        jLabelReportMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010984].png"))); // NOI18N
        jLabelReportMonth.setText("Relátorio Mensal de Contas de Clientes");
        jLabelReportMonth.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelReportMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelReportMonth.setEnabled(false);

        jLabelReportYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelReportYear.setForeground(new java.awt.Color(102, 102, 102));
        jLabelReportYear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010984].png"))); // NOI18N
        jLabelReportYear.setText("Relátorio Anual de Contas de Clientes");
        jLabelReportYear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelReportYear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelReportYear.setEnabled(false);

        jComboReportYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020 ", "2021 ", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));
        jComboReportYear.setToolTipText("");
        jComboReportYear.setSelectedItem(DateActual.setDate(new Date(), "y"));

        jLabel1.setText("Ano Referência:");

        jLabel2.setText("Semana Referência:");

        jComboReportWeek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52" }));
        jComboReportWeek.setToolTipText("");

        jTextFieldAccountType.setEditable(false);
        jTextFieldAccountType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAccountType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAccountType.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Conta:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aClient.description_account}"), jTextFieldAccountType, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jFormattedTextFieldDateAccount.setEditable(false);
        jFormattedTextFieldDateAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Conta:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        jFormattedTextFieldDateAccount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldDateAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aClient.date_account}"), jFormattedTextFieldDateAccount, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jTextFieldValueAccount.setEditable(false);
        jTextFieldValueAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldValueAccount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldValueAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor R$:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aClient.value_acount}"), jTextFieldValueAccount, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldIdClient.setEditable(false);
        jTextFieldIdClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldIdClient.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Cliente:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${aClient.idtbl_client}"), jTextFieldIdClient, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        buttonGroupStatusAccount.add(jRadioButtonOpened);
        jRadioButtonOpened.setSelected(true);
        jRadioButtonOpened.setText("ABERTA");

        buttonGroupStatusAccount.add(jRadioButtonClosed);
        jRadioButtonClosed.setText("FECHADA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldDateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldStatusAccount))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldValueAccount))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextNameClientAccount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldClientCPFAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldClientPhoneAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextIdAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIdClient, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelReportMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelReportYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelReportWeek, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonOpened)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonClosed))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboReportYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboReportWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelReportWeek)
                        .addGap(9, 9, 9)
                        .addComponent(jLabelReportMonth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelReportYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboReportYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jComboReportWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonOpened)
                            .addComponent(jRadioButtonClosed)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldClientCPFAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldClientPhoneAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIdAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNameClientAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStatusAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldDateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValueAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jComboReportWeek.setSelectedItem((DateActual.weekYear(new Date()).length()==1) ? "0"+DateActual.weekYear(new Date()): DateActual.weekYear(new Date()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSaveClient, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExitClient, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSaveClient, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExitClient, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(971, 698));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveClientActionPerformed

        if (!BeanLogin.isIsAccessRestrict()) {
            JOptionPane.showMessageDialog(this, "Usuário '"
                    + BeanLogin.getUser()
                    + "' não possui autorização para esta função.\n",
                    "Mensagem de Segurança.", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int rows = ((jTableAccountClient.getModel().getRowCount() > 0) ? jTableAccountClient.getModel().getRowCount() : 0);
            ArrayList<Object> arg = new ArrayList<>();

            if (rows > 0) {

                for (int i = 0; i < rows; i++) {

                    if (jTableAccountClient.getModel().getValueAt(i, 0).equals(true)) {

                        arg.add(jTableAccountClient.getModel().getValueAt(i, 1));

                    }

                }

                if (arg.isEmpty()) {

                    getaClient().setIdtbl_client(null);
                    JOptionPane.showMessageDialog(this, "Selecione pelo menos um item na tabela!", "Mensagem",
                            JOptionPane.INFORMATION_MESSAGE);

                } else {

                    getaClient().setIdtbl_client(null);
                    if (JOptionPane.showConfirmDialog(this, "VOCÊ CONFRMA O RECEBIMENTO DAS CONTAS SELECIONADAS?", "ALERTA!!!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {

                        if (ClassSale.registerPaymentAccountClient(arg.toString().replace("[", "(").replace("]", ")"))) {

                            JOptionPane.showMessageDialog(this, "Contas Baixadas com Sucesso", "Pagamento de Conta",
                                    JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }

            }
        }
    }//GEN-LAST:event_jButtonSaveClientActionPerformed

    private void jButtonExitClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitClientActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitClientActionPerformed

    private void jTableAccountClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAccountClientMouseClicked

        if (jTableAccountClient.getModel().getRowCount() > 0) {

            if (evt.getClickCount() == 1) {

                System.err.println("ENTROU NO IF");
                setaClient(ClassClient.consultAccountClient(jTableAccountClient.getValueAt(jTableAccountClient.getSelectedRow(), 1).toString()));

            } else if (evt.getClickCount() == 2) {

                //Abre detalhe da compra
            }
        }

    }//GEN-LAST:event_jTableAccountClientMouseClicked

    private void jTableAccountClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAccountClientKeyPressed


    }//GEN-LAST:event_jTableAccountClientKeyPressed

    private void jTextNameClientAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameClientAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameClientAccountActionPerformed

    private void jFormattedTextFieldClientCPFAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldClientCPFAccountActionPerformed

        fnSearchRegister();

    }//GEN-LAST:event_jFormattedTextFieldClientCPFAccountActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        functionFillTableAccountClient();

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
              
        
        if (Bean.getBean() != null) {

            isFromDialogClient = true;
            jLabelReportWeek.setText("Vizualizar Todas Contas");
            System.err.println("BEAN ON DIALOG ACCOUNT::"+Bean.getBean());
            jTextFieldIdClient.setText(Bean.getBean().toString());
            functionFillTableAccountClient();
        }

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Bean.setBean(null);
    }//GEN-LAST:event_formWindowClosed

    private void jLabelReportWeekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReportWeekMouseClicked
       try {
            Method something
                    = this.getClass().getDeclaredMethod("functionReport1", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !  
        } catch (NoSuchMethodException | SecurityException ex) {
            System.err.println("ERROR::" + ex);
            ////newXML.generateLog(ex.toString());
        }
    }//GEN-LAST:event_jLabelReportWeekMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAccountClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogAccountClient dialog = new JDialogAccountClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupStatusAccount;
    static javax.swing.JButton jButtonExitClient;
    private static javax.swing.JButton jButtonSaveClient;
    private javax.swing.JComboBox jComboReportWeek;
    private javax.swing.JComboBox jComboReportYear;
    public static javax.swing.JFormattedTextField jFormattedTextFieldClientCPFAccount;
    public static javax.swing.JFormattedTextField jFormattedTextFieldClientPhoneAccount;
    public static javax.swing.JFormattedTextField jFormattedTextFieldDateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelReportMonth;
    private javax.swing.JLabel jLabelReportWeek;
    private javax.swing.JLabel jLabelReportYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonClosed;
    private javax.swing.JRadioButton jRadioButtonOpened;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAccountClient;
    public static javax.swing.JTextField jTextFieldAccountType;
    public static javax.swing.JTextField jTextFieldIdClient;
    public static javax.swing.JTextField jTextFieldStatusAccount;
    public static javax.swing.JTextField jTextFieldValueAccount;
    public static javax.swing.JTextField jTextIdAccount;
    public static javax.swing.JTextField jTextNameClientAccount;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public void functionReport1() {
        try {

            String argClient = (isFromDialogClient ? "= "+jTextFieldIdClient.getText() : "!= 0");
            String status = (jRadioButtonOpened.isSelected() ? "0" : "1");
            String week = (jComboReportWeek.getSelectedItem().equals("52")? "IN(52,53)" : jComboReportWeek.getSelectedItem().equals("01") ? "IN(0,1)" : "="+jComboReportWeek.getSelectedItem().toString());
            Object[] parArg = {jComboReportYear.getSelectedItem(), week, argClient, status};
            Object[] parID = {"PAR_ANO","PAR_WEEK","PAR_CLIENT", "PAR_STATUS"};
            ImprimirRelatorio_cupom ip = new ImprimirRelatorio_cupom();
            ImprimirRelatorio_cupom ip_2 = new ImprimirRelatorio_cupom();
            ip.visualizarRelatorio(parArg, parID, "reportAccountDayOther.jasper", true);
            ip_2.visualizarRelatorio(parArg, parID, "reportAccountDayBreak.jasper", true);

        } catch (Exception ex) {
            System.err.println("ERROR::" + ex);
            ////newXML.generateLog(ex.toString());
        }
    }
    
    private void functionFillTableAccountClient() {

        if (Bean.getBean() != null) {

            getaClient().setIdtbl_client(Bean.getBean().toString());
        }
         System.err.println("BEAN ON FILL TABLE ACCOUNT::"+Bean.getBean());
        System.err.println("ID CLIENT:::" + getaClient().getIdtbl_client());
        myModelJtableAccountClient = new MyModelJtableAccountClient(Bean.getBean());
        jTableAccountClient.setModel(myModelJtableAccountClient);
    }

    private void fnSearchRegister() {

        setaClient(ClassClient.consultAccountClient(jTextIdAccount.getText()));

        if (getaClient().getIdtbl_client() == null) {

            JOptionPane.showMessageDialog(this, "Cadastro não encontrado", "Consulta de Cadastro",
                    JOptionPane.INFORMATION_MESSAGE);

            jFormattedTextFieldClientCPFAccount.setText("");
            jFormattedTextFieldClientCPFAccount.requestFocus(true);

        } else {

            setaClient(getaClient());
            functionFillTableAccountClient();
        }
    }

    /**
     * @return the aClient
     */
    public AccountClient getaClient() {
        return aClient;
    }

    /**
     * @param accountClient the aClient to set
     */
    public void setaClient(AccountClient accountClient) {
        AccountClient oldAclient = aClient;
        this.aClient = accountClient;
        firePropertyChange("aClient", oldAclient, accountClient);
        System.err.println("ENTROU NO SET");
    }

    class MyCellRenderer extends DefaultTableCellRenderer {

        public MyCellRenderer() {
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused,
                int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);

            Color bg;

            if (!selected) {
                bg = ((row % 2 == 0)
                        ? alternateColor
                        : whiteColor);
            } else {
                bg = selectedColor;
            }

            if (jTableAccountClient.getRowCount() > 0) {

                jTableAccountClient.getColumnModel().getColumn(0).setPreferredWidth(1);
                jTableAccountClient.getColumnModel().getColumn(1).setPreferredWidth(30);
                jTableAccountClient.getColumnModel().getColumn(2).setPreferredWidth(80);
                jTableAccountClient.getColumnModel().getColumn(3).setPreferredWidth(70);
                jTableAccountClient.getColumnModel().getColumn(4).setPreferredWidth(120);
                jTableAccountClient.getColumnModel().getColumn(5).setPreferredWidth(120);
                jTableAccountClient.getColumnModel().getColumn(6).setPreferredWidth(90);

            }

            //jTableItens.setShowHorizontalLines(false);
            //jTableItens.setShowVerticalLines(false);
            setBackground(bg);
            setForeground(selected
                    ? Color.black
                    : new java.awt.Color(102, 102, 102));
            setHorizontalAlignment(SwingConstants.CENTER);

            /*
             *  if (value instanceof ImageIcon) {
             * setIcon((ImageIcon) value);
             * setText("");
             * } else
             * setIcon(null);
             */
            return this;
        }
    }
    
}
