/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import action.BeanConsulta;
import action.BeanLogin;
import action.PaymentCoupon;
import action.Sale;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.ClassCard;
import model.ClassSale;
import model.ClassUser;
import static mondrian.olap.fun.vba.Vba.timer;
import reports.ImprimirRelatorio_cupom;
import util.JTextFieldTools;
import static view.JDialogCloseSale.jTextValueTotalCoupon;

/**
 *
 * @author User
 */
public class JDialogCloseSaleNew extends javax.swing.JDialog {

    private static final DecimalFormat v = new DecimalFormat("0.00");
    private String cod_tipo_pagamento = null;
    private final String codeCoupon = BeanConsulta.getCodVenda();
    private boolean fechouVenda = false;
    private static Method method = null;
    private static AudioClip somFim;
    private final DefaultListModel listModel = new DefaultListModel();
    private boolean payRegistred;
    private String last_cod_tipo_pagamento;
    private static double valor_devido = 0;
    private static final Icon icon = new ImageIcon(new ImageIcon("src/icons/flowRoot3464.png").getImage());

    /**
     * Creates new form JDialogFecharVenda2
     *
     * @param parent
     * @param modal
     */
    public JDialogCloseSaleNew(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCards = new javax.swing.JDialog();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList(ClassSale.allCards().toArray());
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonPagCartao = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton50Reais = new javax.swing.JButton();
        jButton10Reais = new javax.swing.JButton();
        jButton20Reais = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonFinalizaCalculoPagameto = new javax.swing.JButton();
        jButtonLimpaCalculoPagamento = new javax.swing.JButton();
        jButtonSairCalculoPagamento = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextValueTotalCoupon = new javax.swing.JTextField();
        jTextValueDiscontCoupon = new javax.swing.JTextField();
        jTextCash = new javax.swing.JTextField();
        jTextSmallCash = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemPaymentCardCredit = new javax.swing.JMenuItem();
        jMenuItemDiscount = new javax.swing.JMenuItem();
        jMenuIteExactCash = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();

        jDialogCards.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialogCardsWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialogCardsWindowClosed(evt);
            }
        });

        jButton10.setText("OK [Enter]");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Cancelar [Esc]");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jList1.setToolTipText("");
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jDialogCardsLayout = new javax.swing.GroupLayout(jDialogCards.getContentPane());
        jDialogCards.getContentPane().setLayout(jDialogCardsLayout);
        jDialogCardsLayout.setHorizontalGroup(
            jDialogCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCardsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jDialogCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jDialogCardsLayout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        jDialogCardsLayout.setVerticalGroup(
            jDialogCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCardsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(jDialogCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("1");
        jButton1.setName("1"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("2");
        jButton2.setName("2"); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2jButton1MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("3");
        jButton3.setName("3"); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3jButton1MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("4");
        jButton4.setName("4"); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4jButton1MouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("5");
        jButton5.setName("5"); // NOI18N
        jButton5.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5jButton1MouseClicked(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 102));
        jButton6.setText("6");
        jButton6.setName("6"); // NOI18N
        jButton6.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6jButton1MouseClicked(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 102, 102));
        jButton7.setText("7");
        jButton7.setName("7"); // NOI18N
        jButton7.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7jButton1MouseClicked(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(102, 102, 102));
        jButton8.setText("8");
        jButton8.setName("8"); // NOI18N
        jButton8.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8jButton1MouseClicked(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(102, 102, 102));
        jButton9.setText("9");
        jButton9.setName("9"); // NOI18N
        jButton9.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9jButton1MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonPagCartao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPagCartao.setForeground(new java.awt.Color(102, 102, 102));
        jButtonPagCartao.setText("Cartão ( F1 )");
        jButtonPagCartao.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonPagCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagCartaoActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(102, 102, 102));
        jButton12.setText("0");
        jButton12.setName("0"); // NOI18N
        jButton12.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12jButton1MouseClicked(evt);
            }
        });

        jButton50Reais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton50Reais.setForeground(new java.awt.Color(102, 102, 102));
        jButton50Reais.setText("50");
        jButton50Reais.setName("50.00"); // NOI18N
        jButton50Reais.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton50Reais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ReaisActionPerformed(evt);
            }
        });

        jButton10Reais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10Reais.setForeground(new java.awt.Color(102, 102, 102));
        jButton10Reais.setText("10");
        jButton10Reais.setName("10.00"); // NOI18N
        jButton10Reais.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton10Reais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ReaisActionPerformed(evt);
            }
        });

        jButton20Reais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton20Reais.setForeground(new java.awt.Color(102, 102, 102));
        jButton20Reais.setText("20");
        jButton20Reais.setName("20.00"); // NOI18N
        jButton20Reais.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton20Reais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ReaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPagCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton50Reais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10Reais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton20Reais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jButtonPagCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(jButton50Reais, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10Reais, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton20Reais, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButtonFinalizaCalculoPagameto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFinalizaCalculoPagameto.setForeground(new java.awt.Color(102, 102, 102));
        jButtonFinalizaCalculoPagameto.setText("Fim");
        jButtonFinalizaCalculoPagameto.setEnabled(false);
        jButtonFinalizaCalculoPagameto.setPreferredSize(new java.awt.Dimension(83, 18));
        jButtonFinalizaCalculoPagameto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizaCalculoPagametoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFinalizaCalculoPagameto);

        jButtonLimpaCalculoPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonLimpaCalculoPagamento.setForeground(new java.awt.Color(102, 102, 102));
        jButtonLimpaCalculoPagamento.setText("Limpa");
        jButtonLimpaCalculoPagamento.setPreferredSize(new java.awt.Dimension(83, 18));
        jButtonLimpaCalculoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaCalculoPagamentoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLimpaCalculoPagamento);

        jButtonSairCalculoPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSairCalculoPagamento.setForeground(new java.awt.Color(102, 102, 102));
        jButtonSairCalculoPagamento.setText("Sair(Esc)");
        jButtonSairCalculoPagamento.setPreferredSize(new java.awt.Dimension(83, 18));
        jButtonSairCalculoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCalculoPagamentoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSairCalculoPagamento);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jTextValueTotalCoupon.setEditable(false);
        jTextValueTotalCoupon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextValueTotalCoupon.setForeground(new java.awt.Color(102, 102, 102));
        jTextValueTotalCoupon.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextValueTotalCoupon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total R$:", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jTextValueTotalCoupon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextValueTotalCouponMouseClicked(evt);
            }
        });
        jTextValueTotalCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValueTotalCouponActionPerformed(evt);
            }
        });

        jTextValueDiscontCoupon.setEditable(false);
        jTextValueDiscontCoupon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextValueDiscontCoupon.setForeground(new java.awt.Color(102, 102, 102));
        jTextValueDiscontCoupon.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextValueDiscontCoupon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desconto R$:", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jTextValueDiscontCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValueDiscontCouponActionPerformed(evt);
            }
        });
        jTextValueDiscontCoupon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextValueDiscontCouponFocusLost(evt);
            }
        });
        jTextValueDiscontCoupon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextValueDiscontCouponKeyReleased(evt);
            }
        });

        jTextCash.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextCash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextCash.setForeground(new java.awt.Color(102, 102, 102));
        jTextCash.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextCash.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagamento R$:", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jTextCash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextCashFocusGained(evt);
            }
        });
        jTextCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCashActionPerformed(evt);
            }
        });
        jTextCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCashKeyReleased(evt);
            }
        });

        jTextSmallCash.setEditable(false);
        jTextSmallCash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextSmallCash.setForeground(new java.awt.Color(102, 102, 102));
        jTextSmallCash.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextSmallCash.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Troco R$:", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jList2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jList2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jList2.setForeground(new java.awt.Color(102, 102, 102));
        jList2.setModel(listModel);
        jList2.setAutoscrolls(false);
        jList2.setEnabled(false);
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jTextValueDiscontCoupon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextSmallCash)
                    .addComponent(jTextValueTotalCoupon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextValueTotalCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jTextValueDiscontCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCash, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextSmallCash, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(20, 20));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setForeground(new java.awt.Color(102, 102, 102));
        jMenu1.setText("Ações");

        jMenuItemPaymentCardCredit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemPaymentCardCredit.setText("Pag. Cartão");
        jMenuItemPaymentCardCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPaymentCardCreditActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPaymentCardCredit);

        jMenuItemDiscount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemDiscount.setText("Desconto");
        jMenuItemDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDiscountActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDiscount);

        jMenuIteExactCash.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jMenuIteExactCash.setText("Dinheiro Certo");
        jMenuIteExactCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIteExactCashActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIteExactCash);

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuExit.setText("Sair");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (!jList1.isSelectionEmpty()) {
            cod_tipo_pagamento = jList1.getSelectedValue().toString().substring(0, 3);
            funcaoRegistraPag(cod_tipo_pagamento);
            jDialogCards.dispose();

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jDialogCards.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        cod_tipo_pagamento = jList1.getSelectedValue().toString().substring(0, 3);
        funcaoRegistraPag(cod_tipo_pagamento);
        jDialogCards.dispose();

    }//GEN-LAST:event_jList1MouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jList1.isSelectionEmpty()) {
            cod_tipo_pagamento = jList1.getSelectedValue().toString().substring(0, 3);
            funcaoRegistraPag(cod_tipo_pagamento);
            jDialogCards.dispose();

        }

    }//GEN-LAST:event_jList1KeyPressed

    private void jDialogCardsWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogCardsWindowActivated
        jList1.setSelectedIndex(0);
        jList1.requestFocus(true);
    }//GEN-LAST:event_jDialogCardsWindowActivated

    private void jDialogCardsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogCardsWindowClosed


    }//GEN-LAST:event_jDialogCardsWindowClosed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (fechouVenda) {

            try {
                Method something
                        = this.getClass().getDeclaredMethod("functionPrintCupom", new Class[0]);

                this.loading(something); // Aqui enviamos o metodo doIt !  
            } catch (Exception e) {
                System.err.println("ERRO LOADING:::" + e);

            }

        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (!fechouVenda) {
            //BeanConsulta.setVenda_fechada(false);
            jButtonFinalizaCalculoPagameto.setEnabled(false);
            valor_devido = 0;
        } else {

            //BeanConsulta.setVenda_fechada(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        valor_devido = PaymentCoupon.getTotalCoupon();
        jTextValueTotalCoupon.setText(v.format(valor_devido));
        jTextCash.setText("0,00");
        jTextSmallCash.setText("0,00");
        jTextValueDiscontCoupon.setText("0,00");
        jTextCash.requestFocus(true);

    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemPaymentCardCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPaymentCardCreditActionPerformed
        fnPagCartao();
        if (payRegistred) {
            funcaoMostraPag();
            funcaoTotalPedido();
        }
    }//GEN-LAST:event_jMenuItemPaymentCardCreditActionPerformed

    private void jMenuItemDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDiscountActionPerformed
        fnDesconto();
    }//GEN-LAST:event_jMenuItemDiscountActionPerformed

    private void jMenuIteExactCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIteExactCashActionPerformed
        double small_cash = Double.parseDouble(jTextSmallCash.getText().replace(",", "."));
        jTextCash.setText(small_cash >= 0 ? jTextValueTotalCoupon.getText() : v.format(small_cash * -1));
        //BigDecimal calculo = calculaTroco(Double.parseDouble(valor_total.getText()), Double.parseDouble(dinheiro.getText()));
        //String res = new String();
        //res = String.valueOf(calculo);
        //troco.setText(res);
        jTextCash.requestFocus(true);
    }//GEN-LAST:event_jMenuIteExactCashActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed

        this.dispose();
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2jButton1MouseClicked

    }//GEN-LAST:event_jButton2jButton1MouseClicked

    private void jButton3jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3jButton1MouseClicked

    }//GEN-LAST:event_jButton3jButton1MouseClicked

    private void jButton4jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4jButton1MouseClicked

    }//GEN-LAST:event_jButton4jButton1MouseClicked

    private void jButton5jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5jButton1MouseClicked

    }//GEN-LAST:event_jButton5jButton1MouseClicked

    private void jButton6jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6jButton1MouseClicked

    }//GEN-LAST:event_jButton6jButton1MouseClicked

    private void jButton7jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7jButton1MouseClicked

    }//GEN-LAST:event_jButton7jButton1MouseClicked

    private void jButton8jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8jButton1MouseClicked

    }//GEN-LAST:event_jButton8jButton1MouseClicked

    private void jButton9jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9jButton1MouseClicked

    }//GEN-LAST:event_jButton9jButton1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonPagCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagCartaoActionPerformed
        fnPagCartao();
        if (payRegistred) {
            funcaoMostraPag();
            funcaoTotalPedido();
        }
    }//GEN-LAST:event_jButtonPagCartaoActionPerformed

    private void jButton12jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12jButton1MouseClicked

    }//GEN-LAST:event_jButton12jButton1MouseClicked

    private void jButton50ReaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ReaisActionPerformed

        double v1 = 50.00;
        double v2 = Double.parseDouble(jTextCash.getText().replace(",", "."));
        jTextCash.setText(v.format(v1 + v2));
        jTextCash.requestFocus(true);
    }//GEN-LAST:event_jButton50ReaisActionPerformed

    private void jButton10ReaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ReaisActionPerformed
        double v1 = 10.00;
        double v2 = Double.parseDouble(jTextCash.getText().replace(",", "."));
        jTextCash.setText(v.format(v1 + v2));
        jTextCash.requestFocus(true);
    }//GEN-LAST:event_jButton10ReaisActionPerformed

    private void jButton20ReaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ReaisActionPerformed

        double v1 = 20.00;
        double v2 = Double.parseDouble(jTextCash.getText().replace(",", "."));
        jTextCash.setText(v.format(v1 + v2));
        jTextCash.requestFocus(true);
    }//GEN-LAST:event_jButton20ReaisActionPerformed

    private void jTextCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCashActionPerformed
        //faz o calculo do troco
        if (!jTextCash.getText().equals("0,00")) {
            double cash = Double.parseDouble(jTextCash.getText().replace(",", "."));
            double valueTotalCoupon = Double.parseDouble(jTextValueTotalCoupon.getText().replace(",", "."));
            double res = cash - valueTotalCoupon;
            String value = String.valueOf(res);
            
            if(res < 0){
                jTextSmallCash.setForeground(Color.red);
            }
            else {
                jTextSmallCash.setForeground(Color.gray);
            }
             
            jTextSmallCash.setText(value);
           // funcaoRegistraPag(null);
          //  funcaoTotalPedido();
           // funcaoMostraPag();
        }
    }//GEN-LAST:event_jTextCashActionPerformed

    private void jTextCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCashKeyReleased
        //JTextFieldTools.formatJTextNumber(jTextCash);
    }//GEN-LAST:event_jTextCashKeyReleased

    private void jTextValueTotalCouponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextValueTotalCouponMouseClicked

    }//GEN-LAST:event_jTextValueTotalCouponMouseClicked

    private void jTextValueTotalCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValueTotalCouponActionPerformed
        jTextCash.setText(jTextValueTotalCoupon.getText());
        jTextCash.requestFocus(true);
    }//GEN-LAST:event_jTextValueTotalCouponActionPerformed

    private void jButtonFinalizaCalculoPagametoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizaCalculoPagametoActionPerformed
        fechouVenda = true;
        //BeanConsulta.setVenda_fechada(fechouVenda);
        this.dispose();
    }//GEN-LAST:event_jButtonFinalizaCalculoPagametoActionPerformed

    private void jButtonLimpaCalculoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaCalculoPagamentoActionPerformed
        funcaoLimpaPag();
    }//GEN-LAST:event_jButtonLimpaCalculoPagamentoActionPerformed

    private void jButtonSairCalculoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCalculoPagamentoActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairCalculoPagamentoActionPerformed

    private void jTextValueDiscontCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValueDiscontCouponActionPerformed
        jTextCash.requestFocus(true);
        jTextValueDiscontCoupon.setEditable(false);
    }//GEN-LAST:event_jTextValueDiscontCouponActionPerformed

    private void jTextValueDiscontCouponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextValueDiscontCouponFocusLost

    }//GEN-LAST:event_jTextValueDiscontCouponFocusLost

    private void jTextValueDiscontCouponKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextValueDiscontCouponKeyReleased
        JTextFieldTools.formatJTextNumber(jTextValueDiscontCoupon);
    }//GEN-LAST:event_jTextValueDiscontCouponKeyReleased

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        System.err.println(evt.getPoint());
    }//GEN-LAST:event_jPanel4MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        fechouVenda = false;
        cod_tipo_pagamento = null;
    }//GEN-LAST:event_formWindowActivated

    private void jTextCashFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCashFocusGained
        //Thread irá atualizar valor no campo troco
       
    }//GEN-LAST:event_jTextCashFocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        //
    }//GEN-LAST:event_formFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCloseSaleNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogCloseSaleNew dialog = new JDialogCloseSaleNew(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton10Reais;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20Reais;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50Reais;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonFinalizaCalculoPagameto;
    private javax.swing.JButton jButtonLimpaCalculoPagamento;
    private javax.swing.JButton jButtonPagCartao;
    private javax.swing.JButton jButtonSairCalculoPagamento;
    private javax.swing.JDialog jDialogCards;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuIteExactCash;
    private javax.swing.JMenuItem jMenuItemDiscount;
    private javax.swing.JMenuItem jMenuItemPaymentCardCredit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField jTextCash;
    public static javax.swing.JTextField jTextSmallCash;
    public static javax.swing.JTextField jTextValueDiscontCoupon;
    public static javax.swing.JTextField jTextValueTotalCoupon;
    // End of variables declaration//GEN-END:variables

   
       
    private void funcaoTotalPedido() {

        ClassSale.paymentCoupon(codeCoupon);
        BigDecimal smallCash = PaymentCoupon.getSmallCash();

        jTextValueTotalCoupon.setText(v.format(PaymentCoupon.getTotalCoupon()));

        jTextSmallCash.setText(v.format(smallCash.setScale(2, BigDecimal.ROUND_HALF_UP)));
        //jTextValueTotalDiscontCoupon.setText(v.format(PagamentoPedido.getDesconto_pagamento()));

        if (smallCash.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue() < 0) {
            valor_devido = smallCash.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();
            jTextCash.setText("0,00");
            jTextValueDiscontCoupon.setText("0,00");
            jTextCash.requestFocus(true);
        } else {

            if (last_cod_tipo_pagamento != null && smallCash.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue() > 0) {

                if (JOptionPane.showConfirmDialog(this, "Não é permitido troco para pagamento com cartão.\nDeseja emitir um contra vale?", "Mensagem", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon) == 0) {

                    JOptionPane.showMessageDialog(this, "Emitindo contra vale...");

                    fechouVenda = true;
                    //BeanConsulta.setVenda_fechada(fechouVenda);
                    this.dispose();

                } else {

                    funcaoLimpaPag();
                }
            } else {

                valor_devido = smallCash.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();
                jButtonFinalizaCalculoPagameto.setEnabled(true);
                jButtonFinalizaCalculoPagameto.requestFocus(true);

            }
        }

    }

    private void functionPrintCupom() {

        ImprimirRelatorio_cupom imp = new ImprimirRelatorio_cupom();

        try {
            String valPar = codeCoupon;
            String par = "PAR_COD_PED";

            //imp.visualizarRelatorio(valPar, par, "cupomPedido.jasper");
        } catch (Exception ex) {
            Logger.getLogger(JFrameSale_1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void invokeMethod(Method m) throws Exception {
        m.invoke(this, new Object[0]); // perceba que eu passo this !  
    }

    public void loading(Method m) throws Exception {
        method = m;
        final Thread t1 = new Thread(new Runnable() {//cria uma thread pra gravar o seu arquivo

            @Override
            public void run() {

                try {
                    //AQUI VAI A FUNCÃO A SER EXECUTADA

                    invokeMethod(method);

                } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
                    Logger.getLogger(JFrameSale_1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(JFrameSale_1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
        new Thread(new Runnable() {//cria outra thread pra sua tela de espera

            @Override
            public void run() {
                //cria a tela de espera e mostra ela
                JDialogLoading jd = new JDialogLoading(null, false);
                jd.setVisible(true);

                try {
                    t1.join();//fica esperando a primeira thread acabar
                } catch (InterruptedException ex) {
                    Logger.getLogger(JFrameSale_1.class.getName()).log(Level.SEVERE, null, ex);
                }
                // quando acabar fecha a janela de espera, podes fazer outras coisas aqui
                jd.dispose();

            }
        }).start();

    }

    private void funcaoMostraPag() {

        // if (Double.parseDouble(jTextSmallCash.getText().replace(",", ".")) > 0) {
        List<String> listPag = ClassSale.searchPaymentCoupon(codeCoupon);

        ((DefaultListModel) (jList2.getModel()))
                .removeAllElements();

        for (String listPag1 : listPag) {
            ((DefaultListModel) (jList2.getModel())).addElement(listPag1);
        }

    }

    private boolean funcaoRegistraPag(String tipo_pag) {

        last_cod_tipo_pagamento = cod_tipo_pagamento;
        cod_tipo_pagamento = null;
        System.err.println("COD> PAG::" + tipo_pag);
        System.err.println("TIPO PAG::" + (tipo_pag == null ? "DINHEIRO" : "CARTÃO"));
        System.err.println("ULTIMO TIPO PAG::" + (last_cod_tipo_pagamento == null ? "DINHEIRO" : "CARTÃO"));
        double valorPag = Double.parseDouble(jTextCash.getText().replace(",", "."));
        double descontoPag = Double.parseDouble(jTextValueDiscontCoupon.getText().replace(",", "."));

        //payRegistred = ClassPedido.registra_pagamento_pedido(codeCoupon, tipo_pag, valor_devido, valorPag, descontoPag);
        System.out.println("REGISTROU PAG?" + (payRegistred ? "SIM" : "NÃO"));

        return payRegistred;
    }

    private void fnDesconto() {

        if (BeanLogin.isIsCashierAccess()) {

            jTextValueDiscontCoupon.setText(JTextFieldTools.enterValue(this));
            jTextCash.requestFocus(true);

        } else {

            String codigo = JTextFieldTools.enterCodeAcsses(this);
            if (ClassUser.validatorCode(codigo)) {

                jTextValueDiscontCoupon.setText(JTextFieldTools.enterValue(this));
                jTextCash.requestFocus(true);

            } else {
                JOptionPane.showMessageDialog(this, "Código incorreto!", "Mensagem", JOptionPane.INFORMATION_MESSAGE, icon);

            }

        }

    }

    private void fnPagCartao() {

        if (!jTextCash.getText().equals("0,00")) {

            Dimension tamanhoDialogMain = getSize();
            Dimension tamanhoDialog1 = jDialogCards.getPreferredSize();
            Point loc = getLocation();
            jDialogCards.setLocation(
                    (tamanhoDialogMain.width - tamanhoDialog1.width) / 2 + loc.x,
                    (tamanhoDialogMain.height - tamanhoDialog1.height) / 2 + loc.y);
            jDialogCards.setModal(true);
            jDialogCards.pack();
            jDialogCards.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(this, "Insira o valor do pagamento.", "Mensagem", JOptionPane.INFORMATION_MESSAGE, icon);

        }

    }

    private void funcaoLimpaPag() {

        ((DefaultListModel) (jList2.getModel()))
                .removeAllElements();
        ClassSale.clearTypePayment(codeCoupon);

        valor_devido = PaymentCoupon.getTotalCoupon();
        payRegistred = false;
        jTextValueTotalCoupon.setText(v.format(Sale.getPriceTotal()).replace(".", ","));
        jTextCash.setText("0,00");
        jTextSmallCash.setText("0,00");
        jTextValueDiscontCoupon.setText("0,00");
        jTextCash.requestFocus(true);
    }
}
