/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import action.BeanDetailSale;
import java.awt.AWTEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.AWTEventListener;
import java.awt.event.KeyEvent;
import java.lang.reflect.Method;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.ClassSale;
import reports.ImprimirRelatorio_2;
import xml.NewXML;

/**
 *
 * @author User
 */
public class JDialogAllSales extends javax.swing.JDialog {

    private final Color whiteColor = Color.white;                 // new Color(254, 254, 254);
    private final Color alternateColor = new Color(227, 227, 227);    // Color.lightGray;//new Color(204, 204, 204);
    private final Color selectedColor = Color.yellow;
    private static final NewXML newXML = new NewXML();
    private static final List<String> str_status = new ArrayList<>();
    private static MyModelJTableChekedSales myModelJTableChekedSales;
    private static String sql = "";
    private static boolean selected = false;
    private static final List<String> allCodCoupons = new ArrayList<>();
    private static String codeSale;
    private static final DecimalFormat v = new DecimalFormat("0.00");
    private static MyModelJtableDetaialSale myModelJtableDetaialSale;
    private static final DateFormat dateFormat_sql = new SimpleDateFormat("YYYY/MM/dd");
    private static final DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    private static String startDate;
    private static String endDate;
    private static int algin = 0;
    private static boolean isExclused = false;

    /**
     * Creates new form JDialogAllSales
     * @param parent
     * @param modal
     */
    public JDialogAllSales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDetailSale = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelValue = new javax.swing.JLabel();
        jLabelValue1 = new javax.swing.JLabel();
        jLabelValue2 = new javax.swing.JLabel();
        jLabelValue3 = new javax.swing.JLabel();
        jLabelValue4 = new javax.swing.JLabel();
        jLabelValue5 = new javax.swing.JLabel();
        jLabelValue6 = new javax.swing.JLabel();
        jButtonPrintDetailSale = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelValue7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductsDetailSales = new javax.swing.JTable();
        buttonGroupAlgin = new javax.swing.ButtonGroup();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableAllSales = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jCheckBoxAllSales = new javax.swing.JCheckBox();
        jCheckBoxCanceledSales = new javax.swing.JCheckBox();
        jCheckBoxClosedSales = new javax.swing.JCheckBox();
        jButtonBuscarVendas = new javax.swing.JButton();
        jCheckBoxOnDiscount = new javax.swing.JCheckBox();
        jDateChooserStart = new com.toedter.calendar.JDateChooser();
        jDateChooserEnd = new com.toedter.calendar.JDateChooser();
        bt_excluir_product = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bt_sair1 = new javax.swing.JButton();
        bt_excluir_product1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jRadioButtonMenuItemAlignLeft = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemAlignCenter = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemAlignRight = new javax.swing.JRadioButtonMenuItem();

        jDialogDetailSale.setTitle("Detalhes da Venda");
        jDialogDetailSale.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialogDetailSaleWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cód. Cupom:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data/Hora:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Terminal:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Desconto Cupom R$:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total Cupom R$:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cancelado:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fechado:");

        jLabelValue.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelValue.setText("valor");

        jLabelValue1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelValue1.setText("valor");

        jLabelValue2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelValue2.setText("valor");

        jLabelValue3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelValue3.setText("valor");

        jLabelValue4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelValue4.setText("valor");

        jLabelValue5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelValue5.setText("valor");

        jLabelValue6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelValue6.setText("valor");

        jButtonPrintDetailSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer-without-paper_32x32.png"))); // NOI18N
        jButtonPrintDetailSale.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Usúario:");

        jLabelValue7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelValue7.setText("valor");

        jTableProductsDetailSales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableProductsDetailSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProductsDetailSales.setDefaultRenderer(Object.class, new MyCellRenderer());
        jTableProductsDetailSales.setRowHeight(20);
        jTableProductsDetailSales.setRowSelectionAllowed(false);
        jTableProductsDetailSales.setShowHorizontalLines(false);
        jTableProductsDetailSales.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableProductsDetailSales);

        javax.swing.GroupLayout jDialogDetailSaleLayout = new javax.swing.GroupLayout(jDialogDetailSale.getContentPane());
        jDialogDetailSale.getContentPane().setLayout(jDialogDetailSaleLayout);
        jDialogDetailSaleLayout.setHorizontalGroup(
            jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDetailSaleLayout.createSequentialGroup()
                .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogDetailSaleLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValue2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabelValue7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelValue6, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jLabelValue5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelValue4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelValue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDialogDetailSaleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDialogDetailSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPrintDetailSale, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogDetailSaleLayout.setVerticalGroup(
            jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDetailSaleLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelValue)
                    .addComponent(jLabelValue1))
                .addGap(18, 18, 18)
                .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelValue4)
                    .addComponent(jLabel3)
                    .addComponent(jLabelValue2))
                .addGap(18, 18, 18)
                .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogDetailSaleLayout.createSequentialGroup()
                        .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelValue5))
                        .addGap(18, 18, 18)
                        .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelValue6)))
                    .addGroup(jDialogDetailSaleLayout.createSequentialGroup()
                        .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabelValue3))
                        .addGap(18, 18, 18)
                        .addGroup(jDialogDetailSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabelValue7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButtonPrintDetailSale, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busca Avançada de Vendas");
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado da Pesquisa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel10.setLayout(new java.awt.BorderLayout());

        jTableAllSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableAllSales.setRowHeight(20);
        jTableAllSales.setDefaultRenderer(Object.class, new MyCellRenderer());
        jTableAllSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAllSalesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableAllSales);

        jPanel10.add(jScrollPane6, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        jCheckBoxAllSales.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jCheckBoxAllSales.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBoxAllSales.setText("Todos");
        jCheckBoxAllSales.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxAllSalesItemStateChanged(evt);
            }
        });

        jCheckBoxCanceledSales.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jCheckBoxCanceledSales.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBoxCanceledSales.setText("Cancelado");
        jCheckBoxCanceledSales.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxCanceledSalesItemStateChanged(evt);
            }
        });

        jCheckBoxClosedSales.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jCheckBoxClosedSales.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBoxClosedSales.setText("Fechado");
        jCheckBoxClosedSales.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxClosedSalesItemStateChanged(evt);
            }
        });

        jButtonBuscarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/11379_32x32.png"))); // NOI18N
        jButtonBuscarVendas.setText("Buscar  ");
        jButtonBuscarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarVendasActionPerformed(evt);
            }
        });

        jCheckBoxOnDiscount.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jCheckBoxOnDiscount.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBoxOnDiscount.setText("Com Desconto");
        jCheckBoxOnDiscount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxOnDiscountItemStateChanged(evt);
            }
        });

        jDateChooserStart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Inicio:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        jDateChooserStart.setDate(new Date());

        jDateChooserEnd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Fim:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        jDateChooserEnd.setDate(new Date());

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDateChooserStart, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooserEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jCheckBoxCanceledSales, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAllSales, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxClosedSales, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxOnDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCheckBoxCanceledSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxAllSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxClosedSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxOnDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBuscarVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jDateChooserStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        bt_excluir_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TrashFull.png"))); // NOI18N
        bt_excluir_product.setText("Excluir Selecionado (Del)");
        bt_excluir_product.setToolTipText("Excluir Selecionado(s)");
        bt_excluir_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_productActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010681].png"))); // NOI18N
        jButton2.setText("Imprimir Selecionados (Ctrl +P)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bt_sair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[000787].png"))); // NOI18N
        bt_sair1.setText("Sair (Esc)");
        bt_sair1.setToolTipText("Sair");
        bt_sair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sair1ActionPerformed(evt);
            }
        });

        bt_excluir_product1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010987] - Cópia.png"))); // NOI18N
        bt_excluir_product1.setText("Selecionat Todos (Ctrl+T)");
        bt_excluir_product1.setToolTipText("Excluir cadastro");
        bt_excluir_product1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_product1ActionPerformed(evt);
            }
        });

        jMenu3.setText("Arquivo");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItem3.setText("Apagar Vendas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Selecionar Todos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Imprimir Selecionados");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        jMenuEdit.setText("Editar");

        buttonGroupAlgin.add(jRadioButtonMenuItemAlignLeft);
        jRadioButtonMenuItemAlignLeft.setText("Alinhar à Esquerda");
        jRadioButtonMenuItemAlignLeft.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonMenuItemAlignLeftItemStateChanged(evt);
            }
        });
        jMenuEdit.add(jRadioButtonMenuItemAlignLeft);

        buttonGroupAlgin.add(jRadioButtonMenuItemAlignCenter);
        jRadioButtonMenuItemAlignCenter.setSelected(true);
        jRadioButtonMenuItemAlignCenter.setText("Alinhar  Justificado");
        jRadioButtonMenuItemAlignCenter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonMenuItemAlignCenterItemStateChanged(evt);
            }
        });
        jMenuEdit.add(jRadioButtonMenuItemAlignCenter);

        buttonGroupAlgin.add(jRadioButtonMenuItemAlignRight);
        jRadioButtonMenuItemAlignRight.setText("Alinhar à Direita");
        jRadioButtonMenuItemAlignRight.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonMenuItemAlignRightItemStateChanged(evt);
            }
        });
        jMenuEdit.add(jRadioButtonMenuItemAlignRight);

        jMenuBar2.add(jMenuEdit);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_excluir_product, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluir_product1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_sair1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_sair1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_excluir_product, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_excluir_product1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        functionDeleteSale();
        allCodCoupons.clear();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        functionSelectAll();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        functionPrintSelected();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTableAllSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAllSalesMouseClicked
        if (evt.getClickCount() == 2) {

            if (jTableAllSales.getModel().getRowCount() > 0) {
                codeSale = jTableAllSales.getModel().getValueAt(jTableAllSales.getSelectedRow(), 1).toString();
                Dimension tamanhoDialogMain = getSize();
                Dimension tamanhoDialog1 = jDialogDetailSale.getPreferredSize();
                Point loc = getLocation();
                jDialogDetailSale.setLocation(
                        (tamanhoDialogMain.width - tamanhoDialog1.width) / 2 + loc.x,
                        (tamanhoDialogMain.height - tamanhoDialog1.height) / 2 + loc.y);
                jDialogDetailSale.setModal(true);
                jDialogDetailSale.pack();
                jDialogDetailSale.setVisible(true);

            }
        }
    }//GEN-LAST:event_jTableAllSalesMouseClicked

    private void jCheckBoxAllSalesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxAllSalesItemStateChanged
        jCheckBoxCanceledSales.setSelected(false);
        jCheckBoxClosedSales.setSelected(false);
        jCheckBoxOnDiscount.setSelected(false);
        str_status.clear();
        System.err.println(str_status);
    }//GEN-LAST:event_jCheckBoxAllSalesItemStateChanged

    private void jCheckBoxCanceledSalesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxCanceledSalesItemStateChanged
        if (jCheckBoxCanceledSales.isSelected()) {
            str_status.add(" AND isCanceled = 1");
            str_status.remove(" AND isCanceled = 0");
        } else {
            str_status.add(" AND isCanceled = 0");
            str_status.remove(" AND isCanceled = 1");
        }
        System.err.println(str_status);
        jCheckBoxAllSales.setSelected(false);
    }//GEN-LAST:event_jCheckBoxCanceledSalesItemStateChanged

    private void jCheckBoxClosedSalesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxClosedSalesItemStateChanged
        if (jCheckBoxClosedSales.isSelected()) {
            str_status.add(" AND isClosed = 1");
            str_status.remove(" AND isClosed = 0");
        } else {

            str_status.add(" AND isClosed = 0");
            str_status.remove(" AND isClosed = 1");
        }
        System.err.println(str_status);
        jCheckBoxAllSales.setSelected(false);
    }//GEN-LAST:event_jCheckBoxClosedSalesItemStateChanged

    private void jButtonBuscarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarVendasActionPerformed

        try {
            Method something
                    = this.getClass().getDeclaredMethod("fnSearch", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR COMPLETE TABLE LINE 1136::" + ex);

        }

    }//GEN-LAST:event_jButtonBuscarVendasActionPerformed

    private void jCheckBoxOnDiscountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxOnDiscountItemStateChanged
        if (jCheckBoxOnDiscount.isSelected()) {
            str_status.add(" AND t.`discount_coupon` > 0");
            str_status.remove(" AND t.`discount_coupon` = 0");
        } else {

            str_status.add(" AND t.`discount_coupon` = 0");
            str_status.remove(" AND t.`discount_coupon` > 0");
        }
        System.err.println(str_status);
        jCheckBoxAllSales.setSelected(false);
    }//GEN-LAST:event_jCheckBoxOnDiscountItemStateChanged

    private void bt_excluir_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_productActionPerformed
     
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente apagar estas vendas?\nEsta ação não podera ser retornada.", "Alerta!", JOptionPane.YES_NO_OPTION) == 0) {
            
            try {
                Method something
                        = this.getClass().getDeclaredMethod("functionDeleteSale", new Class[0]);

                ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
           
                Thread.sleep(1000);                     
            
            } catch (NoSuchMethodException | SecurityException | InterruptedException ex) {
                //newXML.generateLog(ex.toString());
                System.err.println("ERROR SELECT ALL::" + ex);

            }
            
            allCodCoupons.clear();
          
            if (isExclused) {
                JOptionPane.showMessageDialog(this, "Cupons apagados com sucesso.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao apagar cupom.", "Mensagem", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_bt_excluir_productActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        functionPrintSelected();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bt_sair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sair1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_sair1ActionPerformed

    private void bt_excluir_product1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_product1ActionPerformed

        try {
            Method something
                    = this.getClass().getDeclaredMethod("functionSelectAll", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR SELECT ALL::" + ex);

        }

    }//GEN-LAST:event_bt_excluir_product1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jDialogDetailSaleWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogDetailSaleWindowActivated
        functionSearchSale(codeSale);
        //código para sair da JDialog com ESC
        Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {

            @Override
            public void eventDispatched(final AWTEvent event) {
                if (event.getID() == KeyEvent.KEY_PRESSED) {
                    final KeyEvent evt = (KeyEvent) event;

                    if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {

                        jDialogDetailSale.dispose();

                    }
                }

            }
        }, AWTEvent.KEY_EVENT_MASK);
    }//GEN-LAST:event_jDialogDetailSaleWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jRadioButtonMenuItemAlignLeftItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemAlignLeftItemStateChanged

        algin = -1;
        try {
            Method something
                    = this.getClass().getDeclaredMethod("fnSearch", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR COMPLETE TABLE LINE 1136::" + ex);

        }
    }//GEN-LAST:event_jRadioButtonMenuItemAlignLeftItemStateChanged

    private void jRadioButtonMenuItemAlignCenterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemAlignCenterItemStateChanged

        algin = 0;
        try {
            Method something
                    = this.getClass().getDeclaredMethod("fnSearch", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR COMPLETE TABLE LINE 1136::" + ex);

        }
    }//GEN-LAST:event_jRadioButtonMenuItemAlignCenterItemStateChanged

    private void jRadioButtonMenuItemAlignRightItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemAlignRightItemStateChanged

        algin = 1;
        try {
            Method something
                    = this.getClass().getDeclaredMethod("fnSearch", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
        } catch (NoSuchMethodException | SecurityException ex) {
            //newXML.generateLog(ex.toString());
            System.err.println("ERROR COMPLETE TABLE LINE 1136::" + ex);

        }
    }//GEN-LAST:event_jRadioButtonMenuItemAlignRightItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAllSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogAllSales dialog = new JDialogAllSales(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_excluir_product;
    private javax.swing.JButton bt_excluir_product1;
    private javax.swing.JButton bt_sair1;
    private javax.swing.ButtonGroup buttonGroupAlgin;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscarVendas;
    private javax.swing.JButton jButtonPrintDetailSale;
    private javax.swing.JCheckBox jCheckBoxAllSales;
    private javax.swing.JCheckBox jCheckBoxCanceledSales;
    private javax.swing.JCheckBox jCheckBoxClosedSales;
    private javax.swing.JCheckBox jCheckBoxOnDiscount;
    private com.toedter.calendar.JDateChooser jDateChooserEnd;
    private com.toedter.calendar.JDateChooser jDateChooserStart;
    private javax.swing.JDialog jDialogDetailSale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelValue;
    private javax.swing.JLabel jLabelValue1;
    private javax.swing.JLabel jLabelValue2;
    private javax.swing.JLabel jLabelValue3;
    private javax.swing.JLabel jLabelValue4;
    private javax.swing.JLabel jLabelValue5;
    private javax.swing.JLabel jLabelValue6;
    private javax.swing.JLabel jLabelValue7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAlignCenter;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAlignLeft;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAlignRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableAllSales;
    private javax.swing.JTable jTableProductsDetailSales;
    // End of variables declaration//GEN-END:variables

    public void fnPrintAllSales() {

        String arg = allCodCoupons.toString().replace("[", " idtbl_coupon IN(").replace("]", ") ");
        ImprimirRelatorio_2 imprimirRelatorio_2 = new ImprimirRelatorio_2();
        Object[] par = {"PAR_ALL_COD", "PAR_ARG"};
        Object[] valuePar = {arg, "Vendas realizadas entre " + dateFormat.format(jDateChooserStart.getCalendar().getTime()) + " e " + dateFormat.format(jDateChooserEnd.getCalendar().getTime())};
        imprimirRelatorio_2.visualizarRelatorio(valuePar, par, "reportAllSales.jasper", true);

    }

    public void functionSearchSale(String arg) {

        BeanDetailSale detailSale = ClassSale.detaialSale(arg);

        jLabelValue.setText(detailSale.getCodeSale());
        jLabelValue1.setText(detailSale.getDateHourSale());
        jLabelValue2.setText(String.valueOf(detailSale.getTerminal()));
        jLabelValue3.setText((detailSale.isIsCanceled() ? "SIM" : "NÃO"));
        jLabelValue4.setText((detailSale.isIsClosed() ? "SIM" : "NÃO"));
        jLabelValue5.setText(v.format(detailSale.getDiscount()));
        jLabelValue6.setText(v.format(detailSale.getTotal()));
        jLabelValue7.setText(detailSale.getUser());

        try {

            myModelJtableDetaialSale = new MyModelJtableDetaialSale(arg);
            jTableProductsDetailSales.setModel(myModelJtableDetaialSale);

        } catch (Exception ex) {
            System.err.println("ERROR MODEL TABLE AVANCED SEARCH::" + ex);
            ////newXML.generateLog(ex.toString());
            System.err.println("ERROR::" + ex);

        }

    }

    public void functionDeleteSale() {
         
        if (jTableAllSales.getModel().getRowCount() > 0) {

            for (int i = 0; i < jTableAllSales.getModel().getRowCount(); i++) {

                if (jTableAllSales.getModel().getValueAt(i, 0).equals(true)) {
                    if (!allCodCoupons.contains(jTableAllSales.getModel().getValueAt(i, 1).toString())) {
                        allCodCoupons.add("'" + jTableAllSales.getModel().getValueAt(i, 1).toString() + "'");
                    }
                }
            }
            String arg = allCodCoupons.toString().replace("[", "(").replace("]", ");");
            String sql_delete = "DELETE FROM tbl_coupon WHERE idtbl_coupon IN" + arg;
            System.err.println("SQL delete:::" + sql_delete);
            isExclused = ClassSale.deleteSale(sql_delete);               
            
        }

        try {

            myModelJTableChekedSales = new MyModelJTableChekedSales(false, sql);
            jTableAllSales.setModel(myModelJTableChekedSales);

        } catch (Exception ex) {
            
            System.err.println("ERROR MODEL TABLE AVANCED SEARCH::" + ex);
            ////newXML.generateLog(ex.toString());
            System.err.println("ERROR::" + ex);

        }

        functionSetReturnSearch(false);
     
    }

    public void functionSelectAll() {

        if (jTableAllSales.getModel().getRowCount() > 0) {
            try {

                selected = !selected;
                myModelJTableChekedSales = new MyModelJTableChekedSales(selected, sql);
                jTableAllSales.setModel(myModelJTableChekedSales);
                allCodCoupons.clear();

            } catch (Exception ex) {
                System.err.println("ERROR MODEL TABLE AVANCED SEARCH::" + ex);
                ////newXML.generateLog(ex.toString());
                System.err.println("ERROR::" + ex);

            }
        }
    }

    public void functionPrintSelected() {

        if (jTableAllSales.getModel().getRowCount() > 0) {

            for (int i = 0; i < jTableAllSales.getModel().getRowCount(); i++) {

                if (jTableAllSales.getModel().getValueAt(i, 0).equals(true)) {
                    if (!allCodCoupons.contains(jTableAllSales.getModel().getValueAt(i, 1).toString())) {
                        allCodCoupons.add("'" + jTableAllSales.getModel().getValueAt(i, 1).toString() + "'");
                    }
                }
            }
        }

        if (allCodCoupons.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione pelo menos um item na tabela.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Method something = this.getClass().getDeclaredMethod("fnPrintAllSales", new Class[0]);

                ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !
            } catch (NoSuchMethodException | SecurityException ex) {
                //newXML.generateLog(ex.toString());
                System.err.println("ERROR::" + ex);

            }
        }
    }

    private void functionSetReturnSearch(boolean isSearching) {

        int rows = ((jTableAllSales.getModel().getRowCount() >= 0) ? jTableAllSales.getModel().getRowCount() : 0);
        if (rows == 0) {
            jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado da Pesquisa: 0 cupons encontrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N
            if(isSearching)JOptionPane.showMessageDialog(this, "A pesquisa não retornou resultados. Tente novamento com outros paramêtros.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } else if (rows > 0) {
            jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado da Pesquisa: " + rows + " cupons encontrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 2, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        }
    }

    public void fnSearch() {

        String std = "";
        if (!str_status.isEmpty()) {
            std = str_status.toString().replace("[", "").replace("]", "").replace(",", "");
            System.err.println("\n>>>>>>>" + std);
        }

        startDate = dateFormat_sql.format(jDateChooserStart.getCalendar().getTime());
        endDate = dateFormat_sql.format(jDateChooserEnd.getCalendar().getTime());

        sql = "SELECT t.`idtbl_coupon`, DATE_FORMAT(t.`date_hour_coupon`,'%d/%m/%Y') AS date_coupon, TIME_FORMAT(t.`date_hour_coupon`,'%H:%i') AS hour_coupon, CASE t.`isCanceled` WHEN '1' THEN 'SIM' ELSE 'NÂO' END AS isCanceled, CASE t.`isClosed` WHEN '1' THEN 'SIM' ELSE 'NÂO' END AS isClosed, t.`total_coupon`, t.`discount_coupon`, t.`idtbl_user` FROM tbl_coupon t WHERE (t.`date_hour_coupon` BETWEEN '" + startDate + "' AND '" + endDate + "') OR ('" + endDate + "' BETWEEN '" + startDate + "' AND t.`date_hour_coupon`)" + std + " ORDER BY t.`date_hour_coupon` DESC;";
        System.err.println("SQL::::" + sql);
        try {

            myModelJTableChekedSales = new MyModelJTableChekedSales(false, sql);
            jTableAllSales.setModel(myModelJTableChekedSales);

        } catch (Exception ex) {
            System.err.println("ERROR MODEL TABLE AVANCED SEARCH::" + ex);
            ////newXML.generateLog(ex.toString());
            System.err.println("ERROR::" + ex);

        }
        if (jTableAllSales.getRowCount() > 0) {

            functionSetReturnSearch(true);

        }
    }

    class MyCellRenderer extends DefaultTableCellRenderer {

        public MyCellRenderer() {
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused,
                int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);

            Color bg;

            if (!selected) {
                bg = ((row % 2 == 0)
                        ? alternateColor
                        : whiteColor);
            } else {
                bg = selectedColor;
            }

            if (jTableAllSales.getRowCount() > 0) {

                jTableAllSales.getColumnModel().getColumn(0).setPreferredWidth(2);
                jTableAllSales.getColumnModel().getColumn(1).setPreferredWidth(120);// define a largura da coluna
                jTableAllSales.getColumnModel().getColumn(2).setPreferredWidth(80);
                jTableAllSales.getColumnModel().getColumn(3).setPreferredWidth(80);
                jTableAllSales.getColumnModel().getColumn(4).setPreferredWidth(80);// define a largura da coluna
                jTableAllSales.getColumnModel().getColumn(5).setPreferredWidth(80);// define a largura da coluna
                jTableAllSales.getColumnModel().getColumn(6).setPreferredWidth(80);// define a largura da coluna
                jTableAllSales.getColumnModel().getColumn(7).setPreferredWidth(80);// define a largura da coluna
           
            
            switch (algin) {

                case -1:
                    setHorizontalAlignment(SwingConstants.LEFT);
                    break;
                case 0:
                    setHorizontalAlignment(SwingConstants.CENTER);
                    break;
                case 1:
                    setHorizontalAlignment(SwingConstants.RIGHT);
                    break;

            }
            
                
            }
            if (jTableProductsDetailSales.getRowCount() > 0) {

                jTableProductsDetailSales.getColumnModel().getColumn(0).setPreferredWidth(28);
                jTableProductsDetailSales.getColumnModel().getColumn(1).setPreferredWidth(70);// define a largura da coluna
                jTableProductsDetailSales.getColumnModel().getColumn(2).setPreferredWidth(150);
                jTableProductsDetailSales.getColumnModel().getColumn(3).setPreferredWidth(60);
                jTableProductsDetailSales.getColumnModel().getColumn(4).setPreferredWidth(60);// define a largura da coluna
                jTableProductsDetailSales.getColumnModel().getColumn(5).setPreferredWidth(70);// define a largura da coluna
                jTableProductsDetailSales.getColumnModel().getColumn(6).setPreferredWidth(75);// define a largura da coluna
            
          }
            //jTableItens.setShowHorizontalLines(false);
            //jTableItens.setShowVerticalLines(false);

            setBackground(bg);
            setForeground(selected
                    ? Color.black
                    : new java.awt.Color(102, 102, 102));
            
            setVerticalAlignment(SwingConstants.CENTER);
            ((DefaultTableCellRenderer) jTableProductsDetailSales.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
            ((DefaultTableCellRenderer) jTableAllSales.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

            /*
             *  if (value instanceof ImageIcon) {
             * setIcon((ImageIcon) value);
             * setText(""); 
             * } else
             * setIcon(null);
             */
            return this;
        }
    }
}
