/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 07/10/2009, 21:12:59
 */
package view;

import action.Bean;
import action.BeanCodeSale;
import action.BeanLogin;
import action.Client;
import action.Sale;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.ClassClient;
import static model.ClassRefreshLots.refreshLot;
import static model.ClassRefreshLots.setLaunch;
import model.ClassSale;
import model.ClassUser;
import model.Conn;
import reports.ImprimirRelatorio_cupom;
import util.JTextFieldTools;
import util.NumberInFull;
import static view.JFrameSale_1.*;
//import xml.NewXML;

/**
 *
 * @author Rafael
 */
public class JDialogCloseSale extends javax.swing.JDialog {

    private static PreparedStatement ps;
    private static Statement stmt;
    private static ResultSet rs;
    private static Connection conn;
    private static final DecimalFormat v = new DecimalFormat("0.00");
    private boolean endSale = false;
    private boolean isPrint = false;
    private final boolean reportManegerial = false;
    private double value_pay_database;
    private double value_pay_coupon;
    private double valueReport;
    private static double value_total_product_coupon;
    private static double value_total_discount_coupon;
    private static double value_total_cost_coupon;
    public static String type_pay_database;
    private double value_pay;
    private double value_discount_pay;
    public static String type_pay_coupom = "DINHEIRO";
    private static final List<String> list_type_pay_coupon = new ArrayList<>();
    private static final List<Double> list_value_pay_coupon = new ArrayList<>();
    private static List<String> old_list_type_pay_coupon = new ArrayList<>();
    private static List<Double> old_list_value_pay_coupon = new ArrayList<>();
    //private static final NewXML newXML = new NewXML();
    private static double old_value_total_product_coupon;
    private static double old_value_pay_coupon;
    private static ClassPrintCoupon pc;
    private static String CPF;
    private static int _return = 0;
    private static boolean isRegistred = false;

    /**
     * Creates new form Login
     *
     * @param parent
     * @param modal
     */
    public JDialogCloseSale(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCards = new javax.swing.JDialog();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList(ClassSale.allCards().toArray());
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonPagCartao = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton50Reais = new javax.swing.JButton();
        jButton10Reais = new javax.swing.JButton();
        jButton20Reais = new javax.swing.JButton();
        jTextCash = new javax.swing.JTextField();
        jTextSmallCash = new javax.swing.JTextField();
        jTextValueTotalCoupon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonFinalizaCalculoPagameto = new javax.swing.JButton();
        jButtonLimpaCalculoPagamento = new javax.swing.JButton();
        jButtonSairCalculoPagamento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextValueTotalDiscontCoupon = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemPaymentCardCredit = new javax.swing.JMenuItem();
        jMenuItemDiscount = new javax.swing.JMenuItem();
        jMenuIteExactCash = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();

        jDialogCards.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialogCardsWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialogCardsWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogCardsWindowClosing(evt);
            }
        });

        jButton10.setText("OK [Enter]");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Cancelar [Esc]");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jDialogCardsLayout = new javax.swing.GroupLayout(jDialogCards.getContentPane());
        jDialogCards.getContentPane().setLayout(jDialogCardsLayout);
        jDialogCardsLayout.setHorizontalGroup(
            jDialogCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jDialogCardsLayout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogCardsLayout.setVerticalGroup(
            jDialogCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCardsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(128, 128, 128));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(227, 227, 227));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        jPanel2.setBackground(new java.awt.Color(227, 227, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("1");
        jButton1.setName("1"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("2");
        jButton2.setName("2"); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("3");
        jButton3.setName("3"); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("4");
        jButton4.setName("4"); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("5");
        jButton5.setName("5"); // NOI18N
        jButton5.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("6");
        jButton6.setName("6"); // NOI18N
        jButton6.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("7");
        jButton7.setName("7"); // NOI18N
        jButton7.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 51));
        jButton8.setText("8");
        jButton8.setName("8"); // NOI18N
        jButton8.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 51, 51));
        jButton9.setText("9");
        jButton9.setName("9"); // NOI18N
        jButton9.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonPagCartao.setFont(new java.awt.Font("Impact", 2, 18)); // NOI18N
        jButtonPagCartao.setForeground(new java.awt.Color(51, 51, 51));
        jButtonPagCartao.setText("Cartão ( F1 )");
        jButtonPagCartao.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonPagCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagCartaoActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 51, 51));
        jButton12.setText("0");
        jButton12.setName("0"); // NOI18N
        jButton12.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton50Reais.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton50Reais.setForeground(new java.awt.Color(51, 51, 51));
        jButton50Reais.setText("50");
        jButton50Reais.setName("50.00"); // NOI18N
        jButton50Reais.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton50Reais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ReaisActionPerformed(evt);
            }
        });

        jButton10Reais.setFont(new java.awt.Font("Impact", 3, 18)); // NOI18N
        jButton10Reais.setForeground(new java.awt.Color(51, 51, 51));
        jButton10Reais.setText("10");
        jButton10Reais.setName("10.00"); // NOI18N
        jButton10Reais.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton10Reais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ReaisActionPerformed(evt);
            }
        });

        jButton20Reais.setFont(new java.awt.Font("Impact", 3, 14)); // NOI18N
        jButton20Reais.setForeground(new java.awt.Color(51, 51, 51));
        jButton20Reais.setText("20");
        jButton20Reais.setName("20.00"); // NOI18N
        jButton20Reais.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton20Reais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ReaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPagCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton50Reais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10Reais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton20Reais, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jButtonPagCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(jButton50Reais, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10Reais, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton20Reais, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTextCash.setFont(new java.awt.Font("Impact", 3, 24)); // NOI18N
        jTextCash.setForeground(new java.awt.Color(51, 51, 51));
        jTextCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCashActionPerformed(evt);
            }
        });
        jTextCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCashKeyReleased(evt);
            }
        });

        jTextSmallCash.setEditable(false);
        jTextSmallCash.setFont(new java.awt.Font("Impact", 3, 24)); // NOI18N
        jTextSmallCash.setForeground(new java.awt.Color(51, 51, 51));

        jTextValueTotalCoupon.setEditable(false);
        jTextValueTotalCoupon.setFont(new java.awt.Font("Impact", 3, 24)); // NOI18N
        jTextValueTotalCoupon.setForeground(new java.awt.Color(51, 51, 51));
        jTextValueTotalCoupon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextValueTotalCouponMouseClicked(evt);
            }
        });
        jTextValueTotalCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValueTotalCouponActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Total R$:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Troco R$:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Dinheiro R$:");

        jPanel3.setBackground(new java.awt.Color(227, 227, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButtonFinalizaCalculoPagameto.setFont(new java.awt.Font("Impact", 2, 15)); // NOI18N
        jButtonFinalizaCalculoPagameto.setForeground(new java.awt.Color(51, 51, 51));
        jButtonFinalizaCalculoPagameto.setText("Fim");
        jButtonFinalizaCalculoPagameto.setEnabled(false);
        jButtonFinalizaCalculoPagameto.setPreferredSize(new java.awt.Dimension(83, 18));
        jButtonFinalizaCalculoPagameto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizaCalculoPagametoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFinalizaCalculoPagameto);

        jButtonLimpaCalculoPagamento.setFont(new java.awt.Font("Impact", 2, 15)); // NOI18N
        jButtonLimpaCalculoPagamento.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLimpaCalculoPagamento.setText("Limpa");
        jButtonLimpaCalculoPagamento.setPreferredSize(new java.awt.Dimension(83, 18));
        jButtonLimpaCalculoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaCalculoPagamentoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLimpaCalculoPagamento);

        jButtonSairCalculoPagamento.setFont(new java.awt.Font("Impact", 2, 14)); // NOI18N
        jButtonSairCalculoPagamento.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSairCalculoPagamento.setText("Sair(Esc)");
        jButtonSairCalculoPagamento.setPreferredSize(new java.awt.Dimension(83, 18));
        jButtonSairCalculoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCalculoPagamentoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSairCalculoPagamento);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Desconto R$:");

        jTextValueTotalDiscontCoupon.setEditable(false);
        jTextValueTotalDiscontCoupon.setFont(new java.awt.Font("Impact", 3, 24)); // NOI18N
        jTextValueTotalDiscontCoupon.setForeground(new java.awt.Color(51, 51, 51));
        jTextValueTotalDiscontCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValueTotalDiscontCouponActionPerformed(evt);
            }
        });
        jTextValueTotalDiscontCoupon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextValueTotalDiscontCouponFocusLost(evt);
            }
        });
        jTextValueTotalDiscontCoupon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextValueTotalDiscontCouponKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextSmallCash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jTextCash, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextValueTotalCoupon)
                            .addComponent(jTextValueTotalDiscontCoupon))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValueTotalCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValueTotalDiscontCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSmallCash, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextCash, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(20, 20));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setText("Ações");

        jMenuItemPaymentCardCredit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemPaymentCardCredit.setText("Pag. Cartão");
        jMenuItemPaymentCardCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPaymentCardCreditActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPaymentCardCredit);

        jMenuItemDiscount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemDiscount.setText("Desconto");
        jMenuItemDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDiscountActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDiscount);

        jMenuIteExactCash.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jMenuIteExactCash.setText("Dinheiro Certo");
        jMenuIteExactCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIteExactCashActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIteExactCash);

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuExit.setText("Sair");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        list_type_pay_coupon.clear();
        list_value_pay_coupon.clear();
        isPrint = false;
        jTextCash.requestFocus(true);
        //dinheiro.setText(valor_total.getText());
        jButtonFinalizaCalculoPagameto.requestFocus(true);
        jTextCash.setText("0,00");
        jTextValueTotalDiscontCoupon.setText("0,00");
        jTextSmallCash.setText("0,00");
        jTextCash.requestFocus(true);
        value_total_product_coupon = Double.parseDouble(v.format(Sale.getPriceTotal()).replace(",", "."));
        value_total_cost_coupon = Double.parseDouble(v.format(Sale.getCostTotal()).replace(",", "."));
        jTextValueTotalCoupon.setText(v.format(Sale.getPriceTotal()).replace(".", ","));

    }//GEN-LAST:event_formWindowOpened

    private void jTextCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCashActionPerformed
        type_pay_database = "DINHEIRO";
        functionSetTypePay("DINHEIRO");

    }//GEN-LAST:event_jTextCashActionPerformed

    private void jButtonFinalizaCalculoPagametoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizaCalculoPagametoActionPerformed

        if (!jTextCash.getText().isEmpty()) {

            isNewCoupon = true;
            isPrint = false;
            endSale = true;
            if (type_pay_coupom.equals("DINHEIRO")) {
                value_pay = Double.parseDouble(jTextCash.getText().replace(",", "."));
            }
            this.dispose();
        }

    }//GEN-LAST:event_jButtonFinalizaCalculoPagametoActionPerformed

    private void jButtonPagCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagCartaoActionPerformed

        fnPayCard();

    }//GEN-LAST:event_jButtonPagCartaoActionPerformed

    private void jButtonLimpaCalculoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaCalculoPagamentoActionPerformed
        jTextCash.setText("0,00");
        jTextSmallCash.setText("0,00");
        jTextCash.requestFocus(true);
    }//GEN-LAST:event_jButtonLimpaCalculoPagamentoActionPerformed

    private void jButtonSairCalculoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCalculoPagamentoActionPerformed
        ClassSale.clearTypePayment(codeCoupon);
        jTextValueTotalCoupon.setText(v.format(Sale.getPriceTotal()));
        jTextCash.setText("0,00");
        jTextSmallCash.setText("0,00");
        jTextCash.requestFocus(true);
        dispose();
        // printFooterCoupon();
    }//GEN-LAST:event_jButtonSairCalculoPagamentoActionPerformed

    private void jTextValueTotalCouponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextValueTotalCouponMouseClicked
        jTextCash.setText(jTextValueTotalCoupon.getText());
        BigDecimal calculo = calculaTroco(Double.parseDouble(jTextValueTotalCoupon.getText().replace(",", ".")), Double.parseDouble(jTextCash.getText().replace(",", ".")), Double.parseDouble(jTextValueTotalDiscontCoupon.getText().replace(",", ".")));
        jTextSmallCash.setText(v.format(calculo));
        jTextCash.requestFocus(true);
    }//GEN-LAST:event_jTextValueTotalCouponMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        try {
            Method something
                    = this.getClass().getDeclaredMethod("fnCloseSale", new Class[0]);

            ClassLoadingMethods.loading(something, this); // Aqui enviamos o metodo doIt !  
        } catch (NoSuchMethodException | SecurityException ex) {
            System.err.println("ERROR::" + ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void jTextCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCashKeyReleased
        JTextFieldTools.formatJTextNumber(jTextCash);
    }//GEN-LAST:event_jTextCashKeyReleased

    private void jButton50ReaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ReaisActionPerformed

        double v1 = 50.00;
        double v2 = Double.parseDouble(jTextCash.getText().replace(",", "."));
        jTextCash.setText(v.format(v1 + v2));
        jTextCash.requestFocus(true);

    }//GEN-LAST:event_jButton50ReaisActionPerformed

    private void jButton20ReaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ReaisActionPerformed

        double v1 = 20.00;
        double v2 = Double.parseDouble(jTextCash.getText().replace(",", "."));
        jTextCash.setText(v.format(v1 + v2));
        jTextCash.requestFocus(true);

    }//GEN-LAST:event_jButton20ReaisActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        String dig = evt.getComponent().getName();
        jTextCash.setText(jTextCash.getText().concat(dig));
        JTextFieldTools.formatJTextNumber(jTextCash);
        jTextCash.requestFocus(true);


    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton10ReaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ReaisActionPerformed
        double v1 = 10.00;
        double v2 = Double.parseDouble(jTextCash.getText().replace(",", "."));
        jTextCash.setText(v.format(v1 + v2));
        jTextCash.requestFocus(true);

    }//GEN-LAST:event_jButton10ReaisActionPerformed

    private void jTextValueTotalCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValueTotalCouponActionPerformed
        jTextCash.setText(jTextValueTotalCoupon.getText());
        BigDecimal calculo = calculaTroco(Double.parseDouble(jTextValueTotalCoupon.getText().replace(",", ".")), Double.parseDouble(jTextCash.getText().replace(",", ".")), Double.parseDouble(jTextValueTotalDiscontCoupon.getText().replace(",", ".")));
        jTextSmallCash.setText(v.format(calculo));
        jTextCash.requestFocus(true);
    }//GEN-LAST:event_jTextValueTotalCouponActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jDialogCardsWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogCardsWindowActivated
        jList1.setSelectedIndex(0);
        jList1.requestFocus(true);
    }//GEN-LAST:event_jDialogCardsWindowActivated

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        if (jList1.getSelectedValue().toString() != null) {

            type_pay_database = jList1.getSelectedValue().toString();
            type_pay_coupom = "CARTAO";

            if (type_pay_database.contains("PENDURA")) {

                Bean.setBean(codeCoupon);
                new JDialogClient(null, true).setVisible(true);
                Bean.setBean(null);
                if (Sale.isIsRegistredAccount()) {

                    isRegistred = true;
                    type_pay_coupom = "PENDURA";
                    functionSetTypePay(type_pay_coupom);
                    jDialogCards.dispose();

                }

            } else {

                functionSetTypePay(type_pay_coupom);
                jDialogCards.dispose();
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        jDialogCards.dispose();

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ESCAPE) {

            jDialogCards.dispose();

        }

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {

            if (jList1.getSelectedValue().toString() != null) {

                type_pay_database = jList1.getSelectedValue().toString();
                type_pay_coupom = "CARTAO";

                if (type_pay_database.contains("PENDURA")) {

                    Bean.setBean(codeCoupon);
                    new JDialogClient(null, true).setVisible(true);
                    Bean.setBean(null);
                    if (Sale.isIsRegistredAccount()) {
                        isRegistred = true;
                        functionSetTypePay(type_pay_coupom);
                        jDialogCards.dispose();
                    }

                } else {

                    functionSetTypePay(type_pay_coupom);
                    jDialogCards.dispose();
                }
            }
        }
    }//GEN-LAST:event_jList1KeyPressed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        type_pay_database = jList1.getSelectedValue().toString();

        if (type_pay_database.contains("PENDURA")) {

            Bean.setBean(codeCoupon);
            new JDialogClient(null, true).setVisible(true);
            Bean.setBean(null);
            System.out.println("REGISTROU CONTA:::::::" + Sale.isIsRegistredAccount());

            if (Sale.isIsRegistredAccount()) {

                isRegistred = true;
                type_pay_coupom = "PENDURA";
                functionSetTypePay(type_pay_coupom);
                Sale.setIsRegistredAccount(false);
                jDialogCards.dispose();

            }

        } else if (evt.getClickCount() == 2) {

            if (jList1.getSelectedValue().toString() != null) {

                type_pay_database = jList1.getSelectedValue().toString();
                type_pay_coupom = "CARTAO";

                isRegistred = true;
                functionSetTypePay(type_pay_coupom);
                jDialogCards.dispose();
            }
        }

    }//GEN-LAST:event_jList1MouseClicked

    private void jDialogCardsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogCardsWindowClosed


    }//GEN-LAST:event_jDialogCardsWindowClosed

    private void jTextValueTotalDiscontCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValueTotalDiscontCouponActionPerformed
        jTextCash.requestFocus(true);
        jTextValueTotalDiscontCoupon.setEditable(false);
    }//GEN-LAST:event_jTextValueTotalDiscontCouponActionPerformed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowIconified

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed

        dispose();
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuIteExactCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIteExactCashActionPerformed
        jTextCash.setText(jTextValueTotalCoupon.getText());
        // BigDecimal calculo = calculaTroco(Double.parseDouble(valor_total.getText()), Double.parseDouble(dinheiro.getText()));
        //String res = new String();
        //res = String.valueOf(calculo);
        //troco.setText(res);
        jTextCash.requestFocus(true);
    }//GEN-LAST:event_jMenuIteExactCashActionPerformed

    private void jMenuItemPaymentCardCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPaymentCardCreditActionPerformed

        fnPayCard();

    }//GEN-LAST:event_jMenuItemPaymentCardCreditActionPerformed

    private void jMenuItemDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDiscountActionPerformed
        if (BeanLogin.isIsCashierAccess()) {

            String code_main = JTextFieldTools.enterCodeAcsses(this);
            if (ClassUser.validatorCode(code_main)) {

                jTextValueTotalDiscontCoupon.setEditable(true);
                jTextValueTotalDiscontCoupon.requestFocus(true);
            } else {

                JOptionPane.showMessageDialog(this, "Codigo inválido!", "UPMarket diz:", JOptionPane.ERROR_MESSAGE);

            }
        } else {

            JOptionPane.showMessageDialog(this, "Acesso negado!", "Função Restrita.", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemDiscountActionPerformed

    private void jTextValueTotalDiscontCouponKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextValueTotalDiscontCouponKeyReleased
        JTextFieldTools.formatJTextNumber(jTextValueTotalDiscontCoupon);
    }//GEN-LAST:event_jTextValueTotalDiscontCouponKeyReleased

    private void jTextValueTotalDiscontCouponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextValueTotalDiscontCouponFocusLost
        jTextValueTotalDiscontCoupon.setEditable(false);
    }//GEN-LAST:event_jTextValueTotalDiscontCouponFocusLost

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        pc = new ClassPrintCoupon();
    }//GEN-LAST:event_formWindowActivated

    private void jDialogCardsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogCardsWindowClosing


    }//GEN-LAST:event_jDialogCardsWindowClosing

    public static BigDecimal calculaTroco(double total, double dinheiro, double desconto) {

        BigDecimal r = new BigDecimal(BigInteger.ZERO, 2);

        r = BigDecimal.valueOf(dinheiro - (total - desconto));

        return r;
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogCloseSale dialog = new JDialogCloseSale(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton10Reais;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20Reais;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50Reais;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonFinalizaCalculoPagameto;
    private javax.swing.JButton jButtonLimpaCalculoPagamento;
    private javax.swing.JButton jButtonPagCartao;
    private javax.swing.JButton jButtonSairCalculoPagamento;
    private javax.swing.JDialog jDialogCards;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuIteExactCash;
    private javax.swing.JMenuItem jMenuItemDiscount;
    private javax.swing.JMenuItem jMenuItemPaymentCardCredit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextCash;
    public static javax.swing.JTextField jTextSmallCash;
    public static javax.swing.JTextField jTextValueTotalCoupon;
    public static javax.swing.JTextField jTextValueTotalDiscontCoupon;
    // End of variables declaration//GEN-END:variables

    private void functionSetTypePay(String type_pay) {

        if (!jTextCash.getText().equals("0,00") && !"".equals(type_pay_database) && !"".equals(type_pay_coupom)) {

            BigDecimal calculo = calculaTroco(Double.parseDouble(jTextValueTotalCoupon.getText().replace(",", ".")), Double.parseDouble(jTextCash.getText().replace(",", ".")), Double.parseDouble(jTextValueTotalDiscontCoupon.getText().replace(",", ".")));
            type_pay_coupom = type_pay;
            double value_discount = +Double.parseDouble(jTextValueTotalDiscontCoupon.getText().replace(",", "."));

            System.err.println("####TYPE PAY COUPON>>>" + type_pay_coupom);
            System.err.println("####TYPE PAY DB>>>" + type_pay_database);

            //sem troco
            if (calculo.doubleValue() == 0) {

                value_pay_database = Double.parseDouble(jTextValueTotalCoupon.getText().replace(",", "."));
                value_pay_coupon = Double.parseDouble(jTextValueTotalCoupon.getText().replace(",", "."));

                list_value_pay_coupon.add(value_pay_coupon);
                list_type_pay_coupon.add(type_pay_coupom);
                if (value_discount > 0) {
                    list_value_pay_coupon.add(value_discount * -1);
                    list_type_pay_coupon.add("DESCONTO");
                }

                value_pay = Double.parseDouble(jTextCash.getText().replace(",", "."));
                value_discount_pay = Double.parseDouble(jTextValueTotalDiscontCoupon.getText().replace(",", "."));

                ClassSale.setTypePayment(codeCoupon, type_pay_database, value_pay_database, value_pay, value_discount_pay);

                isNewCoupon = true;
                isPrint = false;
                endSale = true;

                this.dispose();

                //com troco
            } else if (calculo.doubleValue() > 0) {

                value_pay_database = Double.parseDouble(jTextValueTotalCoupon.getText().replace(",", "."));
                value_pay_coupon = Double.parseDouble(jTextCash.getText().replace(",", "."));
                list_value_pay_coupon.add(value_pay_coupon);
                list_type_pay_coupon.add(type_pay_coupom);

                if (value_discount > 0) {
                    list_value_pay_coupon.add(value_discount * -1);
                    list_type_pay_coupon.add("DESCONTO");
                }

                value_pay = Double.parseDouble(jTextCash.getText().replace(",", "."));
                value_discount_pay = Double.parseDouble(jTextValueTotalDiscontCoupon.getText().replace(",", "."));

                ClassSale.setTypePayment(codeCoupon, type_pay_database, value_pay_database, value_pay, value_discount_pay);

                jTextSmallCash.setText(v.format(calculo).replace(".", ","));
                jButtonFinalizaCalculoPagameto.requestFocus(true);
                jButtonFinalizaCalculoPagameto.setEnabled(true);

                //troco negativo
            } else if (calculo.doubleValue() < 0) {

                int option;
                option = JOptionPane.showConfirmDialog(this, "Falatam R$ " + v.format(calculo.doubleValue() * -1).replace(",", ".") + ". Deseja  completar o valor com outra forma de pagamento?", "Aviso!", JOptionPane.YES_NO_OPTION);

                if (option == 0) {
                    jTextValueTotalCoupon.setText(v.format(calculo.doubleValue() * -1).replace(".", ","));
                    value_pay_database = Double.parseDouble(jTextCash.getText().replace(",", "."));
                    value_discount_pay = Double.parseDouble(jTextValueTotalDiscontCoupon.getText().replace(",", "."));

                    list_value_pay_coupon.add(value_pay_database);
                    list_type_pay_coupon.add(type_pay_coupom);

                    if (value_discount > 0) {
                        list_value_pay_coupon.add(value_discount * -1);
                        list_type_pay_coupon.add("DESCONTO");
                    }

                    ClassSale.setTypePayment(codeCoupon, type_pay_database, value_pay_database + value_discount, value_pay_database, value_discount_pay);
                    jTextValueTotalDiscontCoupon.setText("0,00");
                    jTextCash.setText("0,00");
                    jTextSmallCash.setText("0,00");

                } else {

                    ClassSale.clearTypePayment(codeCoupon);
                    list_value_pay_coupon.clear();
                    list_type_pay_coupon.clear();
                    jTextValueTotalCoupon.setText(v.format(Sale.getPriceTotal()).replace(".", ","));
                    jTextCash.setText("0,00");
                    jTextSmallCash.setText("0,00");
                    jTextCash.requestFocus(true);

                }

            }
        }
    }

    public static boolean reprintCoupon(String arg) {
        String dateHour = null;
        try {

            ps = Conn.connect().prepareStatement("SELECT  t.`description_type_payment_coupon`, t.`value_type_payment_coupon`, t.`cashPay`, c.`total_coupon`, DATE_FORMAT(c.`date_hour_coupon`,'%d/%m/%Y %H:%i:%s' ) AS date_hour FROM tbl_type_payment_coupon t INNER JOIN tbl_coupon c ON t.`idtbl_coupon` = c.`idtbl_coupon` WHERE t.`idtbl_coupon` = ? AND t.`isCanceled` = 0;");

            ps.setString(1, arg);
            rs = ps.executeQuery();

            while (rs.next()) {
                dateHour = rs.getString("date_hour");
            }

            pc.printHeaderCoupon(true, arg, dateHour, idCashier, headerCoupon);

            ps = Conn.connect().prepareStatement("SELECT c.`idtbl_coupon`,"
                    + " pc.`prod_bar_code_product`,"
                    + " pc.`product_price`,"
                    + " pc.`product_quantity`,"
                    + " pc.`number_iten`,"
                    + " pc.`quantity_iten`,"
                    + " p.`idtbl_unity_measure`,"
                    + " p.`prod_abbreviature` FROM tbl_coupon c INNER JOIN tbl_product_coupon pc ON c.`idtbl_coupon` = pc.`idtbl_coupon` JOIN tbl_product p ON p.`prod_bar_code_product` = pc.`prod_bar_code_product` WHERE c.`idtbl_coupon`= ?;");

            ps.setString(1, arg);
            rs = ps.executeQuery();

            while (rs.next()) {

                boolean b = rs.getString("prod_bar_code_product").startsWith("2");
                ClassPrintCoupon.printLineCoupon(b, rs.getString("prod_bar_code_product"), rs.getDouble("product_price"), rs.getString("product_quantity"), rs.getString("idtbl_unity_measure"), rs.getString("prod_abbreviature"), rs.getInt("number_iten"));

            }

        } catch (SQLException ex) {
            ////newXML.generateLog(ex.toString());
            System.err.println("ERROR::" + ex);

            return false;

        }
        System.err.println("PRINTFOOTER::"+old_list_value_pay_coupon+","+old_list_type_pay_coupon+","+old_value_total_product_coupon+","+old_value_pay_coupon+","+footerCoupon);
        return pc.printFooterCoupon(false, old_list_value_pay_coupon, old_list_type_pay_coupon, old_value_total_product_coupon, old_value_pay_coupon, null, false, footerCoupon);

    }

    private void fnPayCard() {

        if (!jTextCash.getText().equals("0,00")) {

            Dimension tamanhoDialogMain = getSize();
            Dimension tamanhoDialog1 = jDialogCards.getPreferredSize();
            Point loc = getLocation();
            jDialogCards.setLocation(
                    (tamanhoDialogMain.width - tamanhoDialog1.width) / 2 + loc.x,
                    (tamanhoDialogMain.height - tamanhoDialog1.height) / 2 + loc.y);
            jDialogCards.setModal(true);
            jDialogCards.pack();
            jDialogCards.setVisible(true);

        }
    }
/*
    private void fnRegisterCPF() {

        CPF = JTextFieldTools.enterCPF(this);
        Client client = ClassClient.consultClient(CPF);

        if ((client.getIdtbl_client() == null) && (!"___.___.___/__".equals(CPF))) {

            if (JOptionPane.showConfirmDialog(this, " CPF não cadastrado.\n Deseja cadastrar o CPF?",
                    "Consulta de Cliente", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {

                Bean.setBean(CPF);
                new JDialogClient(null, true).setVisible(true);
                fnRegisterCPF();

            } else {

                type_pay_database = "";
                type_pay_coupom = "";

            }

        } else if (client.getIdtbl_client() != null) {

            if (confirmCPF(this, client) == 1) {

                isRegistred = ClassSale.registerSaleAccountClient(codeCoupon, CPF, Sale.getPriceTotal());

            } else {

                fnRegisterCPF();

            }

            if (isRegistred) {

                functionSetTypePay(type_pay_coupom);
            }

            jDialogCards.dispose();

        }
    }

    public static int confirmCPF(Component c, Client client) {

        JLabel jLabelName = new JLabel(client.getName_client());
        JLabel jLabelCPF = new JLabel(client.getCpf_client());
        JLabel jLabelPhone = new JLabel(client.getPhone_client());
        JLabel jLabelAddress = new JLabel(client.getAddress_client());
        JButton jButtonConfirm = new JButton("SIM");
        JButton jButtonNotConfirm = new JButton("NÃO");

        jLabelName.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabelCPF.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabelName.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        jLabelCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Object[] options = {jLabelName, jLabelCPF, jLabelPhone, jLabelAddress, jButtonConfirm, jButtonNotConfirm};
        final JOptionPane pane = new JOptionPane("Você confirma os dados do cliente?", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[4]);
        final JDialog dialog = pane.createDialog(c, "Consulta de Cliente");

        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmFieldActionPerformed(evt);
            }

            private void jButtonConfirmFieldActionPerformed(ActionEvent evt) {

                _return = 1;
                dialog.dispose();

            }

        });

        jButtonNotConfirm.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotConfirmFieldActionPerformed(evt);
            }

            private void jButtonNotConfirmFieldActionPerformed(ActionEvent evt) {

                _return = 0;
                dialog.dispose();

            }

        });

        dialog.show();
        return _return;
    }
*/
    public void fnCloseSale() {

        value_total_discount_coupon = Double.parseDouble(jTextValueTotalDiscontCoupon.getText().replace(",", "."));
        oldCodeCoupon = codeCoupon;
        old_list_value_pay_coupon = list_value_pay_coupon;
        old_list_type_pay_coupon = list_type_pay_coupon;
        old_value_total_product_coupon = value_total_product_coupon;
        old_value_pay_coupon = value_pay_coupon;

        if (isPrintService) {

            if (!isPrint) {

                if (endSale) {

                    ImprimirRelatorio_cupom imp = new ImprimirRelatorio_cupom();
                    try {

                        if (reportManegerial) {

                            String str = NumberInFull.numberInFull(v.format(valueReport));
                            Object[] valPar2 = {codeCoupon, valueReport, type_pay_coupom, str};
                            Object[] par2 = {"PAR_COD", "PAR_DIN", "PAR_TYPE_PAG", "PAR_DIN_EXT"};

                            ClassSale.closeSale(codeCoupon, true, value_total_product_coupon, value_total_cost_coupon, value_total_discount_coupon);
                            refreshLot(codeCoupon);
                            setLaunch(codeCoupon);
                            ClassSale.refreshReserve(codeCoupon, false);
                            System.out.println("LIST TYPE PAY:::" + list_type_pay_coupon);
                            System.out.println("LIST VALUE PAY:::" + list_value_pay_coupon);
                            pc.printFooterCoupon(false, list_value_pay_coupon, list_type_pay_coupon, value_total_product_coupon, value_pay_coupon, null, false, footerCoupon);
                            list_type_pay_coupon.clear();
                            list_value_pay_coupon.clear();

                            imp.visualizarRelatorio(valPar2, par2, "relatorio_gerencial_vale.jasper", false);

                        } else {

                            ClassSale.closeSale(codeCoupon, true, value_total_product_coupon, value_total_cost_coupon, value_total_discount_coupon);
                            refreshLot(codeCoupon);
                            setLaunch(codeCoupon);
                            ClassSale.refreshReserve(codeCoupon, false);
                            System.out.println("LIST TYPE PAY:::" + list_type_pay_coupon);
                            pc.printFooterCoupon(false, list_value_pay_coupon, list_type_pay_coupon, value_total_product_coupon, value_pay_coupon, null, false, footerCoupon);
                            list_type_pay_coupon.clear();
                            list_value_pay_coupon.clear();
                            // }
                        }

                        codeCoupon = null;
                        BeanCodeSale.setCodeSale(null);
                        isPrint = true;
                        isGenerateCodeCoupon = true;
                        isNewCoupon = true;
                        endSale = true;

                        if (type_pay_database.contains("PENDURA")) {

                            ClassSale.reprintCoupon(lastCodeCoupon, true);

                        }

                    } catch (Exception ex) {
                        System.err.println("ERROR::" + ex);
                        ////newXML.generateLog(ex.toString());
                    }

                }

            }

            jTextValueTotalCoupon.setText(v.format(Sale.getPriceTotal()));
            jTextCash.setText("0,00");
            jTextSmallCash.setText("0,00");
            jTextCash.requestFocus(true);
            //ClassSale.clearTypePayment(codeCoupon);
            //list_type_pay_coupon.clear();
            //list_value_pay_coupon.clear();

        } else {

            if (endSale) {
                ClassSale.closeSale(codeCoupon, true, value_total_product_coupon, value_total_cost_coupon, value_total_discount_coupon);
                refreshLot(codeCoupon);
                setLaunch(codeCoupon);
                ClassSale.refreshReserve(codeCoupon, false);
                codeCoupon = null;
                BeanCodeSale.setCodeSale(null);
                isPrint = true;
                isGenerateCodeCoupon = true;
                isNewCoupon = true;
                endSale = true;
                jTextValueTotalCoupon.setText(v.format(Sale.getPriceTotal()));
                jTextCash.setText("0,00");
                jTextSmallCash.setText("0,00");
                jTextCash.requestFocus(true);
                //list_type_pay_coupon.clear();
                //list_value_pay_coupon.clear();
                if (type_pay_database.contains("PENDURA")) {

                    ClassSale.reprintCoupon(lastCodeCoupon, true);

                }
            }

        }

        System.err.println("####AFTER CLOSED VALUES LIST TYPE PAY>>>#####" + list_type_pay_coupon);
        System.err.println("####AFTER CLOSED VALUES LIST VAUE PAY>>>#####" + list_value_pay_coupon);

    }
}
