 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import action.Bean;
import action.BeanLogin;
import action.BeanProductTransition;
import action.Sale;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import model.ClassInventory;
import model.ClassProduct;
import model.ClassSale;
import util.DimensionFrame;
import util.PreencheTabela;
import xml.NewXML;

/**
 *
 * @author root
 */
public class JFrameAdministrator extends javax.swing.JFrame {

    private static final DecimalFormat v = new DecimalFormat("0.00");
    private final Color whiteColor = Color.white;                 // new Color(254, 254, 254);
    private final Color alternateColor = new Color(227, 227, 227);    // Color.lightGray;//new Color(204, 204, 204);
    private final Color selectedColor = Color.yellow;
    private static final Dimension dimension = new Dimension(DimensionFrame.getDimension());
    public DefaultListModel listModel = new DefaultListModel();
    public static String codeCoupon;
    public static String codeProductCoupon;
    public static int numberItenCancel;
    public static double valueItenCanceled;
    public static int number_item = 1;
    public static boolean isNewCoupon = true;
    private static final String[] head = {"Item", "Descrição", "UN", "Qtd", "Preço", "Total"};
    public static volatile boolean isCancelProduct = false;
    java.awt.Dimension tamanhoFrame = getSize();
    private PreencheTabela tabela;
    private final DecimalFormat cd_3 = new DecimalFormat("0.000");
    private static final int control_qtd = 1;
    private static final double quantityItem = 1.00;
    private final boolean isCoolingRate = false;
    private static final double valueCoolingRate = ClassProduct.coolingRate();
    public static boolean isPrintService = true;
    private final boolean isCodeRapid = false;
    public static boolean isGenerateCodeCoupon = true;
    public static String idCashier;
    private static final String isOpenedCashier = null;
    private static final NewXML newXML = new NewXML();
    private static URI uri;

    /**
     * Creates new form JFrameSale
     */
    public JFrameAdministrator() {
        initComponents();
        // this.setSize(dimension);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTABPrice = new javax.swing.ButtonGroup();
        jDialogSearchProduct = new javax.swing.JDialog();
        jTextFieldBarCodeSearch = new javax.swing.JTextField();
        jTextFieldDescriptionSearch = new javax.swing.JTextField();
        jTextFieldValueProductSearch = new javax.swing.JTextField();
        jPanelFuncoes = new javax.swing.JPanel();
        jButtonRegisterProduct = new javax.swing.JButton();
        jButtonConsultProduct = new javax.swing.JButton();
        jButtonControlReserve = new javax.swing.JButton();
        jButtonRegisterCard = new javax.swing.JButton();
        jButtonRegisterUser = new javax.swing.JButton();
        jButtonCategory = new javax.swing.JButton();
        jButtonReports = new javax.swing.JButton();
        jButtonRegisterVendor = new javax.swing.JButton();
        jButtonMovementsCashier = new javax.swing.JButton();
        jButtonLogoffLogon = new javax.swing.JButton();
        jButtonSales = new javax.swing.JButton();
        jButtonInternet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        jDialogSearchProduct.setTitle("Consulat de Produto");
        jDialogSearchProduct.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialogSearchProductWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialogSearchProductWindowClosed(evt);
            }
        });

        jTextFieldBarCodeSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldBarCodeSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Código de barra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jTextFieldBarCodeSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBarCodeSearchMouseClicked(evt);
            }
        });
        jTextFieldBarCodeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBarCodeSearchActionPerformed(evt);
            }
        });
        jTextFieldBarCodeSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBarCodeSearchKeyPressed(evt);
            }
        });

        jTextFieldDescriptionSearch.setEditable(false);
        jTextFieldDescriptionSearch.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescriptionSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldDescriptionSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Descrição do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jTextFieldDescriptionSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescriptionSearchActionPerformed(evt);
            }
        });

        jTextFieldValueProductSearch.setEditable(false);
        jTextFieldValueProductSearch.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValueProductSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldValueProductSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Valor R$", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jTextFieldValueProductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValueProductSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSearchProductLayout = new javax.swing.GroupLayout(jDialogSearchProduct.getContentPane());
        jDialogSearchProduct.getContentPane().setLayout(jDialogSearchProductLayout);
        jDialogSearchProductLayout.setHorizontalGroup(
            jDialogSearchProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSearchProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogSearchProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDescriptionSearch)
                    .addGroup(jDialogSearchProductLayout.createSequentialGroup()
                        .addComponent(jTextFieldBarCodeSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldValueProductSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDialogSearchProductLayout.setVerticalGroup(
            jDialogSearchProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSearchProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldDescriptionSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogSearchProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValueProductSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBarCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelFuncoes.setBackground(new java.awt.Color(227, 227, 227));
        jPanelFuncoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonRegisterProduct.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonRegisterProduct.setForeground(new java.awt.Color(102, 102, 102));
        jButtonRegisterProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010996].png"))); // NOI18N
        jButtonRegisterProduct.setText("Cadastrar Produtos");
        jButtonRegisterProduct.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonRegisterProduct.setDefaultCapable(false);
        jButtonRegisterProduct.setDisabledIcon(null);
        jButtonRegisterProduct.setDisabledSelectedIcon(null);
        jButtonRegisterProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonRegisterProduct.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRegisterProduct.setIconTextGap(10);
        jButtonRegisterProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterProductActionPerformed(evt);
            }
        });

        jButtonConsultProduct.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonConsultProduct.setForeground(new java.awt.Color(102, 102, 102));
        jButtonConsultProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/11379_32x32.png"))); // NOI18N
        jButtonConsultProduct.setText("Consultar Produtos");
        jButtonConsultProduct.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonConsultProduct.setDefaultCapable(false);
        jButtonConsultProduct.setDisabledIcon(null);
        jButtonConsultProduct.setDisabledSelectedIcon(null);
        jButtonConsultProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonConsultProduct.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonConsultProduct.setIconTextGap(10);
        jButtonConsultProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultProductActionPerformed(evt);
            }
        });

        jButtonControlReserve.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonControlReserve.setForeground(new java.awt.Color(102, 102, 102));
        jButtonControlReserve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/estoque(2).png"))); // NOI18N
        jButtonControlReserve.setText("Estoque");
        jButtonControlReserve.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonControlReserve.setDefaultCapable(false);
        jButtonControlReserve.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonControlReserve.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonControlReserve.setIconTextGap(10);
        jButtonControlReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlReserveActionPerformed(evt);
            }
        });

        jButtonRegisterCard.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonRegisterCard.setForeground(new java.awt.Color(102, 102, 102));
        jButtonRegisterCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010993].png"))); // NOI18N
        jButtonRegisterCard.setText("Cartões");
        jButtonRegisterCard.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonRegisterCard.setDefaultCapable(false);
        jButtonRegisterCard.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonRegisterCard.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRegisterCard.setIconTextGap(10);
        jButtonRegisterCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterCardActionPerformed(evt);
            }
        });

        jButtonRegisterUser.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonRegisterUser.setForeground(new java.awt.Color(102, 102, 102));
        jButtonRegisterUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[009697].png"))); // NOI18N
        jButtonRegisterUser.setText("Cadastrar Usuário");
        jButtonRegisterUser.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonRegisterUser.setDefaultCapable(false);
        jButtonRegisterUser.setDisabledIcon(null);
        jButtonRegisterUser.setDisabledSelectedIcon(null);
        jButtonRegisterUser.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonRegisterUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRegisterUser.setIconTextGap(10);
        jButtonRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterUserActionPerformed(evt);
            }
        });

        jButtonCategory.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonCategory.setForeground(new java.awt.Color(102, 102, 102));
        jButtonCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010987].png"))); // NOI18N
        jButtonCategory.setText("Cadastrar Categoria");
        jButtonCategory.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonCategory.setDefaultCapable(false);
        jButtonCategory.setDisabledIcon(null);
        jButtonCategory.setDisabledSelectedIcon(null);
        jButtonCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonCategory.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonCategory.setIconTextGap(10);
        jButtonCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoryActionPerformed(evt);
            }
        });

        jButtonReports.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonReports.setForeground(new java.awt.Color(102, 102, 102));
        jButtonReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grafics.png"))); // NOI18N
        jButtonReports.setText("Relátorios");
        jButtonReports.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonReports.setDefaultCapable(false);
        jButtonReports.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonReports.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonReports.setIconTextGap(10);
        jButtonReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportsActionPerformed(evt);
            }
        });

        jButtonRegisterVendor.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonRegisterVendor.setForeground(new java.awt.Color(102, 102, 102));
        jButtonRegisterVendor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image2995.png"))); // NOI18N
        jButtonRegisterVendor.setText("Fornecedores");
        jButtonRegisterVendor.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonRegisterVendor.setDefaultCapable(false);
        jButtonRegisterVendor.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonRegisterVendor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonRegisterVendor.setIconTextGap(10);
        jButtonRegisterVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterVendorActionPerformed(evt);
            }
        });

        jButtonMovementsCashier.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonMovementsCashier.setForeground(new java.awt.Color(102, 102, 102));
        jButtonMovementsCashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money_32x32.png"))); // NOI18N
        jButtonMovementsCashier.setText(" Movimentos Caixa");
        jButtonMovementsCashier.setToolTipText("Histórico Movimentos Caixa");
        jButtonMovementsCashier.setDefaultCapable(false);
        jButtonMovementsCashier.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonMovementsCashier.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonMovementsCashier.setIconTextGap(10);
        jButtonMovementsCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMovementsCashierActionPerformed(evt);
            }
        });

        jButtonLogoffLogon.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonLogoffLogon.setForeground(new java.awt.Color(102, 102, 102));
        jButtonLogoffLogon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[010972].png"))); // NOI18N
        jButtonLogoffLogon.setText(" Login/Logoff");
        jButtonLogoffLogon.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonLogoffLogon.setDefaultCapable(false);
        jButtonLogoffLogon.setDisabledIcon(null);
        jButtonLogoffLogon.setDisabledSelectedIcon(null);
        jButtonLogoffLogon.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonLogoffLogon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonLogoffLogon.setIconTextGap(10);
        jButtonLogoffLogon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoffLogonActionPerformed(evt);
            }
        });

        jButtonSales.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonSales.setForeground(new java.awt.Color(102, 102, 102));
        jButtonSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[011001].png"))); // NOI18N
        jButtonSales.setText("Vendas");
        jButtonSales.setToolTipText("Histórico Movimentos Caixa");
        jButtonSales.setDefaultCapable(false);
        jButtonSales.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonSales.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonSales.setIconTextGap(10);
        jButtonSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalesActionPerformed(evt);
            }
        });

        jButtonInternet.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonInternet.setForeground(new java.awt.Color(102, 102, 102));
        jButtonInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/[009716].png"))); // NOI18N
        jButtonInternet.setText("Internet");
        jButtonInternet.setToolTipText("Clique Para fechar  a venda (atalho F1) ");
        jButtonInternet.setDefaultCapable(false);
        jButtonInternet.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonInternet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonInternet.setIconTextGap(10);
        jButtonInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInternetActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Arquivo");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gerenciamento");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Caixa");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Contas");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Relátorios");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Vendas");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Vendas Agrupadas");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cadastros");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Clientes");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fornecedores");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Produtos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuários");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanelFuncoesLayout = new javax.swing.GroupLayout(jPanelFuncoes);
        jPanelFuncoes.setLayout(jPanelFuncoesLayout);
        jPanelFuncoesLayout.setHorizontalGroup(
            jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFuncoesLayout.createSequentialGroup()
                            .addComponent(jButtonReports, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonRegisterCard, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelFuncoesLayout.createSequentialGroup()
                            .addComponent(jButtonRegisterVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelFuncoesLayout.createSequentialGroup()
                            .addComponent(jButtonConsultProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelFuncoesLayout.createSequentialGroup()
                            .addComponent(jButtonRegisterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonControlReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelFuncoesLayout.createSequentialGroup()
                            .addComponent(jButtonMovementsCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonLogoffLogon, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFuncoesLayout.createSequentialGroup()
                        .addComponent(jButtonSales, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButtonInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelFuncoesLayout.setVerticalGroup(
            jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelFuncoesLayout.createSequentialGroup()
                        .addGroup(jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonReports, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRegisterCard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRegisterVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConsultProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRegisterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonControlReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMovementsCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLogoffLogon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelFuncoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSales, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFuncoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFuncoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterProductActionPerformed

        new JDialogProduct_2_0(this, true).setVisible(true);

    }//GEN-LAST:event_jButtonRegisterProductActionPerformed

    private void jButtonConsultProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultProductActionPerformed
        Dimension tamanhoDialogMain = getSize();
        Dimension tamanhoDialog1 = jDialogSearchProduct.getPreferredSize();
        Point loc = getLocation();
        jDialogSearchProduct.setLocation(
                (tamanhoDialogMain.width - tamanhoDialog1.width) / 2 + loc.x,
                (tamanhoDialogMain.height - tamanhoDialog1.height) / 2 + loc.y);
        jDialogSearchProduct.setModal(true);
        jDialogSearchProduct.pack();
        jDialogSearchProduct.setVisible(true);
    }//GEN-LAST:event_jButtonConsultProductActionPerformed

    private void jButtonCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoryActionPerformed

        new JDialogCategory(this, true).setVisible(true);

    }//GEN-LAST:event_jButtonCategoryActionPerformed

    private void jButtonControlReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlReserveActionPerformed
        if (!BeanLogin.isIsControlReserveAccess()) {
            JOptionPane.showMessageDialog(this, "Usuário '" + BeanLogin.getUser() + "' não possui autorização para esta função.", "Alerta de Segurança.", JOptionPane.INFORMATION_MESSAGE);

        } else {
            new JDialogControlProductsReserve(null, true).setVisible(true);
        }
    }//GEN-LAST:event_jButtonControlReserveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        functionControlExpiring();
        Bean.setIsOpened(true);

    }//GEN-LAST:event_formWindowOpened

    private void jButtonRegisterCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterCardActionPerformed
        new JDialogRegisterCards(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonRegisterCardActionPerformed

    private void jButtonRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterUserActionPerformed

        new JDialogUser(this, true).setVisible(true);

    }//GEN-LAST:event_jButtonRegisterUserActionPerformed

    private void jTextFieldBarCodeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBarCodeSearchActionPerformed

        if (ClassSale.searchProduct(jTextFieldBarCodeSearch.getText(), false, 0, false, false) == 0) {

            jTextFieldDescriptionSearch.setText(Sale.getProductName());
            jTextFieldValueProductSearch.setText(v.format(Sale.getProductPrice()).replace(".", ","));
            jTextFieldBarCodeSearch.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Produto não Cadastrado");
            jTextFieldBarCodeSearch.setText("");
        }
    }//GEN-LAST:event_jTextFieldBarCodeSearchActionPerformed

    private void jTextFieldDescriptionSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescriptionSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescriptionSearchActionPerformed

    private void jTextFieldValueProductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValueProductSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValueProductSearchActionPerformed

    private void jTextFieldBarCodeSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBarCodeSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            jDialogSearchProduct.dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            jTextFieldBarCodeSearch.setText("");
        }
    }//GEN-LAST:event_jTextFieldBarCodeSearchKeyPressed

    private void jDialogSearchProductWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogSearchProductWindowActivated
        jTextFieldBarCodeSearch.requestFocus(true);
    }//GEN-LAST:event_jDialogSearchProductWindowActivated

    private void jTextFieldBarCodeSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBarCodeSearchMouseClicked
        jTextFieldBarCodeSearch.setText("");
    }//GEN-LAST:event_jTextFieldBarCodeSearchMouseClicked

    private void jDialogSearchProductWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogSearchProductWindowClosed

        jTextFieldBarCodeSearch.setText("");
        jTextFieldDescriptionSearch.setText("");
        jTextFieldValueProductSearch.setText("");
    }//GEN-LAST:event_jDialogSearchProductWindowClosed

    private void jButtonReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportsActionPerformed
        new JDialogReports(this, true).setVisible(true);
    }//GEN-LAST:event_jButtonReportsActionPerformed

    private void jButtonRegisterVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterVendorActionPerformed

        BeanProductTransition.setControl(false);
        new JDialogRegisterVendor_3_1(this, true).setVisible(true);
    }//GEN-LAST:event_jButtonRegisterVendorActionPerformed

    private void jButtonMovementsCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMovementsCashierActionPerformed

        new JDialogCashierHistory_4_6(null, true).setVisible(true);

    }//GEN-LAST:event_jButtonMovementsCashierActionPerformed

    private void jButtonLogoffLogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoffLogonActionPerformed

        new JDialogLogin(null, true).setVisible(true);

    }//GEN-LAST:event_jButtonLogoffLogonActionPerformed

    private void jButtonSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalesActionPerformed

        new JDialogAllSales(null, true).setVisible(true);

    }//GEN-LAST:event_jButtonSalesActionPerformed

    private void jButtonInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInternetActionPerformed
        try {
            uri = new URI("http://www.google.com.br/");
            fnOpenURL(uri);
        } catch (URISyntaxException ex) {
            System.err.println("ERROR::" + ex);
            //newXML.generateLog(ex.toString());
        }
    }//GEN-LAST:event_jButtonInternetActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged


    }//GEN-LAST:event_jTree1ValueChanged

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        try {
            if (evt.getClickCount() == 2) {

                switch (jTree1.getPathForRow(jTree1.getLeadSelectionRow()).toString()) {

                    case "[Arquivo, Gerenciamento, Vendas Agrupadas]":
                        new JDialogGroupedProductSales(null, true).setVisible(true);
                        break;

                    case "[Arquivo, Gerenciamento, Relátorios]":
                        new JDialogReports(this, true).setVisible(true);
                        break;

                    case "[Arquivo, Gerenciamento, Caixa]":
                        new JDialogCashierHistory_4_6(null, true).setVisible(true);
                        break;

                    case "[Arquivo, Gerenciamento, Vendas]":
                        new JDialogAllSales(null, true).setVisible(true);
                        break;

                    case "[Arquivo, Gerenciamento, Contas]":
                        new JDialogAccountClient(null, true).setVisible(true);
                        break;

                    case "[Arquivo, Cadastros, Produtos]":
                        new JDialogProduct_2_0(this, true).setVisible(true);
                        break;

                    case "[Arquivo, Cadastros, Categorias]":
                        new JDialogCategory(this, true).setVisible(true);
                        break;

                    case "[Arquivo, Cadastros, Clientes]":
                        new JDialogClient(this, true).setVisible(true);
                        break;

                    case "[Arquivo, Cadastros, Usuários]":
                        new JDialogUser(this, true).setVisible(true);
                        break;

                    case "[Arquivo, Cadastros, Fornecedores]":
                        BeanProductTransition.setControl(false);
                        new JDialogRegisterVendor_3_1(this, true).setVisible(true);
                        break;

                }

            }
        } catch (java.lang.NullPointerException ex) {
        }
    }//GEN-LAST:event_jTree1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println("ERROR::" + ex);
            //newXML.generateLog(ex.toString());
            java.util.logging.Logger.getLogger(JFrameAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameAdministrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTABPrice;
    private javax.swing.JButton jButtonCategory;
    private javax.swing.JButton jButtonConsultProduct;
    private javax.swing.JButton jButtonControlReserve;
    private javax.swing.JButton jButtonInternet;
    private javax.swing.JButton jButtonLogoffLogon;
    private javax.swing.JButton jButtonMovementsCashier;
    private javax.swing.JButton jButtonRegisterCard;
    private javax.swing.JButton jButtonRegisterProduct;
    private javax.swing.JButton jButtonRegisterUser;
    private javax.swing.JButton jButtonRegisterVendor;
    private javax.swing.JButton jButtonReports;
    private javax.swing.JButton jButtonSales;
    private javax.swing.JDialog jDialogSearchProduct;
    private javax.swing.JPanel jPanelFuncoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBarCodeSearch;
    private javax.swing.JTextField jTextFieldDescriptionSearch;
    private javax.swing.JTextField jTextFieldValueProductSearch;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    private void functionControlExpiring() {
        JCheckBox checkbox = new JCheckBox("Não exibir esta mensagem novamente.");
        int arg_message = ClassInventory.verifyExpiringLot();
        if (arg_message > 0) {
            String message = "Existem " + arg_message + " lote(s) com vencimento dentro do prazo de alerta.\nDeseja abrir a janela de controle de lotes?";
            Object[] params = {message, checkbox};

            int opcao = 0;
            if (arg_message > 0 && ClassInventory.isAlertExpiring()) {

                opcao = JOptionPane.showConfirmDialog(this, params, "Informação.", JOptionPane.YES_NO_OPTION);

            } else {

                opcao = 1;
            }
            boolean dontShow = checkbox.isSelected();
            if (dontShow) {
                ClassInventory.setAlertExpiring();
            }
            if (opcao == 0) {

                if (BeanLogin.isIsControlReserveAccess()) {

                    new JDialogControlProductExpiring(this, true).setVisible(true);

                } else {

                    JOptionPane.showMessageDialog(null, "Você não tem acesso a esta função.", "Acesso Negado!", JOptionPane.INFORMATION_MESSAGE);

                }
            }
        }
    }

    private void fnOpenURL(URI uri) {
        if (Desktop.isDesktopSupported()) {

            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(uri);

            } catch (IOException ex) {
                System.err.println("ERROR::" + ex);
                //newXML.generateLog(ex.toString());
            }
        } else {
            System.err.println("Erro de compatibilidade.");
        }

    }

}
